### DISCUSSION TITLE
External Database via pg_service.conf

### DISCUSSION THREAD

**Discussion by damonearp** [goharbor/harbor#15413] [Q&A]
Is there anyway to tell harbor to connect to an external database with a connection string like `service=harbor`?

We're trying to get harbor working with Vault database credentials which are short lived and injected into containers by the vault-agent.  I assume that having vault-agent updating the `harbor.yml` regularly will not be enough, as we'd need to trigger a reload of the configuration by harbor. In the past we've had vault-agent simply provide a `pg_service.conf` file and by setting the env `PGSERVICEFILE=` we can rely on `libpq` to reread that file on connection ensuring updated creds.

From the template config, I'm not sure this can be done.

Thanks

```yaml
external_database:
  harbor:
    host: harbor_db_host
    port: harbor_db_port
    db_name: harbor_db_name
    username: harbor_db_username
    password: harbor_db_password
    ssl_mode: disable
    max_idle_conns: 2
    max_open_conns: 0
```
