### DISCUSSION TITLE
How to setup a S3 AWS compatible storage (not AWS) on Harbor?

### DISCUSSION THREAD

**Discussion by FeryET** [goharbor/harbor#16425] [Q&A]
Hi.

I'm trying to use an AWS compatible S3 bucket as my storage backend for harbor, and I've set this in `harbor.yml` file.

```yaml
storage_service:
  s3:
    accesskey: xxxxxxx
    secretkey: xxxxxxx
    bucket: some-docker-registry
    regionendpoint: https://s3.ir-thr-at1.arvanstorage.com
    region: default
    v4auth: false
    chunksize: 5242880
    rootdirectory: /
 redirect:
    disabled: true
```

The service which provides me does not indicate any region, so I used `default` as the region value.

The problem I'm having is that apparently the region endpoint is not accessible in my registry containers. Reading the `registry.log` I see this:

> 
> Feb 27 07:41:55 192.168.64.1 registry[1494139]: time="2022-02-27T07:41:55.665802125Z" level=error msg="error putting payload into blobstore: s3aws: RequestError: send request failed
> 
> Feb 27 07:41:55 192.168.64.1 registry[1494139]: caused by: Put "https:/company-docker-registry/docker/registry/v2/repositories/test-repository/test-image/_manifests/revisions/sha256/5b7d63b34a73cd31cb12ca1cd7e4ca3b259122ccee528562386fa54186d86bcf/link": dial tcp: lookup s3.ir-thr-at1.arvanstorage.com on 127.0.0.11:53: read udp 127.0.0.1:45672->127.0.0.11:53: i/o timeout" auth.user.name=usernamei go.version=go1.15.6 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host=registry.company.co http.request.id=3f304631-453a-41a2-b547-79fd9c71844f http.request.method=PUT http.request.remoteaddr=5.202.202.159 http.request.uri="/v2/test-repository/test-image/manifests/latest" http.request.useragent="docker/20.10.12 go/go1.16.12 git-commit/459d0df kernel/5.13.0-27-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12 \(linux\))" vars.name="test-repository/test-image" vars.reference=latest 
> 
> 

What should I do for the endpoint to be accessible?
