### DISCUSSION TITLE
Usage and Tracking of Cache Layer Feature

### DISCUSSION THREAD

**Discussion by srinath-chandra** [goharbor/harbor#18812] [Q&A] [answered]
We have recently enabled the Layer Caching feature and tested some large pulls, but I don't see any improvements in the performance or in time and even I don't see any spike on our Azure Redis Cache usage and even anything in Harbor logs!

```
cache:
  # default is not enabled.
  enabled: true
  # default keep cache for one day.
  expireHours: 24
```

Is there any other configuration, I'm missing and how could we track the layer caching operation?

Can someone please advise.
