### DISCUSSION TITLE
Using ctr to push to harbor registry

### DISCUSSION THREAD

**Discussion by cwrx777** [goharbor/harbor#20078] [Q&A]
harbor version: `2.10`, images obtained from the [offline installer](https://github.com/goharbor/harbor/releases/download/v2.10.0/harbor-offline-installer-v2.10.0.tgz)
harbor helm: [`1.14.0` ](https://github.com/goharbor/harbor-helm/releases/tag/v1.14.0)

I'm running harbor as part of k3s (v1.29) cluster.
In k3s master, i have configured `registries.yaml` as such:
```yaml
mirrors:
  <REGISTRY>:
    endpoint:
      - "https://<REGISTRY>/v2"
configs:
   <REGISTRY>:
    auth:
      username: <username>
      password: <password>
    tls:
      cert_file: <path to tls.crt>
      key_file:  <path to tls.key>
      ca_file:   <path to ca.crt>
      insecure_skip_verify: true
```

for user accounts, I have created two user accounts:
1. user account, for logging into UI
   - it is also a `Maintainer` on `library` project
   - it is the account that is configured in the above `registries.yaml`
2. robot account in `library` project, with permission;
    - `repository: push,pull` 

I used the following to push:
```shell
sudo ctr image push --user "$USERNAME:$PASSWORD" <REGISTRY>/library/xxxx/yyyyyy:tag
```
Result of both user account and robot account:
```shell
ctr: unexpected status from POST request to https://<REGISTRY>/v2/library/xxxx/yyyyyy/blobs/uploads/: 401 Unauthorized
```
