### DISCUSSION TITLE
How can I change the storage spec from swift to s3?

### DISCUSSION THREAD

**Discussion by hyeyoung-leee** [goharbor/harbor#20305] [Q&A] [answered]
Hi,

I'm using swift as backend storage for harbor and I want to use s3 API instead. The backend storage is still Swift.
How can I set the harbor CR's s3 spec from swift spec?
```
storage:
      swift:
        authurl: http://alp-iaas.cloud.net/identity/v3
        authversion: "3"
        chunksize: 20971520
        container: test
        domain: default
        endpointtype: public
        insecureskipverify: false
        password: test
        region: region
        tenant: test
        username: test
```

Thanks.
