### DISCUSSION TITLE
How to run Harbor Registry Behind Haproxy with ca-cert verify required

### DISCUSSION THREAD

**Discussion by TnGadaria** [goharbor/harbor#20744] [Q&A]
Hi,
I do have a setup with Harbor Instace-1 and a replication registry, and I am using Haproxy to terminate the certificate, also the backend server (Harbor registry) is using SSL. and this works fine.

Now, I am trying to validate the backend server (Harbor registry) certificate from haproxy using haproxy's `ca-cert varify required` directive for backed, which gives me a 503 error while accessing the harbor portal. 

Can you please help me with this? Let me know if you need additional configuration

For now Harbor configuration looks like this
=================================
```
# Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: 192.168.10.144

# http related config
# http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  # port: 80

# https related config
https:
  # https port for harbor, default is 443
  port: 443
  # The path of cert and key files for nginx
  certificate: /data/harbor.crt
  private_key: /data/harbor.key
  # enable strong ssl ciphers (default: false)
  # strong_ssl_ciphers: false`
  
 # Uncomment external_url if you want to enable external proxy
# And when it enabled the hostname will no longer used
# external_url: https://reg.mydomain.com:8433
```
