### DISCUSSION TITLE
Oracle Container Registry

### DISCUSSION THREAD

**Discussion by sashalarsoo** [goharbor/harbor#21558] [General]
Hey harbor users !
Can i use an Oracle container registry as a registry endpoint in order to proxy cache ?

**Comment by bupd** [comment]
Currently Harbor doesn't have Oracle Container Registry Adapter.

Eventhough you can try using Docker Registry Adapter and use Oracle registry.

![oracle regsitry](https://github.com/user-attachments/assets/6263fbb5-c765-40ac-8ba5-f78ce8eb3fab)

Hope this helps.

**Comment by sashalarsoo** [comment]
Thanks it worked. I deployed my harbor in kubernetes, how could i pull an image then ?

**Reply by bupd** [reply]
You can directly pull images from the proxy cache project.

https://goharbor.io/docs/2.12.0/administration/configure-proxy-cache/

**Reply by sashalarsoo** [reply]
I'm having issues. I made a nodeport on harbor-registry, and login with my creds but  : 
`docker pull 10.5.1.92:31154/proxy/3d-predict/job-controller:0.3.20
Error response from daemon: Head "http://10.5.1.92:31154/v2/proxy/3d-predict/job-controller/manifests/0.3.20": no basic auth credentials`

**Reply by sashalarsoo** [reply]
`docker login 10.5.1.92:31154
Username: admin
Password: 
Error response from daemon: login attempt to http://10.5.1.92:31154/v2/ failed with status: 401 Unauthorized`

**Reply by bupd** [reply]
looks like a problem with your deployment of harbor.

**Reply by bupd** [reply]
are you using helm charts to deploy harbor?

**Reply by sashalarsoo** [reply]
to what svc must i connect to when i docker login ?

**Reply by sashalarsoo** [reply]
yes i deployed with this values : expose : type : nodePort
tls: enabled: false externalURL: http://10.5.1.92

**Reply by sashalarsoo** [reply]
![image](https://github.com/user-attachments/assets/49b5adb4-45f7-4680-a7bb-1191932fe9ce)

**Reply by bupd** [reply]
you should configure your ingress to point to harbor-core on /v2/

**Reply by bupd** [reply]
so for docker login you try connecting to harbor-core directly.

**Reply by sashalarsoo** [reply]
Even with no cert , no public ip , no dns will it work ?

**Reply by sashalarsoo** [reply]
What value should i change

**Reply by bupd** [reply]
Here is an example ingress configuration you can use.

```yaml
spec:
  rules:
  - host: <your host here>
    http:
      paths:
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /v2/
        pathType: Prefix
      - backend:
          service:
            name: harbor-core
            port:
              number: 80
        path: /api/
        pathType: Prefix
      - backend:
          service:
            name: harbor-portal
            port:
              number: 80
         path: /
         pathType: Prefix

```

This would help... @sashalarsoo
