### ISSUE TITLE
Add "x-go-type" for model definitions in swagger.yaml to avoid model converting

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10658]
Add `x-go-type` for the model definitions in swagger.yaml to avoid converting our models to the swagger models:
```yaml
    x-go-type:
      import:
        package: "github.com/goharbor/harbor/src/api/artifact"
      type: "Artifact"
```
