### ISSUE TITLE
Chartmuseum not respecting swift auth options

### ISSUE THREAD

**Issue by vowywowy** [goharbor/harbor#10795]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Chartmuseum should respect the `ignoresecureverify: true` option and ignore cert errors. Instead it crashloops itself due to cert errors.

**Steps to reproduce the problem:**
Install with Chartmueseum, use swift as a storage service without adding certs, and set `ignoresecureverify: true`

**Versions:**

- harbor version: [1.10.1]
- docker engine version: [19.03.5]
- docker-compose version: [1.25.4]

**Additional context:**

- **Harbor config files:** the important part is:
```
storage_service:
  swift:
    username: xxxxxx
    password: *****
    authurl: https://*****:****/v3
    tenant: yyyyyyy
    domain: zzzzzzzz
    region: aaaaaaaaa
    container: ffffffffffff
    insecureskipverify: true
```
- **Log files:** You can get them by package the `/var/log/harbor/` .
in the chartmuseum log:
```
panic: Openstack (authenticate): Post https://*****:****/v3/auth/tokens: x509: certificate signed by unknown authority
```
