### ISSUE TITLE
Image replication from Quay.io finished successfully but containers are not downloaded

### ISSUE THREAD

**Issue by danielnbalasoiu** [goharbor/harbor#11323]
**Expected behavior and actual behavior:**
Expected behavior: `prometheus:latest` image should be downloaded into library after replication job finished with **SUCCESS**.
Actual behavior: Empty library. No container images.

**Steps to reproduce the problem:**
1. Go to [quay.io](https://quay.io) and create an account (if you don't have one)
2. Go to **Account Settings** - **Robot Accounts** and create a **New Robot Account**
3. Go to **Administration** - **Registries** - **NEW ENDPOINT**
4. Go to Harbor and create a **New Registry Endpoint** with the following details:
- **Provider**: `quay.io`
- **Name**: `q`
- **Endpoin URL**: `https://quay.io/`
- **Access ID**: [robot-account-id]
- **Access Secret**:  [robot-account-secret]
- Check **Verify Remote Cert** box
- **TEST CONNECTION**
- Hit **OK** button if connection is successful. If not, check credential details again.
5. Go to  **Administration** - **Replications** and add a *NEW REPLICATION RULE** with the following details:
- **Name**: `quay-prometheus`
- **Source registry**: Select `q-https://quay.io/` from the drop-down menu
- **Source resource filter**:
  - **Name**: `prometheus`
  - **Tag**: `latest`
- **Trigger Mode**: `Manual`
- Check `Override` box
- Check `Enable rule` box and save
6. Hit **REPLICATE** button and confirm replication. Replication job status should be listed in the **Executions** table. (it will display **SUCCESS**)
7. Click on the **ID** of the job to go to **EXECUTION** page and check job's details.
Expected result:
`SUCCESS`: `1` 
`FAILURE`: `0` 
`IN PROGRESS`: `0` 
`STOPPED`: `0` 

Actual result:
`SUCCESS`: `0` 
`FAILURE`: `0` 
`IN PROGRESS`: `0` 
`STOPPED`: `0` 

**Versions:**
Please specify the versions of following systems.

- harbor version: `v1.10.1-f3e11715`
- docker engine version: `19.03.5`
- docker-compose version: `1.25.1, build a82fef0`

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
```yaml
hostname: harbor.mylab.com

http:
  port: 80

harbor_admin_password: [redacted]

database:
  password: [redacted]
  max_idle_conns: 50
  max_open_conns: 100

data_volume: /data

clair:
  updaters_interval: 12

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 1.10.0
```

- **Log files:** You can get them by package the `/var/log/harbor/` .
[jobservice.log](https://github.com/goharbor/harbor/files/4389474/jobservice.log)
[chartmuseum.log](https://github.com/goharbor/harbor/files/4389475/chartmuseum.log)
