### ISSUE TITLE
Private repo not work with k8s imagePullSecrets 

### ISSUE THREAD

**Issue by foxyoyo** [goharbor/harbor#11383]
Hi sirs : 
    i try to leverage k8s secret in my deployment.yaml  to do image pull from Harbor (v1.10.1-rc1) , 
but it will failed with error access denied   , but i am sure my deployment.yaml is fine , because if i change the repo to public , then it can run well  . below are the related log , i am not sure what i missed , if anyone experienced can advise me , that would be very appreciated your help .

**---------------  error from my kubectl describe pod -------**
Failed to pull image "xxxxx:tag ": rpc error: code = Unknown desc = Error response from daemon: pull access denied for "xxxxx:tag ":, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
**---------------  my k8s create secret -------**
do the docker login on my k8s-mgm node 
then 
kubectl create secret generic harbor-secret \
    --from-file=.dockerconfigjson=/root/.docker/config.json \
	--namespace=xxxxxxx \
    --type=kubernetes.io/dockerconfigjson

**------------------my deployment sample -----------------------**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxxxx
  namespace: xxxxx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: xxxxx
  template:
    metadata:
      labels:
        k8s-app: xxxxxx
	  spec:
	  containers:
      - name: xxxx
        image: xxxxxxx
        imagePullPolicy: Always
      imagePullSecrets:
      - name: harbor-secret

**Comment by heww** [comment]
Can you dobule check that the `harbor-secret` is correct following the steps in https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#inspecting-the-secret-regcred ?

And ensure that the `harbor host` in the  output of `kubectl get secret harbor-secret --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode`. Username and password is correct.

**Comment by foxyoyo** [comment]
hi heww , 
     many thxs your help and reply , finally i found the workaround solution , but i dont know  is that the root caused , maybe about self-signed cert  ?   
    the only thing what i changed  , i use docker harbor  FQDN insted of ip in my deployment.yaml  , then it work  ! 
    if  i run  pull ip  ie: docker pull x.x.x.x command on k8s worker node , the pull work fine , but thru kubectl create -f deployment.yaml would failed with " rpc error: code = Unknown desc = Error response from daemon: pull access denied for "xxxxx:tag " 

--------------------------------------------------
    spec:
      containers:
      - name: flask2es
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
        image: harbor-rc.xx.mydomain.com/dev/myapp:v2     <----  change to this
        #image: x.x.x.x/dev/myapp:v2    <----- original 
        imagePullPolicy: Always

**Comment by heww** [comment]
Pull throught IP or FQDN depend on your configurations of harbor.

When harbor was installed by docker-compose, the configuration is `hostname` in the `harbor.yml`.

When harbor was installed by helm, the configuration is `externalURL` in `values.yaml`.

**Comment by YoshieraHuang** [comment]
Hi，
   I meet the same things. I cannot pull image from my private harbor. I install harbor by helm. I do use FQDN to locate my images.
  I logs the harbor-core pods and I see this:
```
Repository not exist, repo: harbor.pims.private/dynx/dynx-front, error: harbor-harbor-notary-server:4443 does not have trust data for harbor.pims.private/dynx/dynx-front, returning empty signature
```

and then I checked the notary server  and I see:
```
{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"harbor-notary-ca\\\")\"","time":"2020-04-30T08:30:21Z"}
```

here is my helm value.yaml:
```yaml
# helm install harbor harbor/harbor -f ./helm_value.yaml
expose:
  ingress:
    hosts:
      core: harbor.pims.private
      notary: notary.harbor.pims.private
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-pvc
      subPath: registry
    chartmuseum:
      existingClaim: harbor-pvc
      subPath: charmuseum
    jobservice:
      existingClaim: harbor-pvc
      subPath: jobservice
    database:
      existingClaim: harbor-pvc
      subPath: database
    redis:
      existingClaim: harbor-pvc
      subPath: redis
externalURL: "https://harbor.pims.private"
harborAdminPassword: XXXXXXXX
```
