### ISSUE TITLE
unable to push after successful login

### ISSUE THREAD

**Issue by cameronbraid** [goharbor/harbor#11437]
I can docker login fine, and docker push fails with `unauthorized: authentication required`

```
docker login harbor-dev.drivenow.com.au
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

```
docker push harbor-dev.drivenow.com.au/test/redis-operator:latest
The push refers to repository [harbor-dev.drivenow.com.au/test/redis-operator]
4025cbd82fa5: Pushing [==================================================>]  12.29kB
fcb6471fe7d4: Preparing 
39db6acceed3: Pushing [>                                                  ]  68.61kB/5.533MB
unauthorized: authentication required
```

deployed using helm chart version `v1.3.1`

I am using an istio 1.5 gateway for SSL termination, and using `http` form gateway to harbor, configured with values :

```
expose:
  type: clusterIP    
  tls:
    enabled: false

externalURL: https://harbor-dev.drivenow.com.au

persistence:
  enabled: true
  imageChartStorage:
    type: 'filesystem'
logLevel: debug
harborAdminPassword: #####

# use hard coded secrets so that helm doesn't generate one each time
secretkey: ########
core: 
  secret: #########
  xsrfKey: ###############
registry: 
  secret: ###########
jobservice:
  secret: ###########

database:
  type: external
  external:
    host: "postgres"
    port: "5432"
    username: "harbor"
    password: "#####"

    coreDatabase: "registry"
    clairDatabase: "clair"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"

    # will use istio mutual tls 
    sslmode: "disable" #Connection method of external database (require, prefer, disable)	disable

redis:
  type: external
  external:
    host: redis-cluster-harbor-redis
    port: 6379 
    coreDatabaseIndex: 0
    jobserviceDatabaseIndex: 1
    registryDatabaseIndex: 2 
    chartmuseumDatabaseIndex: 3 
chartmuseum:
  enabled: false
clair:
  enabled: false
notary:
  enabled: false
```

I use an envoy filter to ensure the x-forwarded-* headers are sent

```
# https://github.com/istio/istio/issues/7964#issuecomment-554241818
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff-trust-hops
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          use_remote_address: true
          xff_num_trusted_hops: 1
```

Any help would be appreciated as I have spent a long time trying to resolve this and i'm out of ideas
