### ISSUE TITLE
Bad volumes for trivy when internal tls enabled

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11551]
When internal tls enabled, the volumes generated in docker-compose.yml is bad format.

```yaml
  trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:dev
    restart: always
    cap_drop:
      - ALL
    dns_search: .
    networks:
      - harbor
    depends_on:
      - redis
    volumes:
      - type: bind
        source: /data/trivy-adapter/trivy
        target: /home/scanner/.cache/trivy
      - type: bind
        source: /data/trivy-adapter/reports
        target: /home/scanner/.cache/reports
    volumes:
      - type: bind
        source: /data/secret/tls/harbor_internal_ca.crt
        target: /harbor_cust_cert/harbor_internal_ca.crt
      - type: bind
        source: /data/secret/tls/trivy_adapter.crt
        target: /etc/harbor/ssl/trivy_adapter.crt
      - type: bind
        source: /data/secret/tls/trivy_adapter.key
        target: /etc/harbor/ssl/trivy_adapter.key
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "trivy-adapter"
    env_file:
      ./common/config/trivy-adapter/env
```
