### ISSUE TITLE
Helm Packages YAML Files

### ISSUE THREAD

**Issue by utkudarilmaz** [goharbor/harbor#11683]
# Missing Comments on YAML Files 

When pulling Helm charts from Harbor, comments not showing on yaml files and key order is disappearing and all keys ordered alphabetically.

Mostly cases, written comments on _values.yaml_ file or other yaml files like _Chart.yaml_ very helpful for using charts and contains important information about chart.

Releated issue: #10320

Original values.yaml file:
```yaml
imagePullSecrets:
  name: ""

## some comment
resources: {}

## extra comment
affinity: {}
tolerations: []
```

Pulled values.yaml file:
```yaml
affinity: {}
imagePullSecrets:
  name: ""
resources: {}
tolerations: []
```
