### ISSUE TITLE
Automatically create volume mount for Trivy scanner in offline mode

### ISSUE THREAD

**Issue by danielpacak** [goharbor/harbor#12000]
When you set the `trivy.skip_update` flag to `true`, you have to download the Trivy DB file manually and mount it in the Trivy adapter container by editing `docker_compose.yaml` and adding such volume bind by hand.

If we introduce the `trivy.trivy_db_dir` configuration property and if it's not blank, such volume bind can be added by the installer / prepare script automatically:

```
$ ls /Users/dpacak/tmp/data/trivy-adapter/db
trivy.db
metadata.json
```

```yaml
## Trivy configuration
trivy:
  ## skipUpdate The flag to enable or disable Trivy DB downloads from GitHub
  ##
  ## You might want to enable this flag in test or CI/CD environments to avoid GitHub rate limiting issues.
  ## If the flag is enabled you have to manually download the `trivy.db` file and mount it in the
  ## /home/scanner/.cache/trivy/db/trivy.db path.
  skip_update: false
  ## trivy_db_dir The path to the directory which contains `trivy.db` and `metadata.json` files
  ##
  ## Only applicable if `trivy.sip_update` is set to `true`.
  trivy_db_dir: /Users/dpacak/tmp/data/trivy-adapter/db
```

```yaml
version '2.3'
services:
  trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:v2.0.0
    restart: always
    cap_drop:
      - ALL
    dns_search: .
    networks:
      - harbor
    depends_on:
      - redis
    volumes:
      - type: bind
        source: /Users/dpacak/tmp/data/trivy-adapter/trivy
        target: /home/scanner/.cache/trivy
      - type: bind
        source: /Users/dpacak/tmp/data/trivy-adapter/reports
        target: /home/scanner/.cache/reports
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
      - type: bind
        source: /Users/dpacak/tmp/data/trivy-adapter/db
        target: /home/scanner/.cache/trivy/db
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "trivy-adapter"
    env_file:
      ./common/config/trivy-adapter/env
```
