### ISSUE TITLE
sync image from harbor to dockerhub failed 

### ISSUE THREAD

**Issue by shaowenchen** [goharbor/harbor#12390]
![image](https://user-images.githubusercontent.com/43693241/86430461-ecf25c00-bd24-11ea-9f1c-db741ef26f78.png)

If I set Source resource filter as mynamespace/myimagename , it works. while mynamespace/** , it failed.

I try to set max_open_conns :

```yaml
# Harbor DB configuration
database:
  # The password for the root user of Harbor DB. Change this before any production use.
  password: root123
  # The maximum number of connections in the idle connection pool. If it <=0, no idle connections are retained.
  max_idle_conns: 50
  # The maximum number of open connections to the database. If it <= 0, then there is no limit on the number of open connections.
  # Note: the default number of connections is 100 for postgres.
  max_open_conns: -1
```

It failed again.
