### ISSUE TITLE
A default `library` can be auto appended to the pull path when proxying cache dockerhub 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#12719]
Now, for pulling popular images of the docker hub, user needs to explicitly specify the `library` namespace.

`docker pull 10.192.203.193/szou_proxy/library/redis:4.0`

Actually, we can support the shorten pulling path for dockerhub (so far) by automatically appending the default `library` if the user does not specify the namespace:

`docker pull 10.192.203.193/szou_proxy/redis:4.0`

If the user specifies other namespaces, then directly ignore:

`docker pull 10.192.203.193/szou_proxy/goharbor/harbor-core:2.1`

**Comment by flixpae** [comment]
Is there a plan to implement this ?
i am trying to setup a proxy-repository that behaves somewhat like the standard docker registry
but currently i need to specify

$HARBOR_SERVER/library/library/$IMAGE:$TAG
though i created the proxy project with the name "library"

**Comment by morlay** [comment]
mirror proxy support base path could resolve this.

`${HARBOR}${BASE_PATH}/${IMAGE}` => `${HUB}${BASE_PATH}/${IMAGE}`

```
// new project as mirror proxy
${HARBOR}/library: mirror_proxy("docker.io", "/library")

${HARBOR}/library/nginx:latest => docker.io/library/nginx:latest

```

The rule could be used for multi proxy too.
```
${HARBOR_PROXY}/docker.io: mirror_proxy("docker.io", "/")
${HARBOR_INTERNAL}/docker.io: mirror_proxy("${HARBOR_PROXY}", "/docker.io")

${HARBOR_INTERNAL}/docker.io/library/busybox 
=> ${HARBOR_PROXY}/docker.io/library/busybox
=> docker.io/library/busybox
```

**Comment by flixpae** [comment]
to what is "mirror proxy support" related ?

**Comment by morlay** [comment]
@flixpae just a suggestion. 

v2.1 have a new feature `Proxy Cache` (i renamed it).
i think if it support to configure `BASE_PATH` could solve this issue.

**Comment by flixpae** [comment]
from what i understand (read in the documentation) harbor imposes to specify the harbor "project" in the pull command
if there would be a way present the docker client with the same path that he expects from e.g index.docker.io. 
It would be possible to use harbor as a registry-mirror in the docker-daemon config
so minimal user adjustment is needed when using harbor as pull-through proxy

@morlay when i change the BASE_PATH how does harbor know if to fetch from  remote-registry or a internal project ?

**Comment by morlay** [comment]
Proxy cache could not be used in `registry-mirror`. i think we only pull image with a path prefix.

for your usage.

first create a proxy cache project `library` as  `proxy_cache("docker.io", "/library")`

when you pull

```
docker pull $HARBOR_SERVER/library/nginx
```

The request for path `/library/nginx` fisrt touch harhor, harhor know `/library` should return as proxy_cache,

then fetch from target hub with converted path `"docker.io" + "/library" + "/nginx"`

so the `BASE_PATH` is for proxy_cache to get final url.

**Comment by mmiller1** [comment]
we worked around the lack of this feature in our ingress controllers. This is a hack and I would  love to see better support in harbor, but using this ingress spec (ingress-nginx specific) we are able to register our harbor instance as a registry mirror in /etc/docker/daemon.json and have commands like `docker pull mysql` pull from harbor instead of dockerhub.

assuming the proxy cache project is called "proxy" we use:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /v2/proxy/library/$1
    nginx.ingress.kubernetes.io/rewrite-log: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ( $request_uri ~ "scope=repository%3Alibrary(.*)" ) {
        rewrite ^ /service/token?scope=repository%3Aproxy%2Flibrary$1 break;
      }
  labels:
    app: harbor
  name: harbor-proxy-ingress
  namespace: harbor
spec:
  rules:
  - host: harbor.my.domain
    http:
      paths:
      - backend:
          serviceName: harbor-core
          servicePort: 80
        path: /v2/library/(.*)
      - backend:
          serviceName: harbor-core
          servicePort: 80
        path: /service/token
```
this rewrites the request URL made to harbor for the image to include the proxy project name, and modifies the token request parameters to include the project scope.
