### ISSUE TITLE
Redis sentinel does not work very properly

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#12733]
Three sentinel nodes: myredis_sentinel1, myredis_sentinel2, myredis_sentinel3

`myredis_sentinel1` is the activated sentinel server at first.

No matter whether 2 and 3 are up or down, once the 1 is down(docker pause), the scanning, replication will not work anymore.

**Comment by bitsf** [comment]
This need check trivy-adapter 's code

**Comment by bitsf** [comment]
I think the problem may be tcp connect to sentinel host does not use a timeout

**Comment by bitsf** [comment]
actually if the myredis_sentinel1 is really down with cmd (docker stop myredis_sentinel1), it will switch to myredis_sentinel2 quickly.

**Comment by bitsf** [comment]
replication job hang is because we didn't set the redis read timeout.
workaround is modify configure file in harbor install folder `common/config/registry/config.yml`, add param readtimeout
```
redis:
  # sentinel hosts with comma
  addr: 10.161.71.1:30011,10.161.71.1:30012,10.161.71.1:30013
  sentinelMasterSet: mymaster
  password: 123
  db: 1
  readtimeout: 10000000000
  writetimeout: 10000000000
  dialtimeout: 10000000000
```
