### ISSUE TITLE
push image can not display on harbor ui

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#12804]
What can we help you?

Harbor version: v1.10.1
Deploy way: helm with nodeport

After we pushed image by docker push xxx, it can be pulled by docker pull successfully, but it can not display on harbor ui page, and the registry pod use high cpu and memory, after restart registry pod, and retry previous operations(docker push)，it can be displayed on harbor ui page immediately.

![image](https://user-images.githubusercontent.com/31262637/90494350-01c06d00-e176-11ea-8110-a1a6999c7b14.png)

registry config yaml
```yaml
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disable: false
redis:
  addr: "harbor-harbor-redis:6379"
  db: 2
http:
  relativeurls: false
  addr: :5000
  # set via environment variable
  # secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: "http://x.x.x.x:31104/service/token"
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
validation:
  disabled: true
notifications:
  endpoints:
    - name: harbor
      disabled: false
      url: http://harbor-harbor-core/service/notifications
      timeout: 3000ms
      threshold: 5
      backoff: 1s
      ignoredmediatypes:
        - application/vnd.docker.image.rootfs.diff.tar.gzip
        - application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
        - application/vnd.oci.image.layer.v1.tar
        - application/vnd.oci.image.layer.v1.tar+gzip
        - application/vnd.oci.image.layer.v1.tar+zstd
        - application/vnd.oci.image.layer.nondistributable.v1.tar
        - application/vnd.oci.image.layer.nondistributable.v1.tar+gzip
        - application/vnd.oci.image.layer.nondistributable.v1.tar+zstd
        - application/octet-stream
```

**Comment by chlins** [comment]
There's a similar issue: https://github.com/goharbor/harbor/issues/12577

**Comment by ywk253100** [comment]
Could you show me the log of core and registry when you push image the first time?

**Comment by chlins** [comment]
@ywk253100 Looks like registry not send webhook notification of push event to core immediately,  after few hours(maybe more longer), it can display on ui auto. We do some performence testing for our bussiness what will call harbor api(get tag)，we have 100~ repo, and each repo has 20~ tags.

logs:
[core.log](https://github.com/goharbor/harbor/files/5093928/core.log)
[registry.log](https://github.com/goharbor/harbor/files/5093929/registry.log)

**Comment by Morriz** [comment]
any updates here? we also don't see successful pushes show up in the UI

**Comment by Morriz** [comment]
what service and port should be open to receive that webhook?

**Comment by bitsf** [comment]
Another customer said they met similar issue, and fix it by just restart the registry pod in k8s, harbor version is 1.9.0

**Comment by Morriz** [comment]
That does not work. Same issue remains :|

**Comment by chlins** [comment]
@Morriz After restart the registry pod, did you re push the image?

**Comment by Morriz** [comment]
I am pretty sure I did. We are running with istio and don't use the suggested setup  as that forces nginx with tls. (We have mtls from istio already.)

So I would really like to be sure that harbor core is the webhook receiver. We don't see ingress logs of any incoming webhook.

Is there a state diagram of sorts? With all the flows and actors?

**Comment by Morriz** [comment]
Also pointing to this older issue reporting the same: #11684

**Comment by osaffer** [comment]
Hi,

Did you fix the problem ? 

I am facing with same behavior.

In registry log, I have :+1: 
level=error msg="retryingsink: error writing events: httpSink{http://harbor-core/service/notifications}: response status 404 Not Found unaccepted, retrying"

curl http://harbor-core/service/notifications
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>

Regards,

**Comment by jabbors** [comment]
Ensure that your the port names in your harbor component services are prefixed with `http-` or `tcp-` as this is a requirement by Istio. It fixes our issues.

An example

```
ports:
  - name: http-registry
    port: 5000
    protocol: TCP
    targetPort: 5000
```

If you install harbor through helm, I don't think the charts have been updated the add these prefixes. We don't install with helm so we have full control of the resources deployed. Would like to switch to helm if/when fixed.

We are using harbor 1.10.5 with database auth. I've been experimenting with 2.x and Istio but see the same issue. By switching to basic authentication in 2.x, I got something working but I'd like to keep database authentication so we have decided to stay on 1.10.x until we figure out why and how to fix it.
