### ISSUE TITLE
Trouble deploying Harbor with SSL

### ISSUE THREAD

**Issue by MicahDShackelford** [goharbor/harbor#12860]
Having trouble setting up Harbor with an SSL. My current setup is running my domain to a Nginx Reverse Proxy that points to my Harbor server. I have the server and Nginx reverse proxy setup with the crt & key. The web interface does show that the site is secured, however when I go to docker login I get an `x509: certificate signed by unknown authority`. A temporary workaround was adding the certificate to my client, however this is not a good long term solution from my end. My certification comes from   PositiveSSL.

P.S. This is supposed to labeled as a needs help, havent opened a github issue like this before.

#### Nginx Config:
```
server {
    listen 443 ssl;
    ssl_certificate     /etc/nginx/certs/docker.*****.com/ca.crt;
    ssl_certificate_key /etc/nginx/certs/docker.*****.com/server.key;
    server_name docker.*****.com;
    location / {
        proxy_set_header Host $http_host;   # required for docker client's sake
        proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass https://*****.ddns.net:3050/;

    }
    location /v2/ {
        # Do not allow connections from docker 1.5 and earlier
        # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
        if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
          return 404;
        }
    }
}
server {
    listen 80;
    server_name docker.*****.com;
    return 301 https://$host$request_uri;
}
```

#### Harbor.yml (only the bits I have touched):
```
 Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: docker.****.com

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 3051

# https related config
https:
  # https port for harbor, default is 443
   port: 3050
  # The path of cert and key files for nginx
   certificate: /home/portainer/harbor/ssl/server.crt
   private_key: /home/portainer/harbor/ssl/server.key

# # Uncomment following will enable tls communication between all harbor components
# internal_tls:
#   # set enabled to true means internal tls is enabled
#   enabled: true
#   # put your cert and key files on dir
#   dir: /etc/harbor/tls/internal

# Uncomment external_url if you want to enable external proxy
# And when it enabled the hostname will no longer used
external_url: https://docker.****.com

# The initial password of Harbor admin
# It only works in first time to install harbor
# Remember Change the admin password from UI after launching Harbor.
harbor_admin_password: ****

# Harbor DB configuration
database:
  # The password for the root user of Harbor DB. Change this before any production use.
  password: ****
  # The maximum number of connections in the idle connection pool. If it <=0, no idle connections are retained.
  max_idle_conns: 50
  # The maximum number of open connections to the database. If it <= 0, then there is no limit on the number of open connections.
  # Note: the default number of connections is 1024 for postgres of harbor.
  max_open_conns: 1000

# The default data volume
data_volume: /home/portainer/harbor/data
```

**Comment by ywk253100** [comment]
Which version of Harbor are you using? Could you show the debug log of docker when you login?

**Comment by MicahDShackelford** [comment]
> Which version of Harbor are you using? Could you show the debug log of docker when you login?

Using Harbor 2.0.2, do you want logs from the client or server, and where will they be located so I can be sure I am getting the correct information for you?

**Comment by reasonerjt** [comment]
@MicahDShackelford 
To help us understand which host docker is trying access when the problem happens, could you paste the command you used and the complete output?

**Comment by MicahDShackelford** [comment]
> @MicahDShackelford
> To help us understand which host docker is trying access when the problem happens, could you paste the command you used and the complete output?

Sure, so I do docker login docker.****.com
And and login, then get back 
`
Get https://docker.****.com/v2/: x509: certificate signed by unknown authority
--
224 | time="2020-08-24T03:16:22Z" level=fatal


`

**Comment by MicahDShackelford** [comment]
A bit of an update to give a bit more information (and updates I have made attempting to fix), my setup is as follows:
[Nginx instance that runs proxy and points to harbor (with ssl over https)] -> [Harbor's Nginx instance (no ssl, http)] -> [Harbor instance]
I have changed the setup so the harbor instance is now running over http, because after reviewing a few guides it seems that is the way to go. 

Harbor.yml changes are as follows:
```
# Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: docker.simplisik.com

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 3050
  relativeurls: true

# https related config
https:
  # https port for harbor, default is 443
  # port: 3060

```

**Comment by MicahDShackelford** [comment]
A bit of an update to give a bit more information (and updates I have made attempting to fix), my setup is as follows:
[Nginx instance that runs proxy and points to harbor (with ssl over https)] -> [Harbor's Nginx instance (no ssl, http)] -> [Harbor instance]
I have changed the setup so the harbor instance is now running over http, because after reviewing a few guides it seems that is the way to go. 

Harbor.yml changes are as follows:
```
# Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: docker.****.com

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 3050
  relativeurls: true

# https related config
https:
  # https port for harbor, default is 443
  # port: 3060

```

I have also gone into the nginx config and disabled all of the headers that are mentioned to be removed (didnt see that previously) - error is still the same x509.
