### ISSUE TITLE
trivy container start failed

### ISSUE THREAD

**Issue by renatozhang** [goharbor/harbor#12933]
What can we help you?
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
{"built_at":"2020-06-29T08:06:05Z","commit":"799608904fe81234b6ac427b423356619d6effb6","level":"info","msg":"Starting harbor-scanner-trivy","time":"2020-09-01T07:46:56Z","version":"0.12.0"}
{"level":"warning","msg":"trivy cache dir does not exist","path":"/home/scanner/.cache/trivy","time":"2020-09-01T07:46:56Z"}
{"level":"fatal","msg":"Error: checking config: creating trivy cache dir: mkdir /home/scanner/.cache/trivy: permission denied","time":"2020-09-01T07:46:56Z"}

**Comment by winson08Li** [comment]
I also have this issue, hope someone can help

**Comment by lukasjelonek** [comment]
Had the same problem. Reason was that my storageclass did not automatically change the permissions of the trivy volume for the specified securityContext (10000:10000) in the helm chart. My workaround was to change the permissions of the volume manually to the trivy-user. Now it works.

**Comment by aureq** [comment]
Hi @ninjadq 

Is there any updates on this issue. I just performed an installation and I had the exact same issue. I can also confirm changing the local file system to `10000:10000` allowed the container to start as expected.

**Comment by lukasjelonek** [comment]
One could use a initContainer that sets the right permissions on the volume:

```
# trivy-sts.yaml
[...]
      initContainers:
      - name: set-permissions
        image: busybox:1.28
        command: ['chown', '-R', '10000:10000', '/home/scanner/.cache']
        volumeMounts:
          - name: data
            mountPath: /home/scanner/.cache
            subPath: {{ .Values.persistence.persistentVolumeClaim.trivy.subPath }}
            readOnly: false
[...]
```

**Comment by grexkin** [comment]
I also have this problem,and my permission of nfs is 777 tried many times also can not reslve it, i also need help 

[root@k8s-master harbor-helm]# kubectl logs -f harbor-trivy-0 
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2021-07-29T12:03:38Z","version":"dev"}
{"level":"warning","msg":"trivy cache dir does not exist","path":"/home/scanner/.cache/trivy","time":"2021-07-29T12:03:38Z"}
{"level":"fatal","msg":"Error: checking config: creating trivy cache dir: mkdir /home/scanner/.cache/trivy: permission denied","time":"2021-07-29T12:03:38Z"}

[root@k8s-master harbor-helm]# ll /nfs/appdata/harbor/
total 8
drwxrwxrwx 2 root root 4096 Jul 29 17:45 jobservice
drwxrwxrwx 2 root root 4096 Jul 29 17:46 trivy

**Comment by andyzheung** [comment]
> I also have this problem,and my permission of nfs is 777 tried many times also can not reslve it, i also need help
> 
> [root@k8s-master harbor-helm]# kubectl logs -f harbor-trivy-0 Appending internal tls trust CA to ca-bundle ... find: '/etc/harbor/ssl': No such file or directory Internal tls trust CA appending is Done. {"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2021-07-29T12:03:38Z","version":"dev"} {"level":"warning","msg":"trivy cache dir does not exist","path":"/home/scanner/.cache/trivy","time":"2021-07-29T12:03:38Z"} {"level":"fatal","msg":"Error: checking config: creating trivy cache dir: mkdir /home/scanner/.cache/trivy: permission denied","time":"2021-07-29T12:03:38Z"}
> 
> [root@k8s-master harbor-helm]# ll /nfs/appdata/harbor/ total 8 drwxrwxrwx 2 root root 4096 Jul 29 17:45 jobservice drwxrwxrwx 2 root root 4096 Jul 29 17:46 trivy

I met the same problem, did you solve it?

**Comment by andyzheung** [comment]
> I also have this problem,and my permission of nfs is 777 tried many times also can not reslve it, i also need help
> 
> [root@k8s-master harbor-helm]# kubectl logs -f harbor-trivy-0 Appending internal tls trust CA to ca-bundle ... find: '/etc/harbor/ssl': No such file or directory Internal tls trust CA appending is Done. {"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2021-07-29T12:03:38Z","version":"dev"} {"level":"warning","msg":"trivy cache dir does not exist","path":"/home/scanner/.cache/trivy","time":"2021-07-29T12:03:38Z"} {"level":"fatal","msg":"Error: checking config: creating trivy cache dir: mkdir /home/scanner/.cache/trivy: permission denied","time":"2021-07-29T12:03:38Z"}
> 
> [root@k8s-master harbor-helm]# ll /nfs/appdata/harbor/ total 8 drwxrwxrwx 2 root root 4096 Jul 29 17:45 jobservice drwxrwxrwx 2 root root 4096 Jul 29 17:46 trivy
==============
I met the same problem, did you solve it?
@grexkin

**Comment by hernando-garcia** [comment]
I had the same issue while upgrading from v2.6.0 -> v2.7.0 on a Harbor deployment using docker.
The solution as stated by lukasjelonek was to add to the docker-compose:

```
trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:v2.7.0
    command: ['chown', '-R', '10000:10000', '/home/scanner/.cache']
[...]
```
That solved it for me.
