### ISSUE TITLE
In Harbor 2.0.2 cannot configure redirection from http to https in config.yml file

### ISSUE THREAD

**Issue by Dzhan85** [goharbor/harbor#12959]
Cannot login from CLI
error 
```
Error response from daemon: Get https://hub.xxxxxxxxx/v2/: unauthorized: authentication required

```
My application behind proxy. 

in old version I could add some modification in auth token in config.yml, from http to https

```
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://xxxxxxxxxxxx/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry

``` 

How to solve this problem in version 2.0.2

**Comment by reasonerjt** [comment]
@Dzhan85 
This error means you are not using the correct credentials
Why do you  think it's due to the setting in registry in terms of http vs. https?

**Comment by Dzhan85** [comment]
> @Dzhan85
> This error means you are not using the correct credentials
> Why do you think it's due to the setting in registry in terms of http vs. https?


My harbor is behind  Microsoft AD FS  WAP( proxy), it is deployed in container on and exposed on http port and then redirected to outside through https. In old version we had feature to set authentication realm to **https**
```
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://xxxxxxxxxxxx/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
```
but by default it is redirects to http and I cannot login to registry.
