### ISSUE TITLE
Unable to configure a project with proxy cache capabilities

### ISSUE THREAD

**Issue by mvisonneau** [goharbor/harbor#12995]
**Expected behavior and actual behavior:**

When I try to add a new proxy-cache registry/project, I expect it to be created successfully. However, it throws me a `bad request: unsupported registry type docker-hub`

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1761583/92378482-c6261c80-f0fd-11ea-8843-5947786a0817.png">

Here is the endpoint I used:

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/1761583/92378581-e8b83580-f0fd-11ea-96c9-12442e4fa685.png">

**Steps to reproduce the problem:**

- Installed using the helm chart `v1.4.2` with following values

```yaml
---
.tag: &tag v2.1.0-rc1

externalURL: https://harbor.foo.bar

expose:
  ingress:
    hosts:
      core: harbor.foo.bar
      notary: notary.foo.bar

nginx:
  image:
    tag: *tag

portal:
  image:
    tag: *tag

core:
  image:
    tag: *tag

jobservice:
  image:
    tag: *tag

registry:
  registry:
    image:
      tag: *tag

chartmuseum:
  image:
    tag: *tag

clair:
  clair:
    image:
      tag: *tag

trivy:
  image:
    tag: *tag

notary:
  server:
    image:
      tag: *tag

database:
  internal:
    image:
      tag: *tag

redis:
  internal:
    image:
      tag: *tag

harborAdminPassword: 'xxx'
secretKey: 'xxx'
```

- harbor version: v2.1.0-rc1
