### ISSUE TITLE
Internal server error when retrieving logs from Retention executions

### ISSUE THREAD

**Issue by kmmanto** [goharbor/harbor#13011]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected:
I will be able to see the execution log from a Tag Retention policy run.

Actual:
`{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}` 

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

1. Configure Tag Retention policies.
2. Let it run in the specified schedule
3. Once it is executed, check the Log
4. `{"errors":[{"code":"UNKNOWN","message":"internal server error"}]}` is returned

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.0.2-e91b4ff1]
- docker engine version: [19.03.8]
- docker-compose version: [1.24.1, build 4667896b]

**Additional context:**

`storage_service` is set to a local minio instance

**Comment by steven-zou** [comment]
@kmmanto 

Some errors may occur at the server side (then we can see `internal server error`). Could you please provide the related logs (core.log, jobservice.log) for doing troubleshooting?

**Comment by stephenwolfe1** [comment]
Consistent error on any version up to 1.10.5 for me. Happens anytime you try to view a job log in the UI. Error is below. Looking for docs on how to configure the log data but no luck so far.


`harbor-harbor-core-5f559d6ff8-ml69c core 2020-10-07T21:29:02Z [ERROR] [/common/api/base.go:233]: http error: code 500, message {"code":10009,"message":"failed to get the job log","details":"no log data getter is configured"}`

**Comment by sharkymcdongles** [comment]
I am also experience the same problem.

I see this when I try: {"errors":[{"code":"UNKNOWN","message":"internal server error"}]}

This is the endpoint it tries to go to: /api/v2.0/replication/executions/13/tasks/777/log

**Comment by duyanghao** [comment]
@steven-zou same problem for me, Is there any progress?

**Comment by bitsf** [comment]
@duyanghao Do you mean you see the same error log in jobservice.log

**Comment by ngalanis819** [comment]
As @sharkymcdongles mentioned we get the same errors. Exactly the same error in core.log.
In jobservice.log the below errors are lined up:

`Feb  3 11:54:24 jobservice[5100]: 2021-02-03T11:54:24Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/49a98fa7760ae365312dc1b0/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"error for getting log of job 49a98fa7760ae365312dc1b0: {\"code\":10010,\"message\":\"object is not found\",\"details\":\"49a98fa7760ae365312dc1b0\"}"}`
`Feb  3 12:34:23 jobservice[5100]: 2021-02-03T12:34:23Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/49a98fa7760ae365312dc1b0/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"error for getting log of job 49a98fa7760ae365312dc1b0: {\"code\":10010,\"message\":\"object is not found\",\"details\":\"49a98fa7760ae365312dc1b0\"}"}`
`Feb  3 12:38:26 jobservice[5100]: 2021-02-03T12:38:26Z [INFO] [/jobservice/logger/sweeper_controller.go:97]: 33 outdated log entries are sweepped by sweeper *sweeper.FileSweeper`
`Feb  3 12:43:4 jobservice[5100]: 2021-02-03T12:43:43Z [ERROR] [/jobservice/api/handler.go:288]: Serve http request 'GET /api/v1/jobs/49a98fa7760ae365312dc1b0/log' error: 500 {"code":10009,"message":"failed to get the job log","details":"error for getting log of job 49a98fa7760ae365312dc1b0: {\"code\":10010,\"message\":\"object is not found\",\"details\":\"49a98fa7760ae365312dc1b0\"}"}`

Harbor version running:  v2.1.3

**Comment by steven-zou** [comment]
std logger does not support log getter as then you can not get the log text from the API.

**Comment by steven-zou** [comment]
For file and database logger, there is a sweeper that helps clean the logs with specified duration (current default is 1 day)

**Comment by steven-zou** [comment]
@kmmanto @ngalanis819 @duyanghao @sharkymcdongles @stephenwolfe1 

For the issue you reported, the reason is `std logger does not support log getter as then you can not get the log text from the API.`

As we support STD_LOGGER, FILE_LOGGER, and DB_LOGGER, only FILE_LOGGER and DB_LOGGER support log getter interface. For configurations, you can configure multiple loggers at the same time.

FILE_LOGGER and DB_LOGGER also support log sweepers with a pre-set duration, the outdated logs will be swept by the sweeper.

This is work as designed, no fix will be introduced.

**Comment by leo-lee-4231** [comment]
I am also experience the same problem.

It is really confused to me that one machine it can generate correct log file but another can't.

The harbor-version of both of them is 2.1.1

Here is the jobservice configuration:

```yml
---
#Protocol used to serve
protocol: "http"

#Server listening port
port: 8080

#Worker pool
worker_pool:
  #Worker concurrency
  workers: 10
  backend: "redis"
  #Additional config if use 'redis' backend
  redis_pool:
    #redis://[arbitrary_username:password@]ipaddress:port/database_index
    redis_url: redis://:xxx@external_ip:6379/2?idle_timeout_seconds=30
    namespace: "harbor_job_service_namespace"
    idle_timeout_second: 3600
#Loggers for the running job
job_loggers:
  - name: "STD_OUTPUT" # logger backend name, only support "FILE" and "STD_OUTPUT"
    level: "DEBUG" # INFO/DEBUG/WARNING/ERROR/FATAL
  - name: "FILE"
    level: "DEBUG"
    settings: # Customized settings of logger
      base_dir: "/var/log/jobs"
    sweeper:
      duration: 1 #days
      settings: # Customized settings of sweeper
        work_dir: "/var/log/jobs"

#Loggers for the job service
loggers:
  - name: "STD_OUTPUT" # Same with above
    level: "DEBUG"
```

Is there any filesystem config should be careful of writing job logs?
