### ISSUE TITLE
portal issue with charts of apiversion v2

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor#13024]
**Expected behavior and actual behavior:**
On `Projects < [project name] < Versions`, the chart details should be displayed, and the Download button should work.

However, some of the charts, seems only the ones with apiversion v2, would get "internal server error", and `HELM_CHART.NO_DETAIL` for details, and the Download button does not do a thing.

**Steps to reproduce the problem:**
The apiversion v2 charts are created using Helm 3.  push and helm fetch seems to work.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.1] 
- docker engine version: [18.9.8] client side: 19.03.10
- docker-compose version: [n/a] deployed using helm chart harbor-1.4.1 on k8s v1.12.7

**Additional context:**
Chart sample that has the portal issue (copied from the helm repo index retrieved from harbor using command `helm repo update`):
```
  cert-manager:
  - apiVersion: v2
    appVersion: 1.1.0.0.100010
    created: "2020-09-09T17:05:25.046322Z"
    dependencies:
    - name: certmgmt-agent
      repository: alias:build_destination
      version: ~0.0.62052
    - name: certmgmt-service
      repository: alias:build_destination
      version: ~0.0.62052
    description: Certificate Management
    digest: 137cb336a781785251c2483fbaf26ddb669effea6cf082a6c60001bf5e7d2f89
    name: cert-manager
    urls:
    - charts/cert-manager-1.1.100010.tgz
    version: 1.1.100010
```
Chart sample that does not have the issue:
```
  - apiVersion: v1
    appVersion: 1.0.92130
    created: "2020-06-23T21:12:49.253345Z"
    description: Certificate Management
    digest: 5c203d8ec9c47c0150c9adcd100eaf317685fdaac8faa62974dfba42fcbba9a1
    name: cert-manager
    urls:
    - charts/cert-manager-1.0.92130.tgz
    version: 1.0.92130
```
- **Harbor config files:**
Harbor installation command is similar to the following:
```
helm upgrade ht harbor/harbor --version $hchartv --namespace devops --force --dry-run --debug \
--set expose.ingress.hosts.core=harbor.${hdomain} \
--set expose.ingress.hosts.notary=notary.${hdomain} \
--set externalURL=https://harbor.${hdomain} \
--set persistence.persistentVolumeClaim.registry.existingClaim=ht-harbor-registry \
--set persistence.persistentVolumeClaim.chartmuseum.existingClaim=ht-harbor-chartmuseum \
--set persistence.persistentVolumeClaim.jobservice.existingClaim=ht-harbor-jobservice \
--set persistence.persistentVolumeClaim.database.existingClaim=database-data-ht-harbor-database-0 \
--set persistence.persistentVolumeClaim.redis.existingClaim=data-ht-harbor-redis-0
```
- **Log files:** You can get them by package the `/var/log/harbor/` .
Did not observe errors in the portal and chartmuseum pod logs.  Any particular place we should be looking?
