### ISSUE TITLE
Can I delete the Job log?

### ISSUE THREAD

**Issue by gouki777** [goharbor/harbor#13030]
What can we help you?
Can I delete the Job log？
I think this log is about copying -harbor-log. I'd like to clean up the history log.（one year ago）I wonder if it has any effect on Harbor。
<pre>
  jobservice:
    image: vmware/harbor-jobservice:v1.4.0
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs:z
</pre>

**Comment by steven-zou** [comment]
@gouki777 

As default, the sweeper of FILE logger in the jobservice has been configured and the duration is `1` day.

```
#Loggers for the running job
job_loggers:
  - name: "STD_OUTPUT" # logger backend name, only support "FILE" and "STD_OUTPUT"
    level: "INFO" # INFO/DEBUG/WARNING/ERROR/FATAL
  - name: "FILE"
    level: "INFO"
    settings: # Customized settings of logger
      base_dir: "/var/log/jobs"
    sweeper:
      duration: 1 #days
      settings: # Customized settings of sweeper
        work_dir: "/var/log/jobs"
```
