### ISSUE TITLE
Can't run harbor on an ipv6 only docker host

### ISSUE THREAD

**Issue by ruben-herold** [goharbor/harbor#13193]
**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.0-a3eca103
- docker engine version: 19.03.13
- docker-compose version: 1.27.4
- OS: Centos8 

I try to install harbor an an IPv6 only host, cause in our network no ipv4 anymore.
First I configured the centos system right:

 /etc/docker/daemon.json:

```
{
  "ipv6": true,
  "fixed-cidr-v6": "64:ff9b:99:0000:fc00::/70"
}

```

Add to /etc/sysctl.conf:

```
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding  = 1
net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-ip6tables=1
```

Do: 

```
echo  bridge > /etc/modules-load.d/docker.conf
echo br_netfilter > /etc/modules-load.d/docker.conf
firewall-cmd --permanent --add-rich-rule='rule family=ipv6 source address=64:ff9b:99::/64 masquerade'
systemctl enable docker
curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` \\ 
-o /usr/local bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
firewall-cmd --permanent --add-service=https
firewall-cmd --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-service=http
wget https://github.com/goharbor/harbor/releases/download/v2.1.0/harbor-online-installer-v2.1.0.tgz
tar -xzf harbor-online-installer-v2.1.0.tgz
```

after this I put the right ssl certificates in place. and reboot the system.

After reboot I created this harbor.yml:
```

hostname: harbor01.test.de

http:
  port: 80

https:
  port: 443
  certificate: /data/cert/full.pem
  private_key: /data/cert/full.pem


external_url: https://harbor.test.de:8433

harbor_admin_password: SecurePassword

database:
  password: SecurePassword2
  max_idle_conns: 50
  max_open_conns: 1000

data_volume: /data



clair:
  updaters_interval: 12

trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor


_version: 2.0.0




proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy



```

After this I do ./prepare!

Now I changed the network configuration in the generated docker-compose.yml:

```
....
networks:
  harbor:
    external: false
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 64:ff9b:99::/70
          gateway: 64:ff9b:99::1
  harbor-clair:
    external: false
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 64:ff9b:99:0000:0400::/70
          gateway: 64:ff9b:99:0000:0400::1
  harbor-chartmuseum:
    external: false
    enable_ipv6: true
    ipam:
      driver: default
      config: 
        - subnet: 64:ff9b:99:0000:0800::/70
          gateway: 64:ff9b:99:0000:0800::1


```
now run an 
./install.sh --with-clair --with-chartmuseum
After this I look for the generated bridge interfaces and do:

```

firewall-cmd --permanent --zone=trusted --change-interface=br-356a300796ce
firewall-cmd --permanent --zone=trusted --change-interface=br-7649bc1f5df1
firewall-cmd --permanent --zone=trusted --change-interface=br-f34c3fc3e914
firewall-cmd --complete-reload

```
No I can login into harbor and the harbor can for example reach our ipv6 only mailserver.
But two containers did not start:

clair-adapter
clair

In both logfiles  I found:

```
root@harbor01 harbor]# tail -n2 clair.log 
Sep 29 18:55:48 172.18.0.1 clair[971970]: Internal tls trust CA appending is Done.
Sep 29 18:55:48 172.18.0.1 clair[971970]: {"Event":"pgsql: database connection string is not a valid URL","Level":"fatal","Location":"main.go:97","Time":"2020-09-29 16:55:48.801475"}

```
and

```
[root@harbor01 harbor]# tail -n2 clair-adapter.log 
Sep 29 18:55:53 172.18.0.1 clair-adapter[971970]: Internal tls trust CA appending is Done.
Sep 29 18:55:53 172.18.0.1 clair-adapter[971970]: {"level":"fatal","msg":"Error: getting config: invalid clair database url postgresql://postgres:2Kimpler96?!@postgresql:5432/postgres?sslmode=disable","time":"2020-09-29T16:55:53Z"}

```

Can you help figuring out what's going wrong?
