### ISSUE TITLE
failed to fetch image: FetchImages error when collect tags for repos

### ISSUE THREAD

**Issue by zming** [goharbor/harbor#13233]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Connecting to a harbor-based docker registry, will allow replication of any namespace images.
![image](https://user-images.githubusercontent.com/20045153/95652504-0f65f380-0b24-11eb-83f2-82b8aaad88e3.png)

**Steps to reproduce the problem:**
Connect Harbor registry as Docker Registry.
Create replication of gitlab registry.
Run replication.

**Versions:**
Please specify the versions of following systems.

- harbor version: [v1.10.3]
- docker engine version: [19.03.13]
- docker-compose version: [1.18.0]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
core.log
```Oct 10 16:56:59 172.20.0.1 core[1754]: 2020-10-10T08:56:59Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/edsp-demo-dubbo-app' error: http error: code 504, message <html>#015
Oct 10 16:56:59 172.20.0.1 core[1754]: <head><title>504 Gateway Time-out</title></head>#015
Oct 10 16:56:59 172.20.0.1 core[1754]: <body>#015
Oct 10 16:56:59 172.20.0.1 core[1754]: <center><h1>504 Gateway Time-out</h1></center>#015
Oct 10 16:56:59 172.20.0.1 core[1754]: <hr><center>nginx</center>#015
Oct 10 16:56:59 172.20.0.1 core[1754]: </body>#015
Oct 10 16:56:59 172.20.0.1 core[1754]: </html>#015

Oct 10 18:39:25 172.20.0.1 core[1754]: 2020-10-10T10:39:25Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/edsp-alertmanager-bot' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020-10-10T10:39:26Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/centos' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020-10-10T10:39:26Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/edsp-pay' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020-10-10T10:39:26Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/edsp-openapi-server-dev' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020-10-10T10:39:26Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/edsp-alert-adm' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020-10-10T10:39:26Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/edsp-cd' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020-10-10T10:39:26Z [ERROR] [/common/utils/passports.go:109]: List tags for repo 'edsp/csb-iface' error: http error: code 500, message {"code":500,"message":"Internal Server Error"}
Oct 10 18:39:26 172.20.0.1 core[1754]: 2020/10/10 10:39:26.770 #033[1;44m[D]#033[0m [server.go:2774]  |   10.18.88.212|#033[97;42m 200 #033[0m|   8.913842ms|   match|#033[97;44m GET     #033[0m /api/replication/executions   r:/api/replication/executions
Oct 10 18:39:36 172.20.0.1 core[1754]: 2020/10/10 10:39:36.767 #033[1;44m[D]#033[0m [server.go:2774]  |   10.18.88.212|#033[97;42m 200 #033[0m|   6.004242ms|   match|#033[97;44m GET     #033[0m /api/replication/executions   r:/api/replication/executions
Oct 10 18:39:46 172.20.0.1 core[1754]: 2020/10/10 10:39:46.775 #033[1;44m[D]#033[0m [server.go:2774]  |   10.18.88.212|#033[97;42m 200 #033[0m|   8.536536ms|   match|#033[97;44m GET     #033[0m /api/replication/executions   r:/api/replication/executions
Oct 10 18:39:50 172.20.0.1 core[1754]: 2020/10/10 10:39:50.051 #033[1;44m[D]#033[0m [server.go:2774]  |      127.0.0.1|#033[97;42m 200 #033[0m|   4.818259ms|   match|#033[97;44m GET     #033[0m /api/ping   r:/api/ping
Oct 10 18:39:56 172.20.0.1 core[1754]: 2020/10/10 10:39:56.768 #033[1;44m[D]#033[0m [server.go:2774]  |   10.18.88.212|#033[97;42m 200 #033[0m|   5.022163ms|   match|#033[97;44m GET     #033[0m /api/replication/executions   r:/api/replication/executions
Oct 10 18:40:03 172.20.0.1 core[1754]: 2020-10-10T10:40:03Z [ERROR] [/replication/operation/controller.go:108]: the execution 434 failed: failed to fetch image: FetchImages error when collect tags for repos```

**Comment by zming** [comment]
I have tried the following methods and it doesn't work
1. change postgresql max_connections from 100 to 999，and restart db
2. add nginx  parameters set timeout 900, and restart nginx

**Comment by giladk1221** [comment]
+1

**Comment by bitsf** [comment]
which harbor db did you patched? local or remote harbor?
how many repos and tags?

**Comment by bansalrajat** [comment]
Facing the same issue.Any update on this?

**Comment by sober-wang** [comment]
hi, guys.
I just met the problem.
I configerution docker-compose.yml registry. it can running.
```yaml
  registry:
    image: goharbor/registry-photon:v2.7.1-patch-2819-v1.8.3
    container_name: registry
    restart: always
    # we should add ports at the regitstry
    ports:
      - 5000:5000
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/harbor-1.8.3-data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - /etc/hosts:/etc/hosts
      - type: bind
        source: /data/harbor-1.8.3-data/secret/registry/root.crt
        target: /etc/registry/root.crt
    networks:
      - harbor
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
```

I holp the answer can help you. : )
