### ISSUE TITLE
deployment of Harbor to OpenShift via helm fails - $HOME directory is not available due to dynamic users

### ISSUE THREAD

**Issue by andrejs-sisojevs** [goharbor/harbor#13287]
# Short description
Deployment of Harbor fails, because `/make/photon/common/install_cert.sh` script refers `$HOME` directory, which (`$HOME` variable) is unavailable for OpenShift dynamic users. Failing [script part](https://github.com/goharbor/harbor/blob/c491c4f513475c610fa575f891f82516b618d4af/make/photon/common/install_cert.sh#L10):
```
if [ ! -f ~/ca-bundle.crt.original ]; then
    cp /etc/pki/tls/certs/ca-bundle.crt ~/ca-bundle.crt.original
fi

cp ~/ca-bundle.crt.original /etc/pki/tls/certs/ca-bundle.crt
``` 

After Harbor Helm deployment multiple pods fail similarly:
```
$ kubectl logs harbor-harbor-core-5bf889f555-n44s2
cp: //ca-bundle.crt.original: Permission denied
```

Related issue: https://github.com/goharbor/harbor-helm/issues/560
Related RedHat article, regarding unavailability of `$HOME`: https://access.redhat.com/articles/4859371

# Potential fix

Instead of `~` use either `$(dirname "$0")` or `/tmp` or other directory without relying on `$HOME` variable.

```
ORIGINAL_LOCATION=$(dirname "$0")
if [ ! -f $ORIGINAL_LOCATION/ca-bundle.crt.original ]; then
    cp /etc/pki/tls/certs/ca-bundle.crt $ORIGINAL_LOCATION/ca-bundle.crt.original
fi

cp $ORIGINAL_LOCATION/ca-bundle.crt.original /etc/pki/tls/certs/ca-bundle.crt
``` 

Notice: according to [search results](https://github.com/goharbor/harbor/search?l=Shell&q=install_cert.sh) script `install_cert.sh` is used in 8 Docker entrypoints:
| Calling Script  | Call command |
| --- | --- |
| make/photon/trivy-adapter/entrypoint.sh  | /home/scanner/install_cert.sh  |
| make/photon/clair-adapter/entrypoint.sh  | /home/clair-adapter/install_cert.sh  |
| make/photon/core/entrypoint.sh  | /harbor/install_cert.sh  |
| make/photon/jobservice/entrypoint.sh  | /harbor/install_cert.sh  |
| make/photon/registryctl/start.sh  | /home/harbor/install_cert.sh  |
| make/photon/registry/entrypoint.sh  | /home/harbor/install_cert.sh  |
| make/photon/chartserver/docker-entrypoint.sh  | /home/chart/install_cert.sh  |
| make/photon/clair/docker-entrypoint.sh  | /home/clair/install_cert.sh  |

# Other details
OpenShift version: v4.4.6

<details><summary>Installation commands</summary>
<p>

```
helm repo add harbor https://helm.goharbor.io
helm repo update
helm --debug \
    --kube-apiserver $CLUSTER_API_HTTPS \
    install \
        --wait \
        --timeout 60s \
        -f $SCRIPT_DIR/install-params-override.yaml \
        --namespace harbor \
        harbor \
        harbor/harbor
```

</p>
</details>

<details><summary>Helm values file (`install-params-override.yaml`)</summary>
<p>

```yaml
expose:
  type: clusterIP
  tls:
    certSource: secret
    secret:
      secretName: custom-ssl-certificate
  clusterIP:
    name: harbor
externalURL: https://harbor.apps.mycluster.example.net
harborAdminPassword: "Qwerty12345"

nginx:
  serviceAccountName: provisioner-of-harbor
portal:
  serviceAccountName: provisioner-of-harbor
core:
  serviceAccountName: provisioner-of-harbor
jobservice:
  serviceAccountName: provisioner-of-harbor
registry:
  serviceAccountName: provisioner-of-harbor
chartmuseum:
  serviceAccountName: provisioner-of-harbor
clair:
  serviceAccountName: provisioner-of-harbor
trivy:
  serviceAccountName: provisioner-of-harbor
notary:
  server:
    serviceAccountName: provisioner-of-harbor
  signer:
    serviceAccountName: provisioner-of-harbor
database:
  internal:
    serviceAccountName: provisioner-of-harbor-db
redis:
  internal:
    serviceAccountName: provisioner-of-harbor
```

</p>
</details>

Dedicated OpenShift `SecurityContextConstraints` are copies of default `restricted` SCC, with following distinctions: 
* modified `fsGroup` and `runAsUser` settings
* [SETUID,SETGID] are added to pods, instead of being droped

<details><summary>ServiceAcounts and SecurityContextConstraints</summary>
<p>

```yaml
#!/bin/bash -xe

. "$(dirname "$0")/../_common.sh"
. "$(dirname "$0")/../_secret-data.sh"

oc-login admin

NAMESPACE="harbor"
SERVICE_ACCOUNT_NAME="provisioner-of-$NAMESPACE"
SERVICE_ACCOUNT_NAME_DB="provisioner-of-$NAMESPACE-db"
SCC_NAME="scc-for-provisioner-of-$NAMESPACE"
SCC_NAME_DB="scc-for-provisioner-of-$NAMESPACE-db"

# ==============================================================================
# == cleanup
kubectl delete --ignore-not-found secret custom-ssl-certificate -n $NAMESPACE
kubectl delete --ignore-not-found scc $SCC_NAME
kubectl delete --ignore-not-found scc $SCC_NAME_DB
kubectl delete --ignore-not-found serviceaccount $SERVICE_ACCOUNT_NAME  -n $NAMESPACE
kubectl delete --ignore-not-found serviceaccount $SERVICE_ACCOUNT_NAME_DB  -n $NAMESPACE
kubectl delete --ignore-not-found namespace $NAMESPACE

# ==============================================================================
# == create

kubectl apply -f - <<END
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c24,c14
    openshift.io/sa.scc.supplemental-groups: 999/20000
    openshift.io/sa.scc.uid-range: 999/20000
  name: $NAMESPACE
  selfLink: /apis/project.openshift.io/v1/projects/$NAMESPACE
spec:
  finalizers:
  - kubernetes
END

kubectl apply -f - <<END
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: $SCC_NAME

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
priority: null
readOnlyRootFilesystem: false
fsGroup:
  type: MustRunAs
  ranges:
  - min: 999
    max: 999
  - min: 999
    max: 10000
runAsUser:
  type: MustRunAs
  ranges:
  - min: 10000
    max: 10000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
groups:
- system:authenticated
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
allowedCapabilities:
- SETUID
- SETGID
defaultAddCapabilities:
- SETUID
- SETGID
requiredDropCapabilities:
- KILL
- MKNOD
END

kubectl apply -f - <<END
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: $SCC_NAME_DB

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
priority: null
readOnlyRootFilesystem: false
fsGroup:
  type: MustRunAs
  ranges:
  - min: 999
    max: 999
  - min: 999
    max: 10000
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
groups:
- system:authenticated
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
allowedCapabilities:
- SETUID
- SETGID
defaultAddCapabilities:
- SETUID
- SETGID
requiredDropCapabilities:
- KILL
- MKNOD
END

oc create serviceaccount $SERVICE_ACCOUNT_NAME -n $NAMESPACE
oc create serviceaccount $SERVICE_ACCOUNT_NAME_DB -n $NAMESPACE
oc adm policy add-scc-to-user $SCC_NAME system:serviceaccount:$NAMESPACE:$SERVICE_ACCOUNT_NAME
oc adm policy add-scc-to-user $SCC_NAME_DB system:serviceaccount:$NAMESPACE:$SERVICE_ACCOUNT_NAME_DB

kubectl \
    get secret custom-ssl-certificate \
    -n openshift-ingress \
    -o json \
    | jq 'del( .metadata.namespace
             , .metadata.resourceVersion
             , .metadata.uid
             , .metadata.creationTimestamp
             , .metadata.selfLink
             )' \
    | kubectl apply -n $NAMESPACE -f -

```

</p>
</details>
