### ISSUE TITLE
Error response from daemon: Get https://harbor.x.com/v2/: x509: certificate is valid for ingress.local, not harbor.x.com

### ISSUE THREAD

**Issue by sharkymcdongles** [goharbor/harbor#13318]
I deployed harbor from goharbor chart and am getting this error when I try to do docker login. 

`Error response from daemon: Get https://harbor.x.com/v2/: x509: certificate is valid for ingress.local, not harbor.x.com`

My coworkers are able to use docker login fine and don't see this error. Any idea why this is?

I am using harbor-1.5.0 2.1.0 from goharbor repo:

Values:
```
chartmuseum:
  absoluteUrl: false
  enabled: true
  image:
    repository: goharbor/chartmuseum-photon
    tag: v2.1.0
  nodeSelector:
    agentpool: stateful
  replicas: 1
clair:
  adapter:
    image:
      repository: goharbor/clair-adapter-photon
      tag: v2.1.0
  clair:
    image:
      repository: goharbor/clair-photon
      tag: v2.1.0
  enabled: true
  nodeSelector:
    agentpool: stateful
  replicas: 1
  updatersInterval: 12
core:
  image:
    repository: goharbor/harbor-core
    tag: v2.1.0
  nodeSelector:
    agentpool: stateful
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 1024Mi
  startupProbe:
    initialDelaySeconds: 10
database:
  internal:
    image:
      repository: goharbor/harbor-db
      tag: v2.1.0
    nodeSelector:
      agentpool: stateful
    password: censored
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    sslmode: disable
  maxIdleConns: 50
  maxOpenConns: 1000
  type: internal
expose:
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
  ingress:
    annotations:
      ingress.kubernetes.io/proxy-body-size: 10000m
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.allow-http: "false"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    controller: default
    hosts:
      core: harbor.x.com
  tls:
    certSource: secret
    enabled: true
    secret:
      notarySecretName: harbor.x.com
      secretName: harbor.x.com
  type: ingress
externalURL: https://harbor.x.com
harborAdminPassword: censored
imagePullPolicy: IfNotPresent
internalTLS:
  certSource: auto
  chartmuseum:
    crt: ""
    key: ""
    secretName: ""
  clair:
    crt: ""
    key: ""
    secretName: ""
  core:
    crt: ""
    key: ""
    secretName: ""
  enabled: false
  jobservice:
    crt: ""
    key: ""
    secretName: ""
  portal:
    crt: ""
    key: ""
    secretName: ""
  registry:
    crt: ""
    key: ""
    secretName: ""
  trivy:
    crt: ""
    key: ""
    secretName: ""
  trustCa: ""
jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.1.0
  jobLogger: stdout
  maxJobWorkers: 10
  replicas: 1
logLevel: debug
notary:
  affinity: {}
  enabled: false
  nodeSelector: {}
  podAnnotations: {}
  secretName: ""
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v2.1.0
    replicas: 1
    serviceAccountName: ""
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v2.1.0
    replicas: 1
    serviceAccountName: ""
  tolerations: []
persistence:
  enabled: true
  imageChartStorage:
    disableredirect: false
    gcs:
      bucket: harbor
      chunksize: "5242880"
      encodedkey: x
      rootdirectory: /
    type: gcs
  persistentVolumeClaim:
    chartmuseum:
      accessMode: ReadWriteOnce
      existingClaim: '-'
      size: 5Gi
      storageClass: ""
      subPath: ""
    database:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 32Gi
      storageClass: fast
      subPath: ""
    jobservice:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 8Gi
      storageClass: fast
      subPath: ""
    redis:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 32Gi
      storageClass: fast
      subPath: ""
    registry:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 5Gi
      storageClass: '-'
      subPath: ""
    trivy:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 5Gi
      storageClass: fast
      subPath: ""
  resourcePolicy: keep
portal:
  image:
    repository: goharbor/harbor-portal
    tag: v2.1.0
  nodeSelector:
    agentpool: stateful
  replicas: 1
proxy:
  components:
  - core
  - jobservice
  - clair
  - trivy
  httpProxy: null
  httpsProxy: null
  noProxy: 127.0.0.1,localhost,.local,.internal
redis:
  internal:
    image:
      repository: goharbor/redis-photon
      tag: v2.1.0
    nodeSelector:
      agentpool: stateful
    serviceAccountName: ""
  type: internal
registry:
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.1.0
  credentials:
    htpasswd: user_harbor:censored
    password: censored
    username: user_harbor
  middleware:
    enabled: false
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.1.0
  relativeurls: false
  replicas: 1
secretKey: pass
trivy:
  affinity: {}
  debugMode: false
  enabled: true
  ignoreUnfixed: false
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.1.0
  insecure: false
  nodeSelector: {}
  podAnnotations: {}
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  skipUpdate: false
  tolerations: []
  vulnType: os,library
updateStrategy:
  type: RollingUpdate
```
