### ISSUE TITLE
[trivy] Failed to download vulnerability DB: API rate limit exceeded 

### ISSUE THREAD

**Issue by h8h** [goharbor/harbor#13354]
What can we help you?
```

---------- Logs of report 739b5b7c-8b23-41e1-a8f2-c58486b593df ----------
2020-10-23T13:45:22Z [INFO] [/pkg/scan/job.go:325]: registration:
2020-10-23T13:45:22Z [INFO] [/pkg/scan/job.go:336]: {
  "uuid": "47ffc762-1518-11eb-b1e6-0242ac1a0009",
  "name": "Trivy",
  "description": "The Trivy scanner adapter",
  "url": "http://trivy-adapter:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.9.2",
  "create_time": "2020-10-23T10:12:39.627599Z",
  "update_time": "2020-10-23T10:12:39.627601Z"
}
2020-10-23T13:45:22Z [INFO] [/pkg/scan/job.go:325]: scanRequest:
2020-10-23T13:45:22Z [INFO] [/pkg/scan/job.go:336]: {
  "registry": {
    "url": "http://core:8080",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 1,
    "repository": "library/debian",
    "tag": "",
    "digest": "sha256:f4f8457fd057d0744bbd01d994e9ad1229f0bee5d063f1ab7a8568ef18c8ddf8",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2020-10-23T13:45:22Z [INFO] [/pkg/scan/job.go:156]: Report mime types: [application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0]
2020-10-23T13:45:22Z [INFO] [/pkg/scan/job.go:202]: Get report for mime type: application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0
2020-10-23T13:45:24Z [ERROR] [/pkg/scan/job.go:284]: check scan report with mime type application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0: running trivy wrapper: running trivy: exit status 1: 2020-10-23T13:45:22.934Z    [34mINFO[0m    Need to update DB
2020-10-23T13:45:22.934Z    [34mINFO[0m    Downloading DB...
2020-10-23T13:45:23.055Z    [31mFATAL[0m    failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 50m29s]
: general response handler: unexpected status code: 500, expected: 200
```

I've uploaded about 20 images to harbor and then the scans failed.

I know what this issue is about.

But does every trivy scan really needs to download the DB?

I know that there is an option to skip the download, but I guess that I have to do it manually.

Is there an option to download the DB frequently (every day, every 12h)?

Thank you.

**Comment by lishinho** [comment]
It is really bad

**Comment by heww** [comment]
@h8h and @lishinho  you can set a GitHub access token for the Trivy scanner to increase the rate limit to 5000 requests per hour. For more information see: https://goharbor.io/docs/2.1.0/install-config/configure-yml-file/

![image](https://user-images.githubusercontent.com/5634205/97824065-e20cff80-1cf5-11eb-9638-d660d7604bad.png)

**Comment by h8h** [comment]
Algthough this is the solution, but if every project is so wasteful with GitHub resources, the server will be down soon.

Sorry IMHO this should not be the solution. The solution should be a pull on a regular time basis and not by every image push.

**Comment by heww** [comment]
Hi, @h8h I think that the Trivy adapter will update the vulnerability database from GitHub every 12hours, not every scanning. Is this right @danielpacak ?

**Comment by danielpacak** [comment]
Yes @heww Normally Trivy is caching the DB file downloaded from GitHub and reuses it for subsequent scans.

**Comment by h8h** [comment]
It seems that it not get cached

```
2020-10-23T13:45:24Z [ERROR] [/pkg/scan/job.go:284]: check scan report with mime type application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0: running trivy wrapper: running trivy: exit status 1: 2020-10-23T13:45:22.934Z    �[34mINFO�[0m    Need to update DB
2020-10-23T13:45:22.934Z    �[34mINFO�[0m    Downloading DB...
2020-10-23T13:45:23.055Z    �[31mFATAL�[0m    failed to download vulnerability DB:
```

I pushed serval images and than while scanning "downloading..." failed without redeploying the harbor docker stack.

With caching I guess I never ran into "403 API rate limit exceeded " or @danielpacak ?

**Comment by danielpacak** [comment]
👋 @h8h Indeed normally, if the persistence volume used by the trivy adapter is not delete for some reasons you should not bump into GitHub rate limit issues. As @heww mentioned and I confirmed in my previous comment, trivy executable used by the adapter service detects whether the Trivy DB file is cached on a local file system and is up to date. It only tries to download the Trivy DB file from GitHub if it's not present or is outdated.

That said, I'm wondering if:
- [ ] You ever managed to download the Trivy DB file without getting the rate limit error?
- [ ] Is there any other app in your cluster that might reach out to GitHub APIs?
- [ ] Is there any process or configuration that might delete the Trivy DB from the PV created by the Trivy adapter service
- [ ] Could you provide more details about versions of Harbor and Trivy that you're using and the installation mode (Docker compose vs Helm chart?) You can find the version of the Trivy adapter under the Interrogation Service menu in the Trivy scanner details.

**Comment by danielpacak** [comment]
BTW, I was testing another thing and here's another confirmation that Trivy does skip the DB update with its default config. Search for **DB update was skipped because DB is the latest** in the following log output of the scanner adapter:

```
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"level":"debug","msg":"Updating status for scan job","new_status":"Pending","scan_job_id":"9f0b6d18ef8c4d722d46c1d2","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"expire":3600,"level":"debug","msg":"Updating scan job","redis_key":"harbor.scanner.trivy:store:scan-job:9f0b6d18ef8c4d722d46c1d2","scan_job_id":"9f0b6d18ef8c4d722d46c1d2","scan_job_status":"Pending","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"image_ref":"core:8080/library/nginx@sha256:c0978d1f3e5ef8a936537cf67bb155a581f56f93bbf8a345a650720e14d321bb","level":"debug","msg":"Started scanning","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"level":"debug","msg":"Saving scan report to tmp file","path":"/home/scanner/.cache/reports/scan_report_983178097.json","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"exit_code":0,"image_ref":"core:8080/library/nginx@sha256:c0978d1f3e5ef8a936537cf67bb155a581f56f93bbf8a345a650720e14d321bb","level":"debug","msg":"Running trivy finished","std_out":"2020-11-29T10:45:46.030Z\t\u001b[35mDEBUG\u001b[0m\tSeverities: HIGH,CRITICAL\n2020-11-29T10:45:46.038Z\t\u001b[35mDEBUG\u001b[0m\tcache dir:  /home/scanner/.cache/trivy\n2020-11-29T10:45:46.039Z\t\u001b[35mDEBUG\u001b[0m\tDB update was skipped because DB is the latest\n2020-11-29T10:45:46.039Z\t\u001b[35mDEBUG\u001b[0m\tDB Schema: 1, Type: 1, UpdatedAt: 2020-11-29 00:33:54.657934459 +0000 UTC, NextUpdate: 2020-11-29 12:33:54.657934059 +0000 UTC, DownloadedAt: 2020-11-29 10:24:22.54855719 +0000 UTC\n2020-11-29T10:45:46.090Z\t\u001b[35mDEBUG\u001b[0m\tVulnerability type:  [os]\n2020-11-29T10:45:46.122Z\t\u001b[35mDEBUG\u001b[0m\tArtifact ID: sha256:2562b6bef9769b637d47ec31284ac0f1a7facef498ab97753623b13c502cddce\n2020-11-29T10:45:46.122Z\t\u001b[35mDEBUG\u001b[0m\tBlob IDs: [sha256:f5600c6330da7bb112776ba067a32a9c20842d6ecc8ee3289f1a713b644092f8 sha256:546ff42febcb6104992d84b2d95beaa699f2952ede6bc4bdb996f02dda30f680 sha256:cf91f5e8589e08c68094796ab970a77ec5f49235dce040d706f2c3f492609961 sha256:4f5295ed788f7de301eb3e25bf72fcdcb5b731dab528495cfab6898bcdda3673 sha256:b56dcfc4eee5dc5435639d9603fbbf40474d282bec27edbb2796820039208dde]\n2020-11-29T10:45:46.122Z\t\u001b[34mINFO\u001b[0m\tDetecting Debian vulnerabilities...\n2020-11-29T10:45:46.122Z\t\u001b[35mDEBUG\u001b[0m\tdebian: os version: 10\n2020-11-29T10:45:46.122Z\t\u001b[35mDEBUG\u001b[0m\tdebian: the number of packages: 135\n","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"level":"debug","msg":"Removing scan report tmp file","path":"/home/scanner/.cache/reports/scan_report_983178097.json","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"level":"debug","msg":"Updating reports for scan job","scan_job_id":"9f0b6d18ef8c4d722d46c1d2","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"expire":3600,"level":"debug","msg":"Updating scan job","redis_key":"harbor.scanner.trivy:store:scan-job:9f0b6d18ef8c4d722d46c1d2","scan_job_id":"9f0b6d18ef8c4d722d46c1d2","scan_job_status":"Pending","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"level":"debug","msg":"Updating status for scan job","new_status":"Finished","scan_job_id":"9f0b6d18ef8c4d722d46c1d2","time":"2020-11-29T10:45:46Z"}
Nov 29 10:45:46 172.20.0.1 trivy-adapter[1686]: {"expire":3600,"level":"debug","msg":"Updating scan job","redis_key":"harbor.scanner.trivy:store:scan-job:9f0b6d18ef8c4d722d46c1d2","scan_job_id":"9f0b6d18ef8c4d722d46c1d2","scan_job_status":"Finished","time":"2020-11-29T10:45:46Z"}
```

**Comment by h8h** [comment]
I think I'm going to close this issue.

Today I've tried it with the current version 2.1.1 and it seems to work (scanning more than 20 images) without getting into the  "API rate limit exceeded" error.

Thank you

**Comment by Lyrwon** [comment]
Hi, i reopen this issue

I have the same problems with the actual version:
```

2021-02-02T07:12:40Z [ERROR] [/pkg/scan/job.go:284]: check scan report with mime type application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0: running trivy wrapper: running trivy: exit status 1: 2021-02-02T07:12:30.142Z	[34mINFO[0m	Need to update DB
2021-02-02T07:12:30.143Z	[34mINFO[0m	Downloading DB...
2021-02-02T07:12:40.150Z	[31mFATAL[0m	failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get https://api.github.com/repos/aquasecurity/trivy-db/releases: dial tcp: lookup api.github.com on 127.0.0.11:53: read udp 127.0.0.1:38662->127.0.0.11:53: i/o timeout
: general response handler: unexpected status code: 500, expected: 200
```

I have started harbor on an Ubunut 18.04 VMBox and an Ubuntu 20.04 VMBox, both running on Windows 10.
I have tried the same config on a nativ Ubuntu 18.04 but there is the same problem.

I hope anyone of you can help me

```
version: '2.3'
services:
  log:
    image: goharbor/harbor-log:v2.1.3
    container_name: harbor-log
    restart: always
    dns_search: .
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/var/log/harbor/:/var/log/docker/:z
      - type: bind
        source: /opt/docker/harbor/common/config/log/logrotate.conf
        target: /etc/logrotate.d/logrotate.conf
      - type: bind
        source: /opt/docker/harbor/common/config/log/rsyslog_docker.conf
        target: /etc/rsyslog.d/rsyslog_docker.conf
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor
  registry:
    image: goharbor/registry-photon:v2.1.3
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/data/registry:/storage:z
      - /opt/docker/harbor/common/config/registry/:/etc/registry/:z
      - type: bind
        source: /opt/docker/harbor/data/secret/registry/root.crt
        target: /etc/registry/root.crt
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
      - harbor-clair
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  registryctl:
    image: goharbor/harbor-registryctl:v2.1.3
    container_name: registryctl
    env_file:
      - /opt/docker/harbor/common/config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/data/registry:/storage:z
      - /opt/docker/harbor/common/config/registry/:/etc/registry/:z
      - type: bind
        source: /opt/docker/harbor/common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registryctl"
  postgresql:
    image: goharbor/harbor-db:v2.1.3
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
      harbor-clair:
        aliases:
          - harbor-db
    dns_search: .
    env_file:
      - /opt/docker/harbor/common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "postgresql"
  core:
    image: goharbor/harbor-core:v2.1.3
    container_name: harbor-core
    env_file:
      - /opt/docker/harbor/common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/data/ca_download/:/etc/core/ca/:z
      - /opt/docker/harbor/data/:/data/:z
      - /opt/docker/harbor/common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: /opt/docker/harbor/common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /opt/docker/harbor/data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /opt/docker/harbor/data/secret/keys/secretkey
        target: /etc/core/key
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      harbor:
      harbor-clair:
        aliases:
          - harbor-core
    dns_search: .
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "core"
  portal:
    image: goharbor/harbor-portal:v2.1.3
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - type: bind
        source: /opt/docker/harbor/common/config/portal/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - harbor
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "portal"

  jobservice:
    image: goharbor/harbor-jobservice:v2.1.3
    container_name: harbor-jobservice
    env_file:
      - /opt/docker/harbor/common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/data/job_logs:/var/log/jobs:z
      - type: bind
        source: /opt/docker/harbor/common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
      - harbor-clair
    dns_search: .
    depends_on:
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  redis:
    image: goharbor/redis-photon:v2.1.3
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /opt/docker/harbor/data/redis:/var/lib/redis
    networks:
      harbor:
      harbor-clair:
        aliases:
          - redis
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "redis"
  proxy:
    image: goharbor/nginx-photon:v2.1.3
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - /opt/docker/harbor/common/config/nginx:/etc/nginx:z
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    dns_search: .
    ports:
      - 80:8080
    depends_on:
      - registry
      - core
      - portal
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: goharbor/clair-photon:v2.1.3
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cpu_quota: 50000
    dns_search: .
    depends_on:
      - log
      - postgresql
    volumes:
      - type: bind
        source: /opt/docker/harbor/common/config/clair/config.yaml
        target: /etc/clair/config.yaml
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
    env_file:
      /opt/docker/harbor/common/config/clair/clair_env
  clair-adapter:
    networks:
      - harbor-clair
    container_name: clair-adapter
    image: goharbor/clair-adapter-photon:v2.1.3
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cpu_quota: 50000
    dns_search: .
    depends_on:
      - clair
      - redis
    volumes:
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair-adapter"
    env_file:
      /opt/docker/harbor/common/config/clair-adapter/env
  trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:v2.1.3
    restart: always
    cap_drop:
      - ALL
    dns_search: .
    depends_on:
      - log
      - redis
    networks:
      - harbor
    volumes:
      - type: bind
        source: /opt/docker/harbor/data/trivy-adapter/trivy
        target: /home/scanner/.cache/trivy
      - type: bind
        source: /opt/docker/harbor/data/trivy-adapter/reports
        target: /home/scanner/.cache/reports
      - type: bind
        source: /opt/docker/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "trivy-adapter"
    env_file:
      /opt/docker/harbor/common/config/trivy-adapter/env
networks:
  harbor:
    external: false
  harbor-clair:
    external: false
```
