### ISSUE TITLE
Docker-Swarm cannot read image-digest from a "proxy cache"-project

### ISSUE THREAD

**Issue by ChristianCiach** [goharbor/harbor#13385]
We are currently trying out the new "proxy cache" feature of Harbor to feed images to our Docker-Swarm cluster.

Docker Swarm is used to run the same set of images on multiple nodes. To archive that in a safe manner, the command `docker stack deploy ...` first tries to retrieve the exact image-digest of the images and then instructs all the nodes in the cluster to pull this exact digest (instead of the tag). This ensures that all nodes pull the exact same image from the registry. This is done by docker-swarm to avoid a race-condition that could occur if an image-tag (like `latest`) were replaced on the registry while some nodes already pulled the previous image, so that the rest of the nodes would then pull the newer image, resulting in different nodes using different image versions.

Unfortunately, when using a proxy-cache project with Harbor, docker-swarm cannot retrieve the image-digest of the requested image-tag and issues a warning:

Command:
```
$ docker stack deploy -c docker-compose.yaml --with-registry-auth test
```

Resulting output:
```
Updating service test_database (id: rzdymwoenht1e4kg3hfkatd5p)
image ems-registry.shnetz/proxy/shnetz/mariadb:latest could not be accessed on a registry to record
its digest. Each node will access ems-registry.shnetz/proxy/shnetz/mariadb:latest independently,
possibly leading to different nodes running different versions of the image.
```

Probably not really important, but this is the docker-compose.yaml that was used for this example:
```yaml
version: '3.8'

services:
  database:
    image: 'ems-registry.shnetz/proxy/shnetz/mariadb:latest'
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
    deploy:
      replicas: 1
```

Of course, this race condition should be avoided. As a proposed solution, Harbor should be able to correctly respond with the image digest when being asked for the digest of an image-tag. Unfortunately, I don't know which API-endpoint the docker-daemon is using for these requests. Anyway, Harbor should *always* forward these digest-request to the upstream registry to ensure the usage of the latest image versions.

This issue only appears when using a "proxy cache" project. When using a regular project, everything works fine.

**Versions:**

- harbor version: 2.1.1
- docker engine version: 19.03.12
