### ISSUE TITLE
Harbor begin HTTPS reverse proxy (x509: certificate is valid for ... not ...)

### ISSUE THREAD

**Issue by Tchoupinax** [goharbor/harbor#13438]
Hello,

_I met this issue and i need help to solve the solution and have a better understanding about the architecture. Morever, it would be nice to have a reference issue with the solution._

UI and service works well but I have the following issue when I pull an image: 

> Error response from daemon: Get https://harbor.myDomain.com/v2/: x509: certificate is valid for 826f898e38816b48e9d68b01e49fc05b.526849e13b633cb69a05d233f7d3f5e6.traefik.default, not harbor.myDomain.com

I spend a lot of time to solve this issue but my issue is not resolved yet.

I installed harbor on kubernetes using the [helm chart](https://github.com/goharbor/harbor-helm) and I use Traefik v2 as ingress controller.

I created an ingressRoute object to declare a route to join harbor. The declaration is the following file:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-tls
  namespace: harbor
  annotations:
    prometheus.io/scrape: 'true'
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`harbor.myDomain.com`)
    kind: Rule
    services:
    - name: harbor-harbor-portal
      namespace: harbor
      port: 80
  - match: Host(`harbor.harbor.myDomain.com`) && PathPrefix(`/api/`, `/service/`, `/v2/`, `/chartrepo/`, `/c/`)
    kind: Rule
    services:
    - name: harbor-harbor-core
      namespace: harbor
      port: 80
  tls:
    certResolver: le # Let's encrypt
```
I read a lot of issues and link to find the solution but I did not succeed. The [most loved issue](https://github.com/goharbor/harbor/issues/3114#issuecomment-394139225) talks (and many others) to remove some header from the nginx conf.

The expected architecture is to have HTTPS until Traefik and HTTP behind (with or without nginx).

## questions

- Should Traefik hits the nginx deployed by harbor or directly hits the portal and the core (like the previous file makes)?
_I tried to hits the `harbor` service (which is nginx) directly and I have the same result, UI works but error when pulling_

## resources

- https://www.claudiokuenzler.com/blog/958/running-harbor-registry-behind-reverse-proxy-solve-docker-push-errors
- https://medium.com/@jodywan/cloud-native-devops-08-harbor-2-0-with-traefik-2-0-reverse-proxy-5acbba95534a
- https://github.com/goharbor/harbor/issues/13318
- https://github.com/goharbor/harbor/issues/3114
