### ISSUE TITLE
v2.0 API | Artifact Additions | Vulnerabilities data has no well defined model in 

### ISSUE THREAD

**Issue by gadinaor** [goharbor/harbor#13468]
Using this API:
`/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/{addition}`

With **vulnerabilities** - a generated go client from the existing API v2.0 swagger.yaml fails because it can't unmarshal JSON into string field.

A modified swagger.yaml such as resolve this issue:
```
      responses:
        '200':
          description: Success
          headers:
            Content-Type:
              description: The content type of the addition
              type: string
          schema:
            type: object # <------- object and not string
            additionalProperties: true
```

Is there a plan to fix this? or expose a well defined API to obtain the report? 

The report I am referring to is here:
`https://github.com/goharbor/harbor/blob/039733b200cc44ba23829499eb6cc71c63d3b9e6/src/pkg/scan/vuln/report.go#L23`

**Comment by steven-zou** [comment]
@heww 

Please confirm if the problem has been fixed already? If it is not fixed, please decide if we need a fix later. Thanks.

**Comment by elenz97** [comment]
Hey @steven-zou @heww, I've encountered the same problem as @gadinaor in the initial issue report.

Using a go client generated by the upstream swagger specification (`v2.4.1` is the latest version as i'm writing) to access either 
`GET ​/projects​/{project_name}​/repositories​/{repository_name}​/artifacts​/{reference}​/additions​/vulnerabilities` **or**
`GET ​/projects​/{project_name}​/repositories​/{repository_name}​/artifacts​/{reference}​/additions​/{addition}` 
will still yield a `cannot unmarshal array into Go value of type string` error.

As per the swagger.yaml, both endpoints define the following schema type on successful responses (as stated by @gadinaor):
```yaml
schema:
  type: string
```

---

I'd like to propose expanding the swagger spec to get a proper struct type in generated go code:

As an example, the `getAddition` operation could have the following schema in its successful response:

```yaml
[...]
schema:
  type: array
  items:
    $ref: '#/definitions/Addition'
```
Below the definition of `Addition`:
```yaml
[...]
  Addition:
    type: object
    description: The addition information
    properties:
      created:
        type: string
        description: The creation date of the addition
      created_by:
        type: string
        description: The command used to create the addition
      empty_layer:
        type: boolean
        description: Indicate whether the addition is an empty layer
      [...]
```

afaik the information that is returned by this endpoint comes from the corresponding layers' internal [`History`](https://github.com/goharbor/harbor/blob/v2.4.1/src/vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go#L63), so the swagger properties could all originate from that struct field.

The same could go for the `getVulnerabilitiesAddition` endpoint, using the struct fields of [`Report`](https://github.com/goharbor/harbor/blob/v2.4.1/src/pkg/scan/vuln/report.go#L25).
