### ISSUE TITLE
No chance to set proxy env to registry and chartserver services

### ISSUE THREAD

**Issue by sporykhin** [goharbor/harbor#13590]
I have an environment behind squid proxy and cant reach S3 service. it seems there is no way to set HTTP_PROXY(S) env vars from harbor.yaml file because after prepare script running no such env-s in service configs

2.1.0 version

**Comment by stonezdj** [comment]
https://github.com/goharbor/harbor/blob/master/make/harbor.yml.tmpl#L182
If you need to add registry in the components list

```
proxy:
  http_proxy: http://proxy.example.com:3128
  https_proxy: http://proxy.example.com:3128
  no_proxy:
  components:
    - core
    - jobservice
    - trivy
    - registry
```

meanwhile, the docker client should have access to the s3 storage because the registry will redirect the request to the s3, so the docker client's host network can reach the s3 storage.
