### ISSUE TITLE
Script `prepare` changes configuration value from small case to uppser case

### ISSUE THREAD

**Issue by h-uchida-n** [goharbor/harbor#13622]
I found a problem in a script `prepare`.
`prepare` script changes configuration valuse `false` to `False` (small f to uppser F) but resistory container does not treat `False` as false. 

## Details:

1. configured `harbor.yml` as follows:
   ```
   storages_service: 
     s3:
       encrypt: false #as default
       secure: false #small `f`
   ```
1. `./common/config/registry/config.yml` was configured as follows when script `prepare` ran.  
   the script switched small `f` to upper `F`.
   ```
   storage: 
     s3: 
       encrypt: False 
       secure: False #Upper `F`
   ```
1. resigtry container behaved as cofigured as `true` when started harbor using above configuration. (Using upper `F`)
1. resigtry container behaved as well as `false` after re-configured `./common/config/registry/config.yml` manually using small `f` as follows:
   ```
   storage: 
     s3: 
       encrypt: false 
       secure: false #small `F`
   ```

## my environment

My environment is as follows:
- harbor version: [v2.1.1]
- docker engine version: [19.03.13]
- docker-compose version: [1.26.0]
