### ISSUE TITLE
Minio ingress spec rules backend svc name is not correct.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor#13773]
What can we help you?

The generated ingress:

```yaml
spec:
  rules:
  - host: minio.core.harbor.domain
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 9000
        path: /
        pathType: ImplementationSpecific

```

but the existing service name is minio-harborcluster-sample.

![image](https://user-images.githubusercontent.com/31262637/102223983-5c998380-3f20-11eb-8acc-05a333a5262d.png)
