### ISSUE TITLE
docker  login  harbor  error

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#13878]
docker login -u admin -p Harbor12345 core.harbor.domain:31247

Username: admin
Password: 
Error response from daemon: Get https://core.harbor.domain:31247/v2/: Get https://core.harbor.domain/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 172.20.0.2:443: connect: connection refused

Web login is accessible and can be logged in

Report this mistake again???

_Originally posted by @misteruly in https://github.com/goharbor/harbor/issues/13870#issuecomment-753834135_

**Comment by stonezdj** [comment]
Your error message is different with the #13870, 
```
dial tcp 172.20.0.2:443: connect: connection refused
```
It seems to be a network issue. usually the 172.20.x.x is default network cidr for docker container, it can not be a IP address for a external host. specify another network cidr in /etc/docker/daemon.json.

**Comment by misteruly** [comment]
@stonezdj Open the tls.Port 30002 is forced to switch to port 443 ??

**Comment by misteruly** [comment]
Insecure Registries:
  core.harbor.domain:30002
  core.harbor.domain:31247
  dockerhub.harbor.local:30002
  172.20.0.2:30002
  127.0.0.0/8
 Registry Mirrors:
  https://72idtxd8.mirror.aliyuncs.com/
 Live Restore Enabled: false

[root@kubesphere docker]# docker login https://core.harbor.domain:31247
Username: admin
Password: 
Error response from daemon: Get https://core.harbor.domain:31247/v2/: Get https://core.harbor.domain/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: dial tcp 172.20.0.2:443: connect: connection refused
[root@kubesphere docker]# cd certs.d/
[root@kubesphere certs.d]# ls
core.harbor.domain  core.harbor.domain:30003  core.harbor.domain:31247
[root@kubesphere certs.d]# 

Can't log in??

**Comment by jiangxiaobin96** [comment]
I met the same error, Is there any solutions now?

**Comment by jiangxiaobin96** [comment]
Hello, I have solved this error.
If `externalURL` set `http`, the `http://nodeIP:30002` must match http nodePort(30002). Because docker registry is default  used `https`, it needs to set `/etc/docker/daemon.json` like `"insecure-registries": ["nodeIP:30002"]` 
```
nodePort:
    # The name of NodePort service
    name: harbor
    ports:
      http:
        # The service port Harbor listens on when serving HTTP
        port: 80
        # The node port Harbor listens on when serving HTTP
        nodePort: 30002
      https:
        # The service port Harbor listens on when serving HTTPS
        port: 443
        # The node port Harbor listens on when serving HTTPS
        nodePort: 30003
  loadBalancer:
    # The name of LoadBalancer service
    name: harbor
    # Set the IP if the LoadBalancer supports assigning IP
    IP: ""
    ports:
      # The service port Harbor listens on when serving HTTP
      httpPort: 80
      # The service port Harbor listens on when serving HTTPS
      httpsPort: 443
    annotations: {}
    sourceRanges: []

# The external URL for Harbor core service. It is used to
# 1) populate the docker/helm commands showed on portal
# 2) populate the token service URL returned to docker client
#
# Format: protocol://domain[:port]. Usually:
# 1) if "expose.type" is "ingress", the "domain" should be
# the value of "expose.ingress.hosts.core"
# 2) if "expose.type" is "clusterIP", the "domain" should be
# the value of "expose.clusterIP.name"
# 3) if "expose.type" is "nodePort", the "domain" should be
# the IP address of k8s node
#
# If Harbor is deployed behind the proxy, set it as the URL of proxy
externalURL: http://nodeIP:30002
```
