### ISSUE TITLE
How to deploy harbor on kubernetes with a NGINX Ingress Controller

### ISSUE THREAD

**Issue by rsoika** [goharbor/harbor#13883]
I have a kubernetes cluster v 1.20.1 running with a NGINX Ingress Controller.
I can not figure out how to setup the helm install to use my NGINX Ingress instead of generating self signed certificates.

My current configuration for the helm chart looks like this: 

```
expose:
  ingress:
    hosts:
      core: "myregistry.foo.com"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      kubernetes.io/ingress.class: nginx
  tls:
    enabled: false
externalURL: "https://myregistry.foo.com"
```

but this did not work. How can I force harbor to work with my NGNIX controller?

**Comment by rsoika** [comment]
I figured out the correct configuration:

```
expose:
  type: ingress
  # NGINX Ingress confiugration
  ingress:
    hosts:
      core: "{YOUR-DOMAIN-NAME}"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      # choose letsencrypt-staging or letsencrypt-prod
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # To be used for the nginx ingress on AKS:
      #kubernetes.io/ingress.class: nginx
  tls:
    enabled: true
    certSource: secret
    secret: 
      secretName: "tls-harbor"

# The external URL for Harbor core service.
externalURL: "https://{YOUR-DOMAIN-NAME}"
```

Maybe there is some place on the page https://goharbor.io/docs/2.1.0/install-config/harbor-ha-helm/ to put this as an example?
