### ISSUE TITLE
Error installing Harbor using MinIO as storage

### ISSUE THREAD

**Issue by IrvingMg** [goharbor/harbor#14093]
Hi everyone,

I want to install Harbor with MinIO as storage. I uncommented the `storage_service` property to set my MinIO instance info in my `harbor.yml` file as below

```yaml
storage_service:
#   # ca_bundle is the path to the custom root ca certificate, which will be injected into the truststore
#   # of registry's and chart repository's containers.  This is usually needed when the user hosts a internal storage with self signed certificate.
#   ca_bundle:
  # storage backend, default is filesystem, options include filesystem, azure, gcs, s3, swift and oss
  # for more info about this configuration please refer https://docs.docker.com/registry/configuration/
  s3:
    accesskey: root
    secretkey: miniopwd
    region: us-east-1
    regionendpoint: http://example.com:9000
    bucket: harbor-registry
    encrypt: true
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
  # set disable to true when you want to disable registry redirect
  redirect:
    disabled: true
```

However, when I ran ./install.sh , the value of the `data_volume` property is used but if I leave it blank or I commented it, the installation gets me an error message. 

How can I disable this property in order to use my s3 storage?
