### ISSUE TITLE
Image pushes from Podman works but from Docker does not

### ISSUE THREAD

**Issue by kam1sh** [goharbor/harbor#14192]
Hi! I'm a new Harbor user and right now I'm trying it in my personal project before proposing to use Harbor on my work.

**Expected behavior and actual behavior:**
I have the next situation:

* Almost clear Harbor installation behind Caddy proxy that terminates TLS.
* Docker pushes does not work, I get something like this in docker:
```
unauthorized: unauthorized to access repository: cec/platform-frontend, action: push: unauthorized to access repository: cec/platform-frontend, action: push
```
and in registry logs:
```
Feb  5 23:32:29 172.21.0.1 registry[734]: time="2021-02-05T23:32:29.167864926Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:d5fe9aaa681bd550de2455df437d9c9a9e24005e810e7d5a01c35d263fa2aa46 err.message="blob unknown to registry" go.version=go1.13.8 http.request.host="192.168.37.207:80" http.request.id=d9eec216-7a39-4753-b992-52bf8d66e8c8 http.request.method=HEAD http.request.remoteaddr=192.168.100.1 http.request.uri="/v2/cec/platform-frontend/blobs/sha256:d5fe9aaa681bd550de2455df437d9c9a9e24005e810e7d5a01c35d263fa2aa46" http.request.useragent="docker/20.10.3 go/go1.13.15 git-commit/46229ca kernel/5.4.0-26-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.3 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.570071ms http.response.status=404 http.response.written=157 vars.digest="sha256:d5fe9aaa681bd550de2455df437d9c9a9e24005e810e7d5a01c35d263fa2aa46" vars.name="cec/platform-frontend" 
```
* BUT. BUT. In Podman it somehow works. With different image, but works!:
```
Feb  5 23:34:26 172.21.0.1 registry[734]: time="2021-02-05T23:34:26.540223786Z" level=info msg="response completed" go.version=go1.13.8 http.request.host="192.168.37.207:80" http.request.id=5d441586-b09d-436b-bfd1-b14b8b371d68 http.request.method=HEAD http.request.remoteaddr=109.252.114.245 http.request.uri="/v2/cec/python/blobs/sha256:06a07484a190ba47e849f1905bb7e2349bb96f50f46246019398eeefa764512d" http.request.useragent="libpod/2.2.1" http.response.contenttype="application/octet-stream" http.response.duration=13.466049ms http.response.status=200 http.response.written=0 
```

**Steps to reproduce the problem:**
???

**Versions:**

- harbor version: 2.1.0
- docker engine version: 19.03.12 (harbor vm), 20.10.3 (VM where I tried to push images)
- podman version: 2.2.1

**Additional context:**

- **Harbor config files:**
```yaml
hostname: harbor.example.org

http:
  port: 80

external_url: https://harbor.example.org

harbor_admin_password: ...

# Harbor DB configuration
database:
  password: ...
  max_idle_conns: 50
  max_open_conns: 1000

data_volume: /data

# Clair configuration
clair:
  # The interval of clair updaters, the unit is hour, set to 0 to disable the updaters.
  updaters_interval: 12

trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 2.1.0

proxy:
  http_proxy: 
  https_proxy: 
  no_proxy: 
  components:
    - core
    - jobservice
    - clair
    - trivy
```
- Caddy config:
```
harbor.example.org {
    reverse_proxy 192.168.37.207:80 {
        header_up Host {http.reverse_proxy.upstream.hostport}
        header_up X-Real-IP {http.request.remote}
        header_up X-Forwarded-Port {http.request.port}
        flush_interval -1
        transport http {
            read_buffer 0
            write_buffer 0
        }
    }
}
```
- **Log files:** I can upload all log files to some cloud or post them here, if you need them.

Even if you couldn't help me, thank you for this interesting project.
