### ISSUE TITLE
Not able to log into fresh install

### ISSUE THREAD

**Issue by weinix** [goharbor/harbor#14209]
What can we help you?

- Environment, kind with k8s v1.20.2
- Chart version: harbor-1.5.3
- App version: 2.1.3
- Expected behavior, able to login portal page with password set
- Issue: Wrong password when trying to log in
- How to duplicate

1. `helm fetch harbor/harbor --untar`
2. `helm install harbor -n harbor ./harbor --set harborAdminPassword="password12345"`
3. Login screenshot
4. Forward harbor-portal port to local:8080
5. attempt login
![image](https://user-images.githubusercontent.com/8346873/107304289-6635f800-6a46-11eb-839f-c10b13075055.png)
6. Nginx log:
```
127.0.0.1 - - [09/Feb/2021:01:37:28 +0000] "POST /c/login HTTP/1.1" 405 559 "http://localhost:8080/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```
7. Other information:
```
 # get all -n harbor                                                            
NAME                                               READY   STATUS    RESTARTS   AGE
pod/harbor-harbor-chartmuseum-868dcff675-8s8l9     1/1     Running   0          12m
pod/harbor-harbor-clair-5c7d8f8676-p74gv           2/2     Running   2          12m
pod/harbor-harbor-core-658d8fd858-kg9q9            1/1     Running   0          12m
pod/harbor-harbor-database-0                       1/1     Running   0          12m
pod/harbor-harbor-jobservice-67bf4bf697-cdktc      1/1     Running   0          12m
pod/harbor-harbor-notary-server-5f79f99c55-r9x86   1/1     Running   0          12m
pod/harbor-harbor-notary-signer-6856f866d4-vdgkm   1/1     Running   0          12m
pod/harbor-harbor-portal-7b4fc78b8-b97c6           1/1     Running   0          12m
pod/harbor-harbor-redis-0                          1/1     Running   0          12m
pod/harbor-harbor-registry-7fc76447bb-5bdhb        2/2     Running   0          12m
pod/harbor-harbor-trivy-0                          1/1     Running   0          12m

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/harbor-harbor-chartmuseum     ClusterIP   10.96.156.134   <none>        80/TCP              12m
service/harbor-harbor-clair           ClusterIP   10.96.106.182   <none>        8080/TCP            12m
service/harbor-harbor-core            ClusterIP   10.96.131.164   <none>        80/TCP              12m
service/harbor-harbor-database        ClusterIP   10.96.91.240    <none>        5432/TCP            12m
service/harbor-harbor-jobservice      ClusterIP   10.96.133.144   <none>        80/TCP              12m
service/harbor-harbor-notary-server   ClusterIP   10.96.245.43    <none>        4443/TCP            12m
service/harbor-harbor-notary-signer   ClusterIP   10.96.46.232    <none>        7899/TCP            12m
service/harbor-harbor-portal          ClusterIP   10.96.191.144   <none>        80/TCP              12m
service/harbor-harbor-redis           ClusterIP   10.96.35.29     <none>        6379/TCP            12m
service/harbor-harbor-registry        ClusterIP   10.96.130.83    <none>        5000/TCP,8080/TCP   12m
service/harbor-harbor-trivy           ClusterIP   10.96.163.220   <none>        8080/TCP            12m

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/harbor-harbor-chartmuseum     1/1     1            1           12m
deployment.apps/harbor-harbor-clair           1/1     1            1           12m
deployment.apps/harbor-harbor-core            1/1     1            1           12m
deployment.apps/harbor-harbor-jobservice      1/1     1            1           12m
deployment.apps/harbor-harbor-notary-server   1/1     1            1           12m
deployment.apps/harbor-harbor-notary-signer   1/1     1            1           12m
deployment.apps/harbor-harbor-portal          1/1     1            1           12m
deployment.apps/harbor-harbor-registry        1/1     1            1           12m

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/harbor-harbor-chartmuseum-868dcff675     1         1         1       12m
replicaset.apps/harbor-harbor-clair-5c7d8f8676           1         1         1       12m
replicaset.apps/harbor-harbor-core-658d8fd858            1         1         1       12m
replicaset.apps/harbor-harbor-jobservice-67bf4bf697      1         1         1       12m
replicaset.apps/harbor-harbor-notary-server-5f79f99c55   1         1         1       12m
replicaset.apps/harbor-harbor-notary-signer-6856f866d4   1         1         1       12m
replicaset.apps/harbor-harbor-portal-7b4fc78b8           1         1         1       12m
replicaset.apps/harbor-harbor-registry-7fc76447bb        1         1         1       12m

NAME                                      READY   AGE
statefulset.apps/harbor-harbor-database   1/1     12m
statefulset.apps/harbor-harbor-redis      1/1     12m
statefulset.apps/harbor-harbor-trivy      1/1     12m
$ get secret harbor-harbor-core -n harbor -o yaml | grep -i admin                                                                                                                   
  HARBOR_ADMIN_PASSWORD: cGFzc3dvcmQxMjM0NQ==
$ echo cGFzc3dvcmQxMjM0NQ== | base64 -d                                                                                                                                                   
password12345
```

**Comment by tbe** [comment]
Same issue for docker-compose installs. More detailed error message:

```
[ERROR] [/jobservice/api/router.go:75]: Serve http request 'POST /c/login' failed with error: {"code":10011,"message":"unauthorized","details":"header 'Authorization' missing"}
```

**Comment by aemaem** [comment]
I installed it on minikube (helm chart version 1.4.6). I fixed it, by not specifying a custom persistent storage for redis.

```
logLevel: debug

expose:
  type: ingress
  ingress:
    annotations:
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      core: registry.local
      notary: signer.registry.local
  tls:
    enabled: true

harborAdminPassword: adminadmin
secretKey: ls1-leftshiftone

externalURL: https://registry.local

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 12Gi
      existingClaim: harbor-volume-claim
      storageClass: harbor
      subPath: registry
    database:
      size: 1Gi
      existingClaim: harbor-volume-claim
      storageClass: harbor
      subPath: database
    jobservice:
      size: 1Gi
      existingClaim: harbor-volume-claim
      storageClass: harbor
      subPath: jobservice
    # redis persistence with custom claim is disable as it makes problems with https://github.com/goharbor/harbor/issues/12753
    # redis:
    #   size: 1Gi
    #   existingClaim: harbor-volume-claim
    #   storageClass: harbor
    #   subPath: redis

registry:
  relativeurls: true
  credentials:
    username: "admin"
    password: "adminadmin"
    htpasswd: "admin:$2y$10$LrjtL/DcSZ3nI.WV.VZBEOx1OkkosiXQZU7LawV7BPkjH9z4a8kVq"

chartmuseum:
  enabled: false
clair:
  enabled: false
notary:
  enabled: false
trivy:
  enabled: false
```
