### ISSUE TITLE
[Feature Request] Configure secret key through environment variable

### ISSUE THREAD

**Issue by jabbors** [goharbor/harbor#14230]
**Is your feature request related to a problem?**
It's not possible to use more secure secrets storage engine (ie vault and bank-vaults secret injector) with harbor-core (currently up to version 2.1.3) since the `secretKey` is read from a file mounted in the containers file system.

**Describe the solution you'd like**
I would like to configure harbor-core to use the value I configure through an environment variable ie. `SECRET_KEY`

The workaround we have done now is to deploy harbor-core with our modified image that writes the value for the provided environment variable holding the the data to the fs where it is expected to be found and then starts up harbor core.

**Comment by meganlyntalley** [comment]
We have this same problem, the workaround makes maintenance a pain.

**Comment by cm-rudolph** [comment]
I worked around this issue by using both bank-vaults vault-env (for the secrets within the environment variables) and vault-agent to provide the secret within a file. To achieve that, I deployed harbor core with the following helm values:

```yaml
core:
  automountServiceAccountToken: true
  podAnnotations:
    vault.security.banzaicloud.io/vault-role: "k8s"
    vault.security.banzaicloud.io/vault-agent-configmap: "harbor-key-template"
    vault.security.banzaicloud.io/vault-agent-env-variables: '[{"name":"SKIP_CHOWN","value":"true"},{"name":"SKIP_SETCAP","value":"true"}]'
  extraEnvVars:
    - name: KEY_PATH
      value: /vault/secrets/key
```

The configmap looks like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-key-template
  namespace: harbor
data:
  config.hcl: |
    vault {
    }
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "k8s"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }
    template {
      contents = <<EOH
        {{- with secret "secrets/data/k8s/harbor/default/harbor" -}}
        {{ .Data.data.communicationSecretKey }}
        {{- end -}}
      EOH
      destination = "/vault/secrets/key"
    }
```

The configmap isn't optimized but close to the examples from the bank-vaults documentation.
