### ISSUE TITLE
Database data directory permission

### ISSUE THREAD

**Issue by electrical** [goharbor/harbor#14354]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
After upgrading I'm getting the following error of the database instance:

```
FATAL: data directory "/var/lib/postgresql/data/pgdata" has group or world access
DETAIL: Permissions should be u=rwx (0700).
```
Perhaps it would be easy to chmod it before starting up to ensure we have the right permissions?

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.3 -> 2.2.0
- Kubernetes: 1.19.7

**Additional context:**

The database instance uses Persisted storage backed by Ceph.

Relevant helm value:
```
    database:
      existingClaim: ""
      storageClass: "rook-ceph-block"
      subPath: "data"
      accessMode: ReadWriteOnce
      size: 1Gi
```
