### ISSUE TITLE
Remove x-golang-type in swagger.yaml

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#14490]
such as 
```
  LdapFailedImportUser:
    type: object
    x-go-type:
      type: FailedImportUser
      import:
        package: "github.com/goharbor/harbor/src/pkg/ldap/model"
  LdapUser:
    type: object
    x-go-type:
      type: User
      import:
        package: "github.com/goharbor/harbor/src/pkg/ldap/model"
  UserGroup:
    type: object
    x-go-type:
      type: Group
      import:
        package: "github.com/goharbor/harbor/src/pkg/ldap/model"
```
