### ISSUE TITLE
access harbor 404

### ISSUE THREAD

**Issue by Hello-Linux** [goharbor/harbor#14495]
The web page show,and the page is blank
```
GET https://harbor.baidu.com/common.c2cef30c4af0102a75d3.js   [HTTP/2 404 Not Found 477ms]

指向“https://harbor.baidu.com/common.c2cef30c4af0102a75d3.js”的 <script> 加载失败。 harbor.baidu.com:1:1
ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 0 failed.
(error: https://harbor.baidu.com/common.c2cef30c4af0102a75d3.js)
n.e@https://harbor.baidu.com/runtime.4f5fe9796a4793599eac.js:1:2074
loadChildren@https://harbor.baidu.com/18.cfb692787e642658894d.js:1:62769
loadModuleFactory@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:753974
load@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:753716
getChildConfig/<@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:740252
_tryNext@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:56631
_next@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:56549
next@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:58828
r/<@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:600691
_trySubscribe@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:345972
subscribe@https://harbor.baidu.com/main.1f96e5d71f1887057edb.js:1:345780
call@ht…
```

**Comment by mxmorin** [comment]
Same issue

**Comment by johann8384** [comment]
Possibly related to #13493

**Comment by reasonerjt** [comment]
@mxmorin @Hello-Linux 
Did you expose Harbor using ingress? what is the ingress controller?

@Hello-Linux Are you using the chart under `goharbor/harbor-helm` repo?

**Comment by mxmorin** [comment]
I think this was due to https://github.com/goharbor/harbor-helm/pull/873

**Comment by ywk253100** [comment]
@Hello-Linux Seems the chart you use isn't a release version(the common.xxx.js is introduced in master branch which isn't released yet). Please try the released version instead.

**Comment by ywk253100** [comment]
@johann8384 Your issue is a different one, already created a new ticket https://github.com/goharbor/harbor-helm/issues/918 for that

**Comment by viceice** [comment]
We have the same issue after upgrading to v2.3.0 docker images

```yaml
expose:
  tls:
    enabled: false
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: 'true'
    hosts:
      core: harbor.domain.test

externalURL: https://harbor.domain.test

persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-data-registry
    jobservice:
      existingClaim: harbor-data-jobservice

database:
  type: external
  external:
    host: postgresql
    username: postgres

imagePullPolicy: Always

redis:
  type: external
  external:
#    sentinelMasterSet: redis
    addr: redis-redis-ha-haproxy:6379

portal:
  replicas: 2
  image:
    repository: goharbor/harbor-portal
    tag: v2.3.0

core:
  replicas: 2
  image:
    repository: goharbor/harbor-core
    tag: v2.3.0

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.3.0

registry:
  replicas: 2
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.3.0

  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.3.0

trivy:
  enabled: true
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.3.0

nginx:
  image:
    repository: goharbor/nginx-photon
    tag: v2.3.0

notary:
  enabled: false

# deprecated stuff

chartmuseum:
  enabled: false

clair:
  enabled: false

```
