### ISSUE TITLE
can not delete a project  with a minio storage 

### ISSUE THREAD

**Issue by lizhiyong2000** [goharbor/harbor#14567]
can not delete a project  with a minio storage 

but the image operations did not fail

![image](https://user-images.githubusercontent.com/5274809/113391880-cd2cb900-93c6-11eb-9e48-906ee794f1b6.png)

- harbor version: v2.2.1-b0d63082
- docker engine version:   19.03.8 
- kubernetes  version: 1.20.5

imageChartStorage config:

```
  imageChartStorage:
    # Specify whether to disable `redirect` for images and chart storage, for
    # backends which not supported it (such as using minio for `s3` storage type), please disable
    # it. To disable redirects, simply set `disableredirect` to `true` instead.
    # Refer to
    # https://github.com/docker/distribution/blob/master/docs/configuration.md#redirect
    # for the detail.
    disableredirect: true
    delete:
      enabled: true
    maintenance:
      uploadpurging:
        enabled: false

    # Specify the "caBundleSecretName" if the storage service uses a self-signed certificate.
    # The secret must contain keys named "ca.crt" which will be injected into the trust store
    # of registry's and chartmuseum's containers.
    # caBundleSecretName:

    # Specify the type of storage: "filesystem", "azure", "gcs", "s3", "swift",
    # "oss" and fill the information needed in the corresponding section. The type
    # must be "filesystem" if you want to use persistent volumes for registry
    # and chartmuseum
    type: s3
    filesystem:
      rootdirectory: /storage
      #maxthreads: 100
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
      #realm: core.windows.net
    gcs:
      bucket: bucketname
      # The base64 encoded json file which contains the key
      encodedkey: base64-encoded-json-key-file
      #rootdirectory: /gcs/object/name/prefix
      #chunksize: "5242880"
    s3:
      region: us-west-1
      bucket: harbor
      accesskey: harbor
      secretkey: harbor_dp@12345
      regionendpoint: https://minio.minio-tenant-1.svc.cluster.local
      encrypt: false
      #keyid: mykeyid
      secure: true
      skipverify: true
      v4auth: true
      chunksize: "5242880"
      rootdirectory: /
      redirect:
        disabled: false
      #storageclass: STANDARD
      #multipartcopychunksize: "33554432"
      #multipartcopymaxconcurrency: 100
      #multipartcopythresholdsize: "33554432"
```

```

/harbor/src/server/middleware/session/session.go:34, github.com/goharbor/harbor/src/server/middleware/session.Middleware.func1.1
--
Fri, Apr 2 2021 3:00:57 pm | 2021-04-02T07:00:57Z [ERROR] [/server/v2.0/handler/project.go:435][requestID="82831bfc1674834e15d620284d3be8eb"]: failed to populate propertites for project library, error: get chart count of project 1 failed: http error: code 500, message RequestError: send request failed
Fri, Apr 2 2021 3:00:57 pm | caused by: Get "https://minio.minio-tenant-1.svc.cluster.local/harbor?prefix=library": x509: certificate signed by unknown authority
Fri, Apr 2 2021 3:00:57 pm | 2021-04-02T07:00:57Z [ERROR] [/server/v2.0/handler/project.go:435][requestID="82831bfc1674834e15d620284d3be8eb"]: failed to populate propertites for project busybox, error: get chart count of project 2 failed: http error: code 500, message RequestError: send request failed
Fri, Apr 2 2021 3:00:57 pm | caused by: Get "https://minio.minio-tenant-1.svc.cluster.local/harbor?prefix=busybox": x509: certificate signed by unknown authority
Fri, Apr 2 2021 3:01:12 pm | 2021-04-02T07:01:12Z [WARNING] [/pkg/systeminfo/imagestorage/filesystem/driver.go:51]: The path /data is not found, will return zero value of capacity
Fri, Apr 2 2021 3:01:13 pm | 2021-04-02T07:01:13Z [ERROR] [/server/v2.0/handler/project.go:435][requestID="8c215f10a37778639bacc897ab7ab20e"]: failed to populate propertites for project busybox, error: get chart count of project 2 failed: http error: code 500, message RequestError: send request failed
Fri, Apr 2 2021 3:01:13 pm | caused by: Get "https://minio.minio-tenant-1.svc.cluster.local/harbor?prefix=busybox": x509: certificate signed by unknown authority
Fri, Apr 2 2021 3:01:13 pm | 2021-04-02T07:01:13Z [ERROR] [/server/v2.0/handler/project.go:435][requestID="8c215f10a37778639bacc897ab7ab20e"]: failed to populate propertites for project library, error: get chart count of project 1 failed: http error: code 500, message RequestError: send request failed
Fri, Apr 2 2021 3:01:13 pm | caused by: Get "https://minio.minio-tenant-1.svc.cluster.local/harbor?prefix=library": x509: certificate signed by unknown authority
Fri, Apr 2 2021 3:02:00 pm | 2021-04-02T07:02:00Z [INFO] [/replication/registry/healthcheck.go:60]: Start regular health check for registries with interval 5m0s


```
