### ISSUE TITLE
docker pull/push failed with nginx reverse proxy

### ISSUE THREAD

**Issue by 20988902** [goharbor/harbor#14593]
## Problem Description

**harbor version**: v2.2.1

**harbor service domain:**  `reg.test.com`

**harbor service works on host:**  `192.168.163.171:8090`

I have an nginx reverse proxy pointing to the back-end harbor service. 

1). When nginx reverse proxy `only enables http`, everything works fine. 
2). If one of the `virtual hosts is configured to https`, docker login is normal, BUT `docker pull/push cannot be executed normally`. Check the nginx error log as follows:

**Nginx error log:**
2021/04/08 16:42:08 [error] 9364#0: *719 "/opt/html/v2/index.html" is not found (2: No such file or directory), client: 192.168.163.171, server: mpdev.test.com, request: "GET /v2/ HTTP/1.1", host: "reg.test.com"
2021/04/08 16:42:08 [error] 9364#0: *720 open() "/opt/html/v2/base/nginx/manifests/v1" failed (2: No such file or directory), client: 192.168.163.171, server: mpdev.test.com, request: "GET /v2/base/nginx/manifests/v1 HTTP/1.1", host: "reg.test.com"

3). When I `changed mpdev.test.com port of https to 444`, docker pull/push also worked normally.

**Nginx Config with http:**

```
server
 	listen		80;
	server_name  reg.test.com;

	client_max_body_size 0; 
	access_log /var/log/reg.test.com.log;

	location / {
		proxy_pass	http://192.168.163.171:8090;
		
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		proxy_set_header X-Forwarded-Proto	$scheme;
		proxy_buffering off;
		proxy_request_buffering off;
	}
}
```

**Nginx Config with https:**
```
server {
	listen		80;
	server_name  mpdev.test.com;
	rewrite ^(.*)$  https://mpdev.test.com$1 permanent;
}

server {
    listen 443 ssl;
    server_name mpdev.test.com;

    ssl_certificate        cert/mpdev.test.com.pem;
    ssl_certificate_key    cert/mpdev.test.com.key;
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_prefer_server_ciphers On;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;

    access_log /var/log/mpdev.test.com.log;

    location / {
        root /opt/html;
        index index.html;
    }
}
```

**harbor.yml**
```
hostname: reg.test.com:8090
http:
  port: 8090
external_url: http://reg.test.com
harbor_admin_password: Harbor12345
database:
  password: root123
  max_idle_conns: 50
  max_open_conns: 1000
data_volume: /var/data/reg
trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.2.0
proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

```
