### ISSUE TITLE
WARNING: no logs are available with the 'syslog' log driver

### ISSUE THREAD

**Issue by softmarch** [goharbor/harbor#14771]
![image](https://user-images.githubusercontent.com/22042539/116407844-c3cb2b00-a864-11eb-8fae-f7ab81bdf263.png)
![image](https://user-images.githubusercontent.com/22042539/116407890-cded2980-a864-11eb-9b94-64d4dcb66e9e.png)

**Comment by softmarch** [comment]
v2.2.1

in v2.0.6:

```shell
sudo docker-compose down -v
remove v2.0.6 docker images
sudo rm -rf /data
```

harbor.yml The following parameters are modified:

```yml
hostname: reg.xxx.cn
# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 8500
# https related config
# https:
  # https port for harbor, default is 443
  # port: 443
  # The path of cert and key files for nginx
  # certificate: /your/certificate/path
  # private_key: /your/private/key/path
external_url: https://reg.xxx.cn
```

in v2.2.1:

```shell
sudo ./install.sh
```
