### ISSUE TITLE
azure storage service

### ISSUE THREAD

**Issue by rasberrypie** [goharbor/harbor#14784]
What can we help you?
I have added storage class for harbor as mentioned below
```
# The default data volume
data_volume: /data

# Harbor Storage settings by default is using /data dir on local filesystem
# Uncomment storage_service setting If you want to using external storage
storage_service:
  azure:
    accountname: xxxxxxxx
    accountkey: xxxxxxxxxx
    container: xxxxx
#   # ca_bundle is the path to the custom root ca certificate, which will be injected into the truststore
#   # of registry's and chart repository's containers.  This is usually needed when the user hosts a internal storage with self signed certificate.
#   ca_bundle:

#   # storage backend, default is filesystem, options include filesystem, azure, gcs, s3, swift and oss
#   # for more info about this configuration please refer https://docs.docker.com/registry/configuration/
#   filesystem:
#     maxthreads: 100
#   # set disable to true when you want to disable registry redirect
#  redirect:
#    disabled: false
```
When i am doing docker login server - it fails saying 
Login did not succeed, error: Error response from daemon: login attempt to https://xxxxxxx/v2/ failed with status: 502 Bad Gateway

If i removed the storage service , docker login succeeds. 
i was able to connect to this blob container from azure storage desktop tool.

logs:

Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/config/config.go:84]: key path: /etc/core/key
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/config/config.go:61]: init secret store
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/config/config.go:64]: init project manager
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/config/config.go:96]: initializing the project manager based on local database...
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/main.go:164]: configurations initialization completed
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-postgresql port-5432 database-registry sslmode-"disable"
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/common/dao/base.go:70]: Register database completed
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/common/dao/pgsql.go:130]: No change in schema, skip.
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/migration/migration.go:58]: Abstracting artifact data to DB...
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/migration/migration.go:67]: No need to abstract artifact data. Skip
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/main.go:81]: User id: 1 already has its encrypted password.
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/main.go:244]: Removing Trivy scanner
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/main.go:258]: Removing Clair scanner
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/main.go:202]: initializing notification...
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/pkg/notification/notification.go:47]: notification initialization completed
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021-04-29T09:50:45Z [INFO] [/core/main.go:221]: Version: v2.1.5, Git commit: 919c9fd2
Apr 29 09:50:45 172.28.0.1 core[5362]: 2021/04/29 09:50:45.383 #033[1;34m[I]#033[0m [asm_amd64.s:1373]  http server Running on http://:8080
Apr 29 09:51:21 172.28.0.1 core[5362]: 2021-04-29T09:51:21Z [INFO] [/replication/registry/healthcheck.go:60]: Start regular health check for registries with interval 5m0s
Apr 29 09:52:07 172.28.0.1 core[5362]: 2021/04/29 09:52:07 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
Apr 29 09:54:10 172.28.0.1 core[5362]: 2021/04/29 09:54:10 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
Apr 29 09:56:58 172.28.0.1 core[5362]: 2021/04/29 09:56:58 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
Apr 29 09:57:50 172.28.0.1 core[5362]: 2021/04/29 09:57:50 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
Apr 29 10:25:03 172.28.0.1 core[5362]: 2021/04/29 10:25:03 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
Apr 29 10:40:00 172.28.0.1 core[5362]: 2021/04/29 10:40:00 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
Apr 29 10:55:14 172.28.0.1 core[5362]: 2021/04/29 10:55:14 http: proxy error: dial tcp 172.28.0.4:5000: connect: connection refused
