### ISSUE TITLE
Harbor registry - s3aws: AccessDenied

### ISSUE THREAD

**Issue by pbradly** [goharbor/harbor#14792]
**Expected behavior:**
User is able to successfully push docker image to the registry and it is stored on the S3 bucket

**Actual behavior:**
When attempting to push docker images to the registry, it fails giving the following error;

```time="2021-04-30T16:42:58.755384646Z" level=info msg="authorized request" go.version=go1.15.6 http.request.host=registry.harbor.identos.ca http.request.id=22c2366e-dc9b-45be-9872-1b6c7dfdea7f http.request.method=POST http.request.remoteaddr=3.97.44.84 http.request.uri="/v2/<REDACTED>/<REDACTED>/blobs/uploads/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))" vars.name="<REDACTED>/<REDACTED>" 
100.117.138.199 - - [30/Apr/2021:16:42:58 +0000] "POST /v2/<REDACTED>/<REDACTED>/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \\(darwin\\))"
time="2021-04-30T16:42:58.810237064Z" level=info msg="response completed" go.version=go1.15.6 http.request.host=registry.harbor.identos.ca http.request.id=22c2366e-dc9b-45be-9872-1b6c7dfdea7f http.request.method=POST http.request.remoteaddr=3.97.44.84 http.request.uri="/v2/<REDACTED>/<REDACTED>/blobs/uploads/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))" http.response.duration=129.282456ms http.response.status=202 http.response.written=0 
time="2021-04-30T16:42:59.033178391Z" level=info msg="authorized request" go.version=go1.15.6 http.request.host=registry.harbor.identos.ca http.request.id=a0cb0368-56dd-48a8-a312-c3454da8800c http.request.method=PATCH http.request.remoteaddr=3.97.44.84 http.request.uri="/v2/<REDACTED>/<REDACTED>/blobs/uploads/4cc00559-0db3-4e94-b2ac-a572ec2aaffa?_state=ZNR1L3jht2pKO0nDGln1V-lu2Hc9bCKqWtYbOvlz4RJ7Ik5hbWUiOiJmcHgtd2FsbGV0L3dhbGxldC1zZXJ2ZXIiLCJVVUlEIjoiNGNjMDA1NTktMGRiMy00ZTk0LWIyYWMtYTU3MmVjMmFhZmZhIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIxLTA0LTMwVDE2OjQyOjQ5LjY3NDY0ODExMVoifQ%3D%3D" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))" vars.name="<REDACTED>/<REDACTED>" vars.uuid=4cc00559-0db3-4e94-b2ac-a572ec2aaffa 
time="2021-04-30T16:42:59.049897075Z" level=error msg="error resolving upload: s3aws: AccessDenied: Access Denied
	status code: 403, request id: 3PCWAZNZ3CZQCAKC, host id: AZYRy77pTt0tzqjBKczpMoqd/AIFtLpSrm6EscNhTy/u6C48ICJ8omwQrFkUdoH0HTpLa5RvU/A=" auth.user.name="harbor_registry_user" go.version=go1.15.6 http.request.host=registry.harbor.identos.ca http.request.id=a0cb0368-56dd-48a8-a312-c3454da8800c http.request.method=PATCH http.request.remoteaddr=3.97.44.84 http.request.uri="/v2/<REDACTED>/<REDACTED>/blobs/uploads/4cc00559-0db3-4e94-b2ac-a572ec2aaffa?_state=ZNR1L3jht2pKO0nDGln1V-lu2Hc9bCKqWtYbOvlz4RJ7Ik5hbWUiOiJmcHgtd2FsbGV0L3dhbGxldC1zZXJ2ZXIiLCJVVUlEIjoiNGNjMDA1NTktMGRiMy00ZTk0LWIyYWMtYTU3MmVjMmFhZmZhIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIxLTA0LTMwVDE2OjQyOjQ5LjY3NDY0ODExMVoifQ%3D%3D" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))" vars.name="<REDACTED>/<REDACTED>" vars.uuid=4cc00559-0db3-4e94-b2ac-a572ec2aaffa 
time="2021-04-30T16:42:59.049970136Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: AccessDenied: Access Denied
```

We have confirmed that the AWS user does have permission to push objects to the bucket, as we are able to push objects into the bucket using the users access token via the AWS CLI. We can see that during the docker push, objects are getting pushed into the S3 bucket. 

Despite this the docker push gets stuck in a retrying loop as the registry says it does not have access to the bucket

**Steps to reproduce the problem:**
- Create S3 bucket and AWS user with permission to push objects to that bucket
- Install Harbor on K8s cluster via helm-chart, using Access token from AWS User
- Attempt to push docker image to harbor registry

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.2]
- docker engine version: [19.03.8]
- Kubernetes version: [1.18.18]
- Helm Version: [3.2.0]

**Additional context:**

<details>
<summary>Harbor Helm Values file</summary>
<p>

```yaml
expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-registry-cert"
      notarySecretName: "harbor-notary-cert"
  ingress:
    hosts:
      core: *****
      notary: *****
    controller: default
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/cluster-issuer: letsencrypt-prod

externalURL: https://*****

internalTLS:
  enabled: true
  certSource: "auto"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: false
    type: s3
    s3:
      region: ca-central-1
      bucket: *****
      accesskey: *****
      secretkey: *****
      regionendpoint: https://s3.ca-central-1.amazonaws.com
      secure: true
      v4auth: true

imagePullPolicy: IfNotPresent

imagePullSecrets:
updateStrategy:
  type: RollingUpdate

logLevel: info

harborAdminPassword: "*****"

caSecretName: ""

secretKey: "*****"

proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
  components:
    - core
    - jobservice
    - trivy

portal:
  image:
    repository: goharbor/harbor-portal
    tag: v2.2.1
  serviceAccountName: ""
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

core:
  image:
    repository: goharbor/harbor-core
    tag: v2.2.1
  serviceAccountName: ""
  replicas: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""
  secretName: ""
  xsrfKey: ""

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.2.1
  replicas: 1
  serviceAccountName: ""
  maxJobWorkers: 10
  jobLoggers:
    - file
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""

registry:
  serviceAccountName: ""
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.2.1
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.2.1

  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""
  relativeurls: false
  credentials:
    username: "harbor_registry_user"
    password: "harbor_registry_password"
    htpasswd: "harbor_registry_user:$2y$10$9L4Tc0DJbFFMB6RdSCunrOpTHdwhid4ktBJmLD00bYgqkkGOvll3m"

  middleware:
    enabled: false
    type: cloudFront
    cloudFront:
      baseurl: example.cloudfront.net
      keypairid: KEYPAIRID
      duration: 3000s
      ipfilteredby: none
      privateKeySecret: "my-secret"

chartmuseum:
  enabled: true
  serviceAccountName: ""
  absoluteUrl: false
  image:
    repository: goharbor/chartmuseum-photon
    tag: v2.2.1
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

trivy:
  enabled: true
  image:
    repository: goharbor/trivy-adapter-photon
    tag: v2.2.1
  serviceAccountName: ""
  replicas: 1
  debugMode: false
  vulnType: "os,library"
  severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  ignoreUnfixed: false
  insecure: false
  gitHubToken: ""
  skipUpdate: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

notary:
  enabled: true
  server:
    serviceAccountName: ""
    image:
      repository: goharbor/notary-server-photon
      tag: v2.2.1
    replicas: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}
  signer:
    serviceAccountName: ""
    image:
      repository: goharbor/notary-signer-photon
      tag: v2.2.1
    replicas: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podAnnotations: {}
  secretName: ""

database:
  type: internal
  internal:
    serviceAccountName: ""
    image:
      repository: goharbor/harbor-db
      tag: v2.2.1
    password: "changeit"
    nodeSelector: {}
    tolerations: []
    affinity: {}
    initContainer:
      migrator: {}
      permissions: {}
  maxIdleConns: 50
  maxOpenConns: 1000
  podAnnotations: {}

redis:
  type: internal
  internal:
    serviceAccountName: ""
    image:
      repository: goharbor/redis-photon
      tag: v2.2.1
    nodeSelector: {}
    tolerations: []
    affinity: {}
  podAnnotations: {}

exporter:
    replicas: 1
    podAnnotations: {}
    serviceAccountName: ""
    image:
      repository: goharbor/harbor-exporter
      tag: v2.2.1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    cacheDuration: 30
    cacheCleanInterval: 14400

metrics:
  enabled: false
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    interval: ""
    metricRelabelings: []
    relabelings: []
```
</p>
</details>
