### ISSUE TITLE
harbor portal ingress common.js 404

### ISSUE THREAD

**Issue by febelery** [goharbor/harbor#14800]
# issue
`https://harbor.xxx.com/common.230a782a18b7e7924cc0.js` 404

# k8s yaml config
```yaml
expose:
  type: ingress
```
# portal nginx log
```
10.233.105.26 - - [05/May/2021:03:25:11 +0000] "GET /favicon.ico HTTP/1.1" 200 7455 "https://harbor.febelery.com/common.230a782a18b7e7924cc0.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"

10.233.105.26 - - [05/May/2021:03:25:30 +0000] "GET /17.2748988b749ff9feec69.js HTTP/1.1" 200 22439 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
```

**Comment by febelery** [comment]
add ingress route 
```yaml

          - path: /common
            pathType: Prefix
            backend:
              serviceName: harbor-harbor-portal
              servicePort: 80

```
