### ISSUE TITLE
Replication status report 'Failed' wrongly for a short period.

### ISSUE THREAD

**Issue by dsnt02518** [goharbor/harbor#14986]
I'm triggering a pull replication from dockerhub to my local harbor instance via the API from an Ansible playbook.
The playbook will then poll the replication every 5s and wait for it to complete. Sometimes the status returned from the API will be 'Failed', however the replication has actually succeeded (and subsequent checks show the correct status).

Calling API endpoint: GET api/v2.0/replication/executions/3351

**Expected behavior and actual behavior:**
Expected behaviour: Status should be 'InProgress' until complete, then 'Succeed', or 'Failed' only if replication actually fails.
Actual behaviour: Status transitions to 'Failed' for a short period prior to becoming 'Succeed'. 

Results returned to Ansible from status GET request:
```
{
  "end_time": "2021-05-26T13:33:00.000Z",
  "failed": 1,
  "id": 3351,
  "in_progress": 0,
  "policy_id": 1304,
  "start_time": "2021-05-26T13:32:38.987Z",
  "status": "Failed",
  "status_text": "",
  "stopped": 0,
  "succeed": 0,
  "total": 1,
  "trigger": "manual"
}
```
Subsequent calls to the same GET request:
```
{
  "end_time": "2021-05-26T13:33:33.000Z",
  "failed": 0,
  "id": 3351,
  "in_progress": 0,
  "policy_id": 1304,
  "start_time": "2021-05-26T13:32:38.987Z",
  "status": "Succeed",
  "status_text": "",
  "stopped": 0,
  "succeed": 1,
  "total": 1,
  "trigger": "manual"
}
```
Note that the timestamps do not change.

**Steps to reproduce the problem:**
Trigger a replication via the API  (POST to api/v2.0/replication/executions)
Monitor status via GET api/v2.0/replication/executions/<id>

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.2.1-b0d63082]
- docker engine version: [2.10.6]
- docker-compose version: [1.18.0]

**Additional context:**

- **Harbor config files:** 
harbor.yml:
```
hostname: harbor.keyop.co.uk
http:
  port: 80
https:
  port: 443
  certificate: /etc/letsencrypt/live/harbor.keyop.co.uk/fullchain.pem
  private_key: /etc/letsencrypt/live/harbor.keyop.co.uk/privkey.pem
harbor_admin_password: ########
database:
  password: ########
  max_idle_conns: 50
  max_open_conns: 1000
data_volume: /harbordata
trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.2.0
proxy:
  http_proxy: 
  https_proxy: 
  no_proxy: 
  components:
    - core
    - jobservice
    - trivy
```
- **Log files:** These are a bit large, but happy to provide some or all of them if required.
