### ISSUE TITLE
'-' char in yaml respond for helm char list in respond

### ISSUE THREAD

**Issue by spyroot** [goharbor/harbor#15008]
Hi Folks,

Is there any particular reason why Harbor respond forget the request for example for a chart? I believe you changed the behavior.

```
apiVersion: v1
entries:
  flexran:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-05-28T05:51:29.593954817Z"
    description: test
    digest: f27582c40482b81cfef53a88156485c76acd56178f4e0ab3617ea519397c087f
    name: test
    type: application
    urls:
    - charts/test-1.0.0.tgz
    version: 1.0.0

```

Thank you.
