### ISSUE TITLE
[v2.3.0] Redis sentinel isn't supported by prepare script

### ISSUE THREAD

**Issue by sixeIa** [goharbor/harbor#15185]
**Expected behavior and actual behavior:**
After upgrading to 2.3.0, redis sentinel isn't supported.
Indeed, files receive "redis://" format but no "redis+sentinel://" (for example jobservice) as it did for 2.1.0 and 2.2.0.
Forcing the data well works anyway, it seems to be related to a script not taking sentinel into account.

**Steps to reproduce the problem:**
Upgrade to 2.3.0 (or install it).
Migrate harbor.yml file.
Use prepare script to generate app files with redis sentinel in harbor.yml.

**Versions:**
- harbor version: [2.3.0]

**Additional context:**
jobservice config.yml:
```
---
#Protocol used to serve
protocol: "https"

https_config:
  cert: "/etc/harbor/ssl/job_service.crt"
  key: "/etc/harbor/ssl/job_service.key"

#Server listening port
port: 8443

#Worker pool
worker_pool:
  #Worker concurrency
  workers: 10
  backend: "redis"
  #Additional config if use 'redis' backend
  redis_pool:
    #redis://[arbitrary_username:password@]ipaddress:port/database_index
    redis_url: redis://:[REDACTED]@10.0.0.1:26379,10.0.0.2:26379,10.0.0.3:26379/2?idle_timeout_seconds=30
    namespace: "harbor_job_service_namespace"
    idle_timeout_second: 3600
```
harbor.yml extract:
```
external_redis:
  # support redis, redis+sentinel
  # host for redis: <host_redis>:<port_redis>
  # host for redis+sentinel:
  #  <host_sentinel1>:<port_sentinel1>,<host_sentinel2>:<port_sentinel2>,<host_sentinel3>:<port_sentinel3>
  host: 10.0.0.1:26379,10.0.0.2:26379,10.0.0.3:26379
  password: r2RJIruMOCq5NbIxjaxXFphi
  # sentinel_master_set must be set to support redis+sentinel
  #sentinel_master_set:
  # db_index 0 is for core, it's unchangeable
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  trivy_db_index: 5
  idle_timeout_seconds: 30
```
