### ISSUE TITLE
docker push error with "401 UNAUTHORIZED" after upgrade harbor to v2.3.1

### ISSUE THREAD

**Issue by gejunqiang** [goharbor/harbor#15375]
# Problem description

We upgrade our harbor from v1.10.6 to v2.3.1 with [harbor-helm](https://github.com/goharbor/harbor-helm/tree/1.7.1)，and then we found that when docker push a image, it sometimes returned a error with messge "401 UNAUTHORIZED", just like below:
```json
{
    "errorDetail":{
        "message":"unauthorized: http status code: 401, body: {\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"faulttest-default/a-30153\",\"Action\":\"pull\"}]}]}\n"
    },
    "error":"unauthorized: http status code: 401, body: {\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"faulttest-default/a-30153\",\"Action\":\"pull\"}]}]}\n"
}
```
The most import thing is that, this error is not happened everytime. It happened with around 20% probability.

From the harbor-registry log, we found that , the error happened when harbor-core get manifest from harbor-registry. The harbor-registry log is shown as below:

```
time="2021-07-29T17:28:16.499876126+08:00" level=warning msg="error authorizing context: basic authentication challenge for realm "harbor-registry-basic-realm": invalid authorization credential" go.version=go1.15.12 http.request.host="harbor-harbor-registry:5000" http.request.id=cafa9a94-635d-431d-ab19-2a66cde1dca2 http.request.method=GET http.request.remoteaddr="10.116.135.169:57890" http.request.uri="/v2/faulttest-default/a-30153/manifests/sha256:b78c307c83ba1526c24eb322e64266baf24ac473c86a8c1a7430b67c89074564" http.request.useragent=harbor-registry-client vars.name="faulttest-default/a-30153" vars.reference="sha256:b78c307c83ba1526c24eb322e64266baf24ac473c86a8c1a7430b67c89074564"
10.116.135.169 - - [29/Jul/2021:17:28:18 +0800] "GET /v2/faulttest-default/a-30153/manifests/sha256:ae211908fa6bce97736357ef416049fc31afe4c82f688d1d7410c2c414412ee2 HTTP/1.1" 401 168 "" "harbor-registry-client"
```

# Harbor config

## harbor-core configMap:
```yaml
apiVersion: v1
data:
  _REDIS_URL_CORE: redis://redis-haproxy:6379/0?idle_timeout_seconds=30
  _REDIS_URL_REG: redis://redis-haproxy:6379/2?idle_timeout_seconds=30
  CHART_CACHE_DRIVER: redis
  CHART_REPOSITORY_URL: http://harbor-harbor-chartmuseum
  CONFIG_PATH: /etc/core/app.conf
  CORE_LOCAL_URL: http://127.0.0.1:8080
  CORE_URL: http://harbor-harbor-core:80
  DATABASE_TYPE: postgresql
  EXT_ENDPOINT: https://harbor.my-company.com
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  JOBSERVICE_URL: http://harbor-harbor-jobservice
  LOG_LEVEL: info
  METRIC_ENABLE: "true"
  METRIC_NAMESPACE: harbor
  METRIC_PATH: /metrics
  METRIC_PORT: "8001"
  METRIC_SUBSYSTEM: core
  NO_PROXY: harbor-harbor-core,harbor-harbor-jobservice,harbor-harbor-database,harbor-harbor-chartmuseum,harbor-harbor-notary-server,harbor-harbor-notary-signer,harbor-harbor-registry,harbor-harbor-portal,harbor-harbor-trivy,harbor-harbor-exporter,127.0.0.1,localhost,.local,.internal
  NOTARY_URL: http://harbor-harbor-notary-server:4443
  PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry
  PORT: "8080"
  PORTAL_URL: http://harbor-harbor-portal
  POSTGRESQL_DATABASE: registry
  POSTGRESQL_HOST: stolon-proxy
  POSTGRESQL_MAX_IDLE_CONNS: "100"
  POSTGRESQL_MAX_OPEN_CONNS: "900"
  POSTGRESQL_PORT: "80"
  POSTGRESQL_SSLMODE: disable
  POSTGRESQL_USERNAME: stolon
  REGISTRY_CONTROLLER_URL: http://harbor-harbor-registry:8080
  REGISTRY_CREDENTIAL_USERNAME: harbor_registry_user
  REGISTRY_STORAGE_PROVIDER_NAME: s3
  REGISTRY_URL: http://harbor-harbor-registry:5000
  TOKEN_SERVICE_URL: http://harbor-harbor-core:80/service/token
  TRIVY_ADAPTER_URL: http://harbor-harbor-trivy:8080
  WITH_CHARTMUSEUM: "true"
  WITH_NOTARY: "false"
  WITH_TRIVY: "false"
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8080
kind: ConfigMap
metadata:
  name: harbor-harbor-core
  namespace: harbor
```

## harbor-registry configMap:

```yaml
apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      s3:
        region: us-east-1
        bucket: harbor
        regionendpoint: http://harbor.service.org
        skipverify: true
      cache:
        layerinfo: redis
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
      redirect:
        disable: false
    redis:
      addr: redis-haproxy:6379
      db: 2
      readtimeout: 10s
      writetimeout: 10s
      dialtimeout: 10s
      pool:
        maxidle: 100
        maxactive: 500
        idletimeout: 60s
    http:
      addr: :5000
      relativeurls: false
      # set via environment variable
      # secret: placeholder
      debug:
        addr: :8001
        prometheus:
          enabled: true
          path: /metrics
    auth:
      htpasswd:
        realm: harbor-registry-basic-realm
        path: /etc/registry/passwd
    validation:
      disabled: true
    compatibility:
      schema1:
        enabled: true
  ctl-config.yml: |
    ---
    protocol: "http"
    port: 8080
    log_level: info
    registry_config: "/etc/registry/config.yml"
kind: ConfigMap
metadata:
  name: harbor-harbor-registry
  namespace: harbor
```

# Additional Info
- harbor version: v2.3.1
- docker version: 19.03.14
