### ISSUE TITLE
Data missing after upgrading from v1.10.0 to v2.3.0

### ISSUE THREAD

**Issue by clp01** [goharbor/harbor#15383]
Hi,

I attempted to upgrade from v1.10.0 to v2.3.0, which according to the [documentation](https://goharbor.io/docs/2.3.0/administration/upgrade/) is a valid upgrade path.

This appeared to work fine however when I logged into the GUI with the admin account all of our data (projects, users) was missing. I restarted harbor and since then the harbor-db container has been restarting continuously with the following in the logs:

```
postgresql[223139]: ls: cannot access '/var/lib/postgresql/data': Operation not permitted
postgresql[223139]: initdb: error: directory "/var/lib/postgresql/data/pg13" exists but is not empty
postgresql[223139]: If you want to create a new database system, either remove or empty
postgresql[223139]: the directory "/var/lib/postgresql/data/pg13" or run initdb
postgresql[223139]: with an argument other than "/var/lib/postgresql/data/pg13".
```

I assume this means that I can clear the /data/database/pg13 folder, however we want to be able to keep our data after upgrading. Is there some way around this?

Thanks,

Charlotte

**Comment by clp01** [comment]
I reverted the VM to a checkpoint and attempted this again, this time using the following upgrade path:

v1.10.0 -> v2.1.6 -> v2.2.3 -> v2.3.1

There were no issues up to v2.2.3, but I experienced the same issue as above when going from v2.2.3 to v2.3.1.

Any help would be greatly appreciated.

**Comment by clp01** [comment]
I tried clearing the /data/database/pg13 folder and although this allowed all harbor containers to start up I was unable to login to the GUI with the admin account. A subsequent restart of harbor caused the original issue to reoccur.

Relevant section of docker-compose.yaml is below:
```
  postgresql:
    image: goharbor/harbor-db:v2.3.1
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
    dns_search: .
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "postgresql"
    shm_size: '1gb'
```
