### ISSUE TITLE
 push: unauthorized to access repository

### ISSUE THREAD

**Issue by cmille62** [goharbor/harbor#15392]
Setup is using OIDC Login for the Client; within the Docker CLI it returns: 
```
unauthorized: unauthorized to access repository: {repo}, action: push: unauthorized to access repository: {repo}, action: push
```

I've tried this with a system robot with full access and a admin user, here is what happens with the admin user:

The OIDC works properly in the Portal, but via the CLI it fails.

I think it has something to do with the nginx-ingress, and me using arn-certificate.

I've tried using TLS true, and the cert as none, that causes infinite redirects, not sure what else to do. 

When I try with a user and their CLI code this occurs in the core backend logs:
```
2021-08-06T18:05:04Z [WARNING] [/pkg/oidc/helper.go:349]: OIDC. Failed to recover Username from claim. Claim 'user' is invalid or not a string
```

Docker Login:
```
docker login https://harbor.{url}.com-u {username} -p {cli key}
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
```

Docker Push:
```
docker push harbor.{url}.com/{project}/{repository}:[tag]                              
The push refers to repository [harbor.{url}.com/{project}/{repository}]
dbfb4986f117: Pushing  3.584kB
f6ab51ee6551: Pushing [==================================================>]  9.216kB
5d2c4c7ea45e: Pushing [==========================================>        ]  601.1kB/700.1kB
4553ef6ccad0: Pushing [==================================================>]   7.68kB
62fb8c0324b5: Pushing  5.632kB
6f031ef6fbe4: Waiting 
67c3f952c742: Waiting 
813c982a3669: Waiting 
55d1a584cbba: Waiting 
fcb1779cb1c5: Waiting 
b6f2e3d8c0e2: Waiting 
48a4c3c3d4c1: Waiting 
00360a51d728: Waiting 
442644222c14: Waiting 
ed5e20d12d57: Waiting 
dd3097cd7909: Waiting 
685934357c89: Waiting 
ccb9b68523fd: Waiting 
00bcea93703b: Waiting 
688e187d6c79: Waiting 
unauthorized: unauthorized to access repository: {project}/{repository}, action: push: unauthorized to access repository: {project}/{repository}, action: push
```

Values File: 

[values.yaml.txt](https://github.com/goharbor/harbor/files/6947667/values.yaml.txt)

Thanks!

**Comment by cmille62** [comment]
My Nginx-Intress has tls-terminination enabled, would that be a potential cause?

**Comment by cmille62** [comment]
When trying using a system-level robot, it says failed to get oidc info, not sure why this is the case for a robot 

2021-08-14T22:36:08Z [ERROR] [/server/middleware/security/oidc_cli.go:62][requestID="9e54b7cd6d0919b76ead7bb3a05f085b"]: failed to verify secret, username: robot-dev, error: failed to get oidc user info, error: <QuerySeter> no row found
1
2021-08-14T22:36:08Z [INFO] [/server/middleware/security/robot.go:88][requestID="9e54b7cd6d0919b76ead7bb3a05f085b"]: a robot security context generated for request GET /service/token

**Comment by cmille62** [comment]
With the system-admin account; 


2
2021-08-14T22:58:04Z [ERROR] [/server/middleware/security/oidc_cli.go:62][requestID="f9e6a505a750163666ff3896634231b5"]: failed to verify secret, username: admin, error: failed to get oidc user info, error: <QuerySeter> no row found

**Comment by cmille62** [comment]
It looks like when behind a reverse proxy, you need to set the  ` relativeurls: true ` 

also in my annotations for ingress, 

```YAML
ingress.kubernetes.io/ssl-redirect: "true"
ingress.kubernetes.io/proxy-body-size: "0"
nginx.ingress.kubernetes.io/ssl-redirect: "true"
nginx.ingress.kubernetes.io/proxy-body-size: "0"
nginx.ingress.kubernetes.io/certificate-arn: {arn}
nginx.ingress.kubernetes.io/configuration-snippet: |
proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header  X-Forwarded-Proto $scheme;
```
