### ISSUE TITLE
external_redis: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

### ISSUE THREAD

**Issue by mrh666** [goharbor/harbor#15403]
I'm trying to use AWS ElastiCache as cache for Harbor 2.3.1. I have a Redis cluster with two instances cache.t3.small and Harbor can't connect to configuration endpoint neither instance endpoints with the same error: 
```
failed to ping redis://:xxxxx@dev-harbor-redis-0001-001.XXXXXXXX.XXX.euc1.cache.amazonaws.com:6379?idle_timeout_seconds=30, retry after 10s : ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

Configuration:
```
external_redis:
  host: dev-harbor-redis-0001-001.XXXXXXXX.XXX.az1.cache.amazonaws.com:6379
  password: working_password
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  trivy_db_index: 5
  idle_timeout_seconds: 30
```

- Harbor 2.3.1 is installed (```/opt/harbor# ./install.sh --with-trivy --with-chartmuseum```) with offline installer in Ubuntu Focal AWS ec2 instance.
- docker version: 20.10.8
- docker-compose version: 1.25.0

Currently I'm using it with local redis container but I will highly appreciate any help on making ElastiCache work with Harbor.
