### ISSUE TITLE
The `_upload` folders are taking too much space

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#15641]
A user reported that after using ~2months the `_upload` folders are taking >90GB of space.

1) We should investigate if this is normal, if it is we should update the doc to provide a workaround.
2) We should consider provide an API or tool to clean that up

The user was using Harbor v1.10.x which we no longer support but this problem may happen in recent releases.

**Comment by wy65701436** [comment]
We would like to collect some date from your environment, you can get it with the following commane(1 or 2):

1. find . -name "_uploads" | xargs du -sh 
2. tree --du -h /data/registry/docker/registry/v2/repositories/*/*/_uploads/

**Comment by cobolbaby** [comment]
After I upgraded the harbor version, there are many historical files in uploads that need to be cleaned up, and it seems that GC will not clean up these failed files.

harbor version: 2.1.4 / 2.3.3

**Comment by cobolbaby** [comment]
```
find /storage  -path "*/_uploads/*" -type f -mtime +1d |xargs rm -rf
```

Although the files that took up a lot of space were deleted, many empty folders were left.

**Comment by Vad1mo** [comment]
@cobolbaby are you on AliCloud?
Can you verify that the registry has the correct permission on the object store and is allowed to delete files?

The registry just silently ignores the error if it can delete the upload blobs.

**Comment by stonezdj** [comment]
Adding a configure parameter in harbor.yaml
```
uploadpurging:
  enabled: true
  # remove files in _upload directories which exist for a period of time, default is one week.
  age: 168h
  # the interval of the purge operations
  interval: 24h
  dryrun: false
```
