### ISSUE TITLE
Encountered 404 error while accessing harbor

### ISSUE THREAD

**Issue by xiaohuanxiong3** [goharbor/harbor#15816]
I want to access harbor(docker) through nginx's secondary directory(just like http://domain/myharbor) and i meet the following problem
![image](https://user-images.githubusercontent.com/39520495/137874671-6cb7d096-4869-49f2-a1c3-10674e76ff75.png)
Here is my configuration in harbor.yml and nginx.conf
```
# Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: 192.168.1.11

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 30081
  relativeurls: true

# https related config
# https:
  # https port for harbor, default is 443
#  port: 443
  # The path of cert and key files for nginx
#  certificate: /your/certificate/path
#  private_key: /your/private/key/path

# # Uncomment following will enable tls communication between all harbor components
# internal_tls:
#   # set enabled to true means internal tls is enabled
#   enabled: true
#   # put your cert and key files on dir
#   dir: /etc/harbor/tls/internal

# Uncomment external_url if you want to enable external proxy
# And when it enabled the hostname will no longer used
# external_url:

# The initial password of Harbor admin
# It only works in first time to install harbor
# Remember Change the admin password from UI after launching Harbor.
harbor_admin_password: admin
......
(The rest of the configuration has not changed.)
```
and configuration of nginx
```
location ^~ /harbor/ {
	proxy_pass http://harbor/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Fonwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
}
```
I hava also tried external_url in harbor.yml but failed too.
I would be very appreciate if anyone can help.
