### ISSUE TITLE
Harbor failed to connect to redis Cluster

### ISSUE THREAD

**Issue by misteruly** [goharbor/harbor#15814]
<html>
<body>
<!DOCTYPE html>

主机名 | IP | 端口
-- | -- | --
redis-1 | 192.168.1.11 | 5001,5002
redis-2 | 192.168.1.10 | 5003,5004
redis-3 | 192.168.1.7 | 5005,5006

</body>
</html>

![image-20211014101911740](https://image.z5689.com/blog/image-20211014101911740.png)

Harbor's Redis configuration
   ```
   external_redis:
       host: 192.168.1.10:5003
       password: 123456
       registry_db_index: 1
        jobservice_db_index: 2
       chartmuseum_db_index: 3
       trivy_db_index: 5
       idle_timeout_seconds: 30
   ```

Harbor login error, core service unavailable
 ```
[ERROR] [/server/middleware/security/session.go:34][requestID="9409457e-ed48-49e7-8894-dea13eb9d9c8"]: failed to get the session store for request: MOVED 3754 192.168.1.11:5001
 ```

How to solve this problem？？
