### ISSUE TITLE
Harbor Portal on Path instead of domain root.

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor#16031]
We modified Harbor Portal to be presenet on the path `/console` instead the default `/`

For that to work we had to build the portal in `portal/Dockerfile` with the angular build parameters `base-href` and `deploy-url`

`RUN node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod --base-href /console/ --deploy-url console/`

So far it is working fine. 

The only problem is that when OIDC is enabled, the user is redirected  to  root `/` instead to the `/path`

see: https://github.com/goharbor/harbor/blob/44f477e965e57ba619d494a7122c69a636906666/src/core/controllers/oidc.go#L169

**My questions to the fellow maintainers are:**

1. Can we make the redirect path configurable?
	2. Via Config File?
	3. Via the UI?
2. Should we add our modifications as a feature into Harbor.
	Makefile and Dockerfile changes for the Portal, so a user can build
	the portal with a different root path.

**Comment by stonezdj** [comment]
could you please raise a PR for it? not sure it will break change other features.

**Comment by Vad1mo** [comment]
Here is the solution that works:
**Ingress**

```yaml
  rules:
    - host: demo.example.com
      http:
        paths:
          - path: /admin-console/
            pathType: Prefix
            backend:
              service:
                name: harbor-portal
                port:
                  number: 80
```

**Nginx of Harbor Portal**
```nginx
worker_processes auto;
pid /tmp/nginx.pid;
events {
    worker_connections  1024;
}
http {
    client_body_temp_path /tmp/client_body_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;
    server {
        listen 8080;
        listen [::]:8080;
        server_name  localhost;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;
        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        
        location /admin-console/ {
           rewrite ^/admin-console/(.*) /$1 break;
           try_files $uri $uri/ /index.html;
        }

        location = /index.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
            sub_filter 'base href="/"' 'base href="/admin-console/"';
            sub_filter_once on;
        }
    }
}

```
