### ISSUE TITLE
How to configure timout for image scan

### ISSUE THREAD

**Issue by ShabiDabi** [goharbor/harbor#16160]
Can someone please advise on a way to configure a longer timeout for image scanning?
I have a big registry and sometimes I get `context deadline exceeded` when scanning images. Is it possible to configure this using scanner metadata?

**Comment by EvgenyAGRO** [comment]
I'm struggling with the same problem. @danielpacak

**Comment by EvgenyAGRO** [comment]
I'm struggling with the same problem. @danielpacak Do you maybe have a suggestion on how to configure longer timeouts for harbor scanners?

**Comment by wy65701436** [comment]
you can modify the `SCANNER_TRIVY_TIMEOUT` to enlarge it in the trivy-adapter env, @danielpacak please correct me.

**Comment by EvgenyAGRO** [comment]
@wy65701436 Should this work if I wrote a custom scanner and not using trivy? I mean can I just return `SCANNER_TRIVY_TIMEOUT ` with some custom value in my scanner metadata and harbor will treat it as timeout for image scan?

**Comment by wy65701436** [comment]
no, it's only for trivy. All the common behavior are designed in the scanner spec.

**Comment by EvgenyAGRO** [comment]
@wy65701436 I really couldn’t find a clear documentation on that matter, can you please provide a url to documentation of possible settings for a custom scanner?

**Comment by ShabiDabi** [comment]
@wy65701436 @danielpacak, I'm using a custom scanner (not trivy) as well. Can you please share the common behavior scanner spec?

**Comment by heww** [comment]
The default time out for the scan job is 30min, the scanner must return the scan report in 30min otherwise harbor will trust the scan job as failed.

https://github.com/goharbor/harbor/blob/main/src/pkg/scan/job.go#L55 Here is the time out for the scan job.

BTW, what's the size of your image? How long will the scanner take to pull it from the registry?

**Comment by danielpacak** [comment]
As pointed by @wy65701436 for Trivy scanner adapter you can update the timeout by setting the `SCANNER_TRIVY_TIMEOUT` environment variable. It defaults to 5 min, so even if Harbor has 30 min timeout set for a scan job, the adapter service may fail sooner.

As a quick fix / workaround one can set the `SCANNER_TRIVY_TIMEOUT` variable in his deployment descriptor or env file read by Docker compose.

@EvgenyAGRO The [Pluggable Scanners API](https://github.com/goharbor/pluggable-scanner-spec) does not dictate a set of configuration parameters that each scanner adapter must provide. The implementation and documentation is left for security vendor. Some vendors may not even support timeouts. For Trivy all configuration options are listed on https://github.com/aquasecurity/harbor-scanner-trivy#configuration

After all, I think it makes sens to add the `timeout` parameter to the trivy config in `harbor.yml` and similar Helm chart values. WDYT?

```yaml
# Trivy configuration
trivy:
  # ignoreUnfixed The flag to display only fixed vulnerabilities
  ignore_unfixed: false
  # skipUpdate The flag to enable or disable Trivy DB downloads from GitHub
  skip_update: false
  # insecure The flag to skip verifying registry certificate
  insecure: false
  # timeout The duration to wait for scan completion
  timeout: 5m
```
