### ISSUE TITLE
trivy scanner

### ISSUE THREAD

**Issue by rgadeev** [goharbor/harbor#16217]
After the update 2.3.3 to 2.4.1
Scanning errors began to appear:

`analyze error: timeout: context deadline exceeded`

Changed the default value

```
trivy:
  timeout: 5m0s

trivy:
  timeout: 15m0s

```
The scan was completed successfully

Is scanning slower after the update?
