### ISSUE TITLE
Garbage collector stopped working after upgrading from version 1.10 to 2.4.1

### ISSUE THREAD

**Issue by the-papi** [goharbor/harbor#16232]
Hello,
After updating harbor to version 2.4.1 (from version 1.10) my garbage collector is not working. Every time it crashes with a message:
```
2022-01-15T08:44:52Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:264]: failed to delete manifest with v2 API, myproject/myrepo, sha256:c7a2a960429bc4c69f9a49b051388ae8b4656f1b87a0b6053543ecd0f2343edf, http status code: 401, body: 
2022-01-15T08:44:52Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:166]: failed to execute GC job at sweep phase, error: failed to delete manifest with v2 API: myproject/myrepo, sha256:c7a2a960429bc4c69f9a49b051388ae8b4656f1b87a0b6053543ecd0f2343edf: http status code: 401, body:
```

I noticed that the following message appears in the container registry log:
```
registry       | time="2022-01-15T08:44:52.809148326Z" level=warning msg="error authorizing context: basic authentication challenge for realm "harbor-registry-basic-realm": invalid authorization credential" go.version=go1.17.2 http.request.host="registry:5000" http.request.id=76f4d2b3-8363-486f-ba38-b58074667866 http.request.method=GET http.request.remoteaddr="192.168.240.9:56366" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" 
registry       | time="2022-01-15T08:44:52.818576157Z" level=warning msg="error authorizing context: basic authentication challenge for realm "harbor-registry-basic-realm": invalid authorization credential" go.version=go1.17.2 http.request.host="registry:5000" http.request.id=abab8cd2-5f1a-4036-99d3-9122e319e429 http.request.method=HEAD http.request.remoteaddr="192.168.240.9:56368" http.request.uri="/v2/myproject/myrepo/manifests/sha256:c7a2a960429bc4c69f9a49b051388ae8b4656f1b87a0b6053543ecd0f2343edf" http.request.useragent=harbor-registry-client vars.name="myproject/myrepo" vars.reference="sha256:c7a2a960429bc4c69f9a49b051388ae8b4656f1b87a0b6053543ecd0f2343edf"
```

Maybe this is related to #12364, as I noticed that the configuration of `common/config/registries/config.yml` has been changed from:
```
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://harbor.company.com:444/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
```
to:
```
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
```

Pulling & pushing images works as expected.
