### ISSUE TITLE
Secure Metics with Credentials

### ISSUE THREAD

**Issue by Whoop-Whoop** [goharbor/harbor#16253]
In addition to #16252.

Please add an option to protect the metrics e.g. by Basic Authentication.

Suggestions:
harbor.yml
```
...
metric:
  enabled: true
  port: 8080
  path: /metrics
  auth:
    basicauth: /path-to-authfile/myusers.htpasswd
...
```
