### ISSUE TITLE
Secure Metics with SSL

### ISSUE THREAD

**Issue by Whoop-Whoop** [goharbor/harbor#16252]
There were already two issues (#13991 and #13992) for this topic, but both are closed.

Please add an option to harbor.yml (in section metric) to enable ssl.

Suggestions:
harbor.yml
```
...
metric:
  enabled: true
  port: 9090
  path: /metrics
  ssl: true
...
```

nginx.conf
```
...
    listen 9090 ssl;
    ssl_certificate /etc/cert/server.crt;
    ssl_certificate_key /etc/cert/server.key;
...
```
