### ISSUE TITLE
Add tooltip for LDAP group settings

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#16271]
It seems that many users misconfigured the LDAP group settings.

<img width="653" alt="Screen Shot 2022-01-24 at 3 56 20 PM" src="https://user-images.githubusercontent.com/2696760/150743473-55e369e8-cd95-4106-9d08-4c2e43f69321.png">

The tool tip for `LDAP group base dn`, `LDAP group filter`, `LDAP group gid`, `LDAP group membership` should add:  
```
This field cannot be empty if you need to enable the LDAP group related feature.
```
The `LDAP scope` should be `LDAP group search scope`
The `LDAP group ` the tool tips should be 
```
LDAP Group Filter: The filter to search for LDAP/AD groups. for OpenLDAP: objectclass=groupOfNames. for Active Directory: objectclass=group. This field cannot be empty if you need the LDAP group-related feature.
```

**Comment by bad2cat** [comment]
'''
 apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
'''

**Comment by bad2cat** [comment]
```
apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
```
