### ISSUE TITLE
GC doesn't clean up blobs if a repo is deleted and a new one with the same name is recreated.

### ISSUE THREAD

**Issue by ikogan** [goharbor/harbor#16402]
**Expected behavior and actual behavior:**
I had a proxy cache project using an endpoint of type "Quay.io" for Quay.io.. Since I don't have any actual images of my own on Quay, I decided to switch it to the more generic Docker Registry endpoint type. I deleted all the repos in my quay.io project, then deleted the project. I did not trigger a GC. I then created a new repo with the same name using the new endpoint. As expected, the new project had 0 repositories and 0 quota usage.

I then issued a pull for the images I would like to cache from Quay and yet none of them appeared in my new project. I'm still able to pull those images from this new project despite none of them actually being in that project according to the UI. On disk, there don't seem to be any manifests for these repos:

```
harbor [ /storage/docker/registry/v2/repositories/quay.io ]$ find . -iname '*manifests*'
./bitnami/sealed-secrets-controller/_manifests
./oauth2-proxy/oauth2-proxy/_manifests
./jetstack/cert-manager-cainjector/_manifests
./jetstack/cert-manager-controller/_manifests
./jetstack/cert-manager-webhook/_manifests
./ceph/ceph/_manifests
./cephcsi/cephcsi/_manifests
```

I've ran GC several times and it claims there's nothing to clean up:

```
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:145]: Garbage Collection parameters: [delete_untagged: true, dry_run: false, time_window: 2]
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:155]: start to run gc in job.
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:394]: start to delete untagged artifact (no actually deletion for dry-run mode)
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:415]: end to delete untagged artifact (no actually deletion for dry-run mode)
2022-02-22T16:57:14Z [WARNING] [/jobservice/job/impl/gc/garbage_collection.go:187]: no removed artifacts.
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:203]: no need to execute GC as there is no non referenced artifacts.
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:331]: The GC job actual frees up 0 MB space.
2022-02-22T16:57:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:174]: success to run gc in job.
```

Looking in the database, I can't seem to find any artifact referencing "quay".

**Steps to reproduce the problem:**
In theory:

1. Create a proxy cache endpoint.
2. Create a proxy cache project for that endpoint.
3. Delete the proxy cache project.
4. Delete the proxy cache endpoint.
5. Create a new proxy cache endpoint with the same name.
6. Create a new proxy cache project with the same name.
7. Attempt to pull an image using that proxy cache endpoint.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.1
- docker engine version: 20.10.12
- docker-compose version: None
- kubernetes version: 1.20.14

**Additional context:**

- **Harbor config files:**
```yaml
data:
  _REDIS_URL_CORE: redis://harbor-redis:6379/0?idle_timeout_seconds=30
  _REDIS_URL_REG: redis://harbor-redis:6379/2?idle_timeout_seconds=30
  CHART_CACHE_DRIVER: redis
  CHART_REPOSITORY_URL: http://harbor-chartmuseum
  CONFIG_PATH: /etc/core/app.conf
  CORE_LOCAL_URL: http://127.0.0.1:8080
  CORE_URL: http://harbor-core:80
  DATABASE_TYPE: postgresql
  EXT_ENDPOINT: https://registry.kube.mydomain.private
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  JOBSERVICE_URL: http://harbor-jobservice
  LOG_LEVEL: info
  NO_PROXY: harbor-core,harbor-jobservice,harbor-database,harbor-chartmuseum,harbor-notary-server,harbor-notary-signer,harbor-registry,harbor-portal,harbor-trivy,harbor-exporter,127.0.0.1,localhost,.local,.internal
  NOTARY_URL: http://harbor-notary-server:4443
  PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry
  PORT: "8080"
  PORTAL_URL: http://harbor-portal
  POSTGRESQL_DATABASE: registry
  POSTGRESQL_HOST: harbor-database
  POSTGRESQL_MAX_IDLE_CONNS: "100"
  POSTGRESQL_MAX_OPEN_CONNS: "900"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_SSLMODE: disable
  POSTGRESQL_USERNAME: postgres
  REGISTRY_CONTROLLER_URL: http://harbor-registry:8080
  REGISTRY_CREDENTIAL_USERNAME: harbor_registry_user
  REGISTRY_STORAGE_PROVIDER_NAME: filesystem
  REGISTRY_URL: http://harbor-registry:5000
  TOKEN_SERVICE_URL: http://harbor-core:80/service/token
  TRIVY_ADAPTER_URL: http://harbor-trivy:8080
  WITH_CHARTMUSEUM: "true"
  WITH_NOTARY: "true"
  WITH_TRIVY: "true"
  app.conf: |
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8080
```

```yaml
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /storage
      cache:
        layerinfo: redis
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
      redirect:
        disable: false
    redis:
      addr: harbor-redis:6379
      db: 2
      readtimeout: 10s
      writetimeout: 10s
      dialtimeout: 10s
      pool:
        maxidle: 100
        maxactive: 500
        idletimeout: 60s
    http:
      addr: :5000
      relativeurls: false
      # set via environment variable
      # secret: placeholder
      debug:
        addr: localhost:5001
    auth:
      htpasswd:
        realm: harbor-registry-basic-realm
        path: /etc/registry/passwd
    validation:
      disabled: true
    compatibility:
      schema1:
        enabled: true
  ctl-config.yml: |
    ---
    protocol: "http"
    port: 8080
    log_level: info
    registry_config: "/etc/registry/config.yml"
```

- **Log files:** When pulling from the registry, I see the following:

```
 [WARNING] [/pkg/registry/auth/bearer/cache.go:99]: token issued time is empty, return expired to refresh token
 [WARNING] [/server/middleware/repoproxy/proxy.go:143]: Artifact: quay.io/bitnami/sealed-secrets-controller:v0.17.1, digest: is not found in proxy cache, fetch it from remote repo
```

In other projects, I only see the second warning.
