### ISSUE TITLE
`dns_search` in `docker-compose.yml` blocks the internet connection on harbor containers

### ISSUE THREAD

**Issue by FeryET** [goharbor/harbor#16426]
The problem is explained [here](https://github.com/StackStorm/st2-docker/issues/231#issuecomment-983990107).

My docker-compose version: `Docker Compose version v2.2.3`

My docker version:
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I could not access to my s3 using this configuration. 
```
storage_service:
  s3:
    accesskey: xxxxxxx
    secretkey: xxxxxxx
    bucket: some-docker-registry
    regionendpoint: s3.ir-thr-at1.arvanstorage.com
    region: default
    v4auth: false
    chunksize: 5242880
    rootdirectory: /
```

Upon inspecting the running docker containers, I found out that `curl -v s3.ir-thr-at1.arvanstorage.com` was unsuccessful in getting any info and timed out in both `registry` and `registryctl` containers. 

Only after removing `dns_search: .`  lines in `docker-compose.yml` I could curl and therefore use my s3 bucket.

I don't know what might cause this issue and I don't know if it's a bug or I have misconfigured my harbor instance, so I labelled it as a bug.
