### ISSUE TITLE
Pushes to s3 storage with self signed certs fail with 500 error even with skipverify true

### ISSUE THREAD

**Issue by shawnparr** [goharbor/harbor#16437]
I was able to get Harbor working with a local minio instance when no SSL certs were in use. I created a set of certificates for minio and Harbor and now pushes fail with a 500 error after successfully pushing layers (which are stored successfully in the bucket).

When pushing I get the following:
```
The push refers to repository [redacted]
2ac8eb3c015d: Pushed 
a40635739389: Pushed 
66be9569dea8: Pushed  
436f85ca6ecf: Pushed  
580d8efcd002: Pushed  
82ea5fcc08b0: Pushed  
12d9d2ff0cce: Pushed  
45b14f916575: Pushed  
6c00b3fc4f3d: Pushed  
f5ab093dc107: Pushed  
e38eaa78f9f8: Pushed  
received unexpected HTTP status: 500 Internal Server Error
```

I'm using the online installer and in the logs for the harbor-core container I'm getting items like this when pushing:
```
2022-02-28T21:46:56Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: Get \"https://localminio.lan:9000/harbor-registry/docker/registry/v2/blobs/sha256/5a/5aa04c767864f240e01d11d88dc4cd65d435c6c453a3fd4e8a27557b13fac9a2/data?X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=bucketname%2F20220228%2Fus-east-1%2Fs3%2Faws4_request\u0026X-Amz-Date=20220228T214656Z\u0026X-Amz-Expires=1200\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Signature=93a4c7ffb42c624fb283c6cfb73a768bf29f64c8df49fb046a91b39796de759e\": x509: certificate signed by unknown authority"}]} 
```

The storage section of harbor.yml:
```
storage_service:
  s3:
    accesskey: redacted
    secretkey: redacted
    region: us-east-1
    regionendpoint: https://localminio.lan:9000
    bucket: bucket name
    encrypt: false
    secure: false
    skipverify: true
    ca_bundle: /path/harbor/certs/wildcard.crt
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
```

I've tried both with and without 

Seems unusual that the harbor instance would ignore the trust issues with the self signed cert to upload all the files, then fail on what appears to be verifying that they were uploaded.
