### ISSUE TITLE
Connection refused on port 1514

### ISSUE THREAD

**Issue by jordaniac89** [goharbor/harbor#16669]
Trying to run Harbor on an M1 mac and when running the install.sh, receive the following output:

```
[Step 4]: starting Harbor ...
[+] Running 5/10
 ⠿ Network harbor_harbor        Created                                                                                                                                                                0.0s
 ⠿ Container harbor-log         Started                                                                                                                                                                0.7s
 ⠿ Container redis              Starting                                                                                                                                                               4.8s
 ⠿ Container harbor-portal      Starting                                                                                                                                                               4.8s
 ⠿ Container registryctl        Starting                                                                                                                                                               4.8s
 ⠿ Container registry           Starting                                                                                                                                                               4.8s
 ⠿ Container harbor-db          Starting                                                                                                                                                               4.8s
 ⠿ Container harbor-core        Created                                                                                                                                                                0.1s
 ⠿ Container harbor-jobservice  Created                                                                                                                                                                0.1s
 ⠿ Container nginx              Created                                                                                                                                                                0.1s
Error response from daemon: failed to initialize logging driver: dial tcp [::1]:1514: connect: connection refused
```

port 1514 appears from the docker compose to be the port that the log service is listening on.

Troubleshooting attempts:
1) run the script as sudo
2) set the `platform: linux/amd64` in the docker-compose and restart the containers, as that was giving me a warning at the start of the install.

When I do a docker-compose ps, I also see harbor-log remains in a restarting state

```
NAME                COMMAND                  SERVICE             STATUS              PORTS
harbor-core         "/harbor/entrypoint.…"   core                created             
harbor-db           "/docker-entrypoint.…"   postgresql          created             
harbor-jobservice   "/harbor/entrypoint.…"   jobservice          created             
harbor-log          "/bin/sh -c /usr/loc…"   log                 restarting          
harbor-portal       "nginx -g 'daemon of…"   portal              created             
nginx               "nginx -g 'daemon of…"   proxy               created             
redis               "redis-server /etc/r…"   redis               created             
registry            "/home/harbor/entryp…"   registry            created             
registryctl         "/home/harbor/start.…"   registryctl         created    
```

when I do a `docker logs harbor-log` I see lots of this type of output

```
chown: changing ownership of '/var/log/docker/wifi.log.0.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.1.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.10.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.2.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.3.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.4.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.5.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.6.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.7.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.8.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker/wifi.log.9.bz2': Operation not permitted
chown: changing ownership of '/var/log/docker': Operation not permitted
```
any help would be appreciated!

**Comment by zyyw** [comment]
have you tried this:
* https://github.com/goharbor/harbor/issues/9382#issuecomment-611915390

**Comment by jordaniac89** [comment]
hi, 
For the first link, I'm a bit new to docker and the instructions aren't very clear. I've tried chmodding and chowning the logs directory that I'm mounting into the logs service but I'm running into the same issue.

I'm also attempting to run this on an M1 mac. Would that cause an issue? I have another AMD based mac and the installation works without a hitch.

**Comment by jordaniac89** [comment]
FYI, needed to change the log service to run as root user.  

```
services:
  log:
    image: goharbor/harbor-log:v2.4.2
    container_name: harbor-log
    restart: always
    user: root
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /Users/jordanmiles/Desktop/logs//:/var/log/docker/:z
      - type: bind
        source: ./common/config/log/logrotate.conf
        target: /etc/logrotate.d/logrotate.conf
      - type: bind
        source: ./common/config/log/rsyslog_docker.conf
        target: /etc/rsyslog.d/rsyslog_docker.conf
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor
```
Not sure why chown wasn't working.
