### ISSUE TITLE
Provide the option with_tag when copying artifact

### ISSUE THREAD

**Issue by wayne-cheng** [goharbor/harbor#16675]
**Is your feature request related to a problem? Please describe.**
When you copy an artifact, the target artifact always have all the tags from the source artifact.
These tags may be redundant, and it will replace the already existing tags of the target respository.

**Describe the solution you'd like**
I hope there have a query parameter for the copy artifact API , it can control the api not to carry tag.
```yaml
# /projects/{project_name}/repositories/{repository_name}/artifacts
# post method ...
       - name: with_tag
          in: query
          description: Specify whether the tags are carried when copy the artifact.
          type: boolean
          required: false
          default: true
```

**Describe the development plan you've considered**
I'd like submit a PR to solve this, since I have modified the api in my local environment and it works well.
