### ISSUE TITLE
Database connection issue between Harbor and PostgreSQL

### ISSUE THREAD

**Issue by AlexBarth13** [goharbor/harbor#16808]
What can we help you?

Hello all,

Currently we are facing an issue when we want to connect from the Harbor application to our PostgreSQL databases for Harbor, Notary Signer and Notary Server.

This is our configuration:

```
external_database:
  harbor:
    host: <SERVER_NAME>
    port: 20001
    db_name: <INSTANCE_NAME>
    username: 
    password:
    ssl_mode: disable
    max_idle_conns: 100
    max_open_conns: 100
  notary_signer:
    host: <SERVER_NAME>
    port: 20003
    db_name: <INSTANCE_NAME>
    username: 
    password: 
    ssl_mode: disable
  notary_server:
    host: <SERVER_NAME>
    port: 20004
    db_name: <INSTANCE_NAME>
    username: 
    password:
```

This is the error message, which we will get:

For Harbor:
```
2022-04-18 15:31:50 CEST [6383-1] (00000) [unknown]@[unknown] ([unknown]) LOG: connection received: host=[local]
2022-04-18 15:31:50 CEST [6383-2] (00000) <USER>@<INSTANCE_NAME> ([unknown]) LOG: connection authorized: user=<USER> database=<INSTANCE_NAME>
2022-04-18 15:31:50 CEST [6383-3] (00000) <USER>@<INSTANCE_NAME> (psql) LOG: disconnection: session time: 0:00:00.004 user=<USER> database=<INSTANCE_NAME> host=[local]
```

For Notary signer:
```
2022-04-18 15:27:44 CEST [5384-1] (00000) [unknown]@[unknown] ([unknown]) LOG: connection received: host=[local]
2022-04-18 15:27:44 CEST [5384-2] (28000) postgres@postgres ([unknown]) FATAL: no pg_hba.conf entry for host "[local]", user "postgres", database "postgres", SSL off
```

For Notary server:
```
2022-04-18 15:30:06 CEST [5968-1] (00000) [unknown]@[unknown] ([unknown]) LOG: connection received: host=[local]
2022-04-18 15:30:06 CEST [5968-2] (28000) postgres@postgres ([unknown]) FATAL: no pg_hba.conf entry for host "[local]", user "postgres", database "postgres", SSL off
```

Can you help us to find the issue or do you have any hint?

Thanks a lot!
<br ><br >
Alexander Barth (alexander.barth@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
