### ISSUE TITLE
Invalid default credentials behind native nginx proxy 

### ISSUE THREAD

**Issue by pthoelken** [goharbor/harbor#16844]
- Debian Server 11 with NGiNX installed as proxy_pass
- Harbor with the following config fresh installed

Harbor Config

```
hostname: reg.foo.bar
http:
  port: 8181
https:
  port: 4433
  certificate: /etc/ssl/certs/reg.foo.bar.crt
  private_key: /etc/ssl/certs/reg.foo.bar.key
external_url: https://reg.foo.bar:4433
harbor_admin_password: Harbor12345

... and more ...
```

Native NGiNXConfig

```
server {

        listen                          443 ssl;

        server_name                     reg.foo.bar;

        ssl_certificate                 /etc/ssl/certs/reg.foo.bar.crt;
        ssl_certificate_key             /etc/ssl/certs/reg.foo.bar.key;
        ssl_session_timeout            5m;
        ssl_protocols                  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers                    ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
        ssl_prefer_server_ciphers      on;

        location / {
                proxy_set_header  Host              $http_host;
                proxy_set_header  X-Real-IP         $remote_addr;
                proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto $scheme;
                proxy_buffering off;
proxy_request_buffering off;

                proxy_pass https://reg.foo.bar:4433/;

        }

}

```

I also tried with `proxy_pass https://127.0.0.1:4433/;` without success. Any ideas why I've got "invalid credentials" every time on login screen from Harbor? 

And also it takes a long time to load in web browser. 

The sign up screen print me this error, I think this is normal chars: 
![image](https://user-images.githubusercontent.com/12643853/167870586-87368172-b657-4e33-8abe-b703f0886a2e.png)
