### ISSUE TITLE
After upgrade 2.2.2 → 2.3.5 → 2.5.1 all signatures gone

### ISSUE THREAD

**Issue by axi92** [goharbor/harbor#16933]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I had valid trust signatures with version 2.2.2. After the upgrade to 2.5.1 all signatures are gone in the UI.

**Steps to reproduce the problem:**
Upgrade from 2.2.2 to 2.3.5 to 2.5.1

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.1
- docker engine version: Docker version 20.10.16, build aa7e414
- docker-compose version: docker-compose version 1.29.2, build 5becea4c

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

harbor.yml
```
hostname: domain.com
http:
  port: 80
https:
  port: 443
  certificate: /data/cert/server.crt
  private_key: /data/cert/server.key
harbor_admin_password: <password>
database:
  password: <password>
  max_idle_conns: 100
  max_open_conns: 900
data_volume: /data
storage_service:
  ca_bundle: 
trivy:
  ignore_unfixed: false
  timeout: 5m0s
  skip_update: false
  offline_scan: false
  insecure: false
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: debug
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.5.0
proxy:
  http_proxy: 
  https_proxy: 
  no_proxy: 
  components:
    - core
    - jobservice
    - trivy
upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false
```
