### ISSUE TITLE
Harbor nginx not picking up new certificate location passed in by harbor.yml after upgrade

### ISSUE THREAD

**Issue by cdestouni-fmp** [goharbor/harbor#16982]
I was upgrading harbor from v1.7.1 to the latest v2.5.1 incrementally. I saw that the certificate used for https was incorrect after the deployment. I updated the path in the `harbor.yml` to point to the new certificate location in the relevant section of the file.

```
https:
  # https port for harbor, default is 443
  port: 443
  # The path of cert and key files for nginx
  certificate: "{{ harbor.ssl.certpath }}" 
  private_key: "{{ harbor.ssl.keyPath }}" 
```

Unfortunately it was still using the old location for the cert and the key `domain.crt` and `domain.key`. My workaround was to rename/move the new certificate and key to the old certificate location and all was fine. Is this a bug? Or because we are upgrading from an older version, is it retaining the cert location somewhere in the database?

P.s. We followed this official [guide](https://goharbor.io/docs/2.5.0/install-config/configure-https/) to configure the new certificate.
