### ISSUE TITLE
Error "MANIFEST_UNKNOWN" for already existing images after Harbor upgrade from v2.2.1 to v2.3.1

### ISSUE THREAD

**Issue by hikkart** [goharbor/harbor#16992]
Hello All,

I am getting following error after upgrading Harbor from `v2.2.1` to `v2.3.1` for already available images in Harbor repository.

Error output for each docker image in repo:
```
http status code: 404, body: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"apps/test-image","Revision":"sha256:7f32cfd2faf90eaceee835ecb8292b48243e64ab96117ec28f98a11f2c0ba67e"}}]}
```
Hence docker pull fails for all the images in repo.

Earlier Version:
```
CHART: harbor-1.6.1   
APP VERSION: 2.2.1
```
Upgraded Version:
```
CHART: harbor-1.7.1   
APP VERSION: 2.3.1
```

Please note that I am using external `bitnami postgresql-ha` helm with postgresql version `v11.14.0` 

In harbor values.yaml:
```
  external:
    host: "postgresql-harbor-pgpool.harbor-space.svc.cluster.local"
    port: "5432"
    username: "postgres"
```

Any help would be much appreciated.
`Thanks in advance`.
