### ISSUE TITLE
Cannot manage helm using http

### ISSUE THREAD

**Issue by marksugar** [goharbor/harbor#17086]
I installed version 2.5.0 offline using docker-compose for testing

As usual, I configured
````
"insecure-registries": [
  "http://harbor.test.com"
]
````
I am able to push and pull normally
````
# docker push harbor.test.com/base/kibana:7.13.4
The push refers to repository [harbor.test.com/base/kibana]
55dd952b63e0: Pushed
67c753c37285: Pushed
0929950056b7: Pushed
3d446c9ecc40: Pushed
ca64b9db8a7a: Pushed
4ebaec6c2ac7: Pushed
551ca34bfeec: Pushed
cb64b1b81831: Pushed
12c24557e3d9: Pushed
5405ed9d9e33: Pushed
722818d8cb7c: Pushed
6af82b44842d: Pushed
2653d992f4ef: Pushed
7.13.4: digest: sha256:c166109de55cb3374328f4b3301b77b0cf60af1671ed09438ad0fb670fec27a1 size: 3037
````
- helm

I can't use http normally in helm

helm configuration file
` egrep -v "^$|^#|^ #|^ #|^ #" harbor.yml `
````
hostname: harbor.test.com
http:
  port: 80
harbor_admin_password: Harbor12345
database:
  password: root123
  max_idle_conns: 100
  max_open_conns: 900
data_volume: /data
trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  insecure: false
jobservice:
  max_job_workers: 10
notification:
  webhook_job_max_retry: 10
chart:
  absolute_url: disabled
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.5.0
proxy:
  http_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy
upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false
````
I am trying to log into helm
`helm registry login harbor.test.com --insecure`
````
# helm registry login harbor.test.com --insecure
Username: admin
Password:
INFO[0004] Error logging in to endpoint, trying next endpoint error="Get \"https://harbor.test.com/v2/\": dial tcp 172.16.100.54:443: connect: connection refused"
Login Succeeded
````
returns a
````
INFO[0004] Error logging in to endpoint, trying next endpoint error="Get \"https://harbor.test.com/v2/\": dial tcp 172.16.100.54:443: connect: connection refused"
````

push
````
# helm push redis-10.5.7.tgz oci://harbor.test.com/helm-test
Error: failed to do request: Head "https://harbor.test.com/v2/helm-test/redis/blobs/sha256:24aad6bd4614c2ffcbd421cf105cc88b23e8aec56fb2130d5c7f57219958a130": dial tcp 172.16.100.54:443: connect: connection refused
````

This is just an intranet test environment, how can I use http to upload and use helm

I don't know where the configuration is wrong

thanks
