### ISSUE TITLE
Can not push image to Harbor running on k8s

### ISSUE THREAD

**Issue by marco210** [goharbor/harbor#17091]
What can we help you?
```
#docker push harbor.test.com/library/myubuntu:v1 
The push refers to repository [harbor.test.com/library/myubuntu]
a790f937a6ae: Retrying in 1 second
received unexpected HTTP status: 503 Service Unavailable
```

I deployed Harbor by using yaml file of  Helm's template. I use http to access and login to harbor. My domain `harbor.test.com`. I used ingress nginx. I login to Harbor sucessed but  push image error.
- Login success: 
```
# docker login harbor.test.com -u robot\$library+bot1
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

- Log registry: 
```
10.0.0.51 - - [28/Jun/2022:08:41:01 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.23"
time="2022-06-28T08:41:02.05567212Z" level=info msg="authorized request" go.version=go1.17.7 http.request.host=harbor.test.com http.request.id=c24f3300-4748-4d17-8a86-94a23fe89327 http.request.method=GET http.request.remoteaddr=192.168.235.192 http.request.uri="/v2/" http.request.useragent="docker/20.10.12 go/go1.16.2 git-commit/20.10.12-0ubuntu220.04.1 kernel/5.4.0-120-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12 \(linux\))"
time="2022-06-28T08:41:02.055884803Z" level=info msg="response completed" go.version=go1.17.7 http.request.host=harbor.test.com http.request.id=c24f3300-4748-4d17-8a86-94a23fe89327 http.request.method=GET http.request.remoteaddr=192.168.235.192 http.request.uri="/v2/" http.request.useragent="docker/20.10.12 go/go1.16.2 git-commit/20.10.12-0ubuntu2-20.04.1 kernel/5.4.0-120-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=83.431553ms http.response.status=200 http.response.written=2
192.168.213.122 - - [28/Jun/2022:08:41:01 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/20.10.12 go/go1.16.2 git-commit/20.10.12-0ubuntu2-20.04.1 kernel/5.4.0-120-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.12 \\(linux\\))"
time="2022-06-28T08:41:02.736254121Z" level=info msg="PurgeUploads starting: olderThan=2022-06-21 08:41:02.736140939 +0000 UTC m=-602219.963162544, actuallyDelete=true"
time="2022-06-28T08:41:02.788162428Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1"
time="2022-06-28T08:41:02.78820571Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.17.7 instance.id=0271702b-8112-4352-88d5-181a44cd1a2d service=registry version=v2.8.0.m
192.168.213.122 - - [28/Jun/2022:08:41:09 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1" 
```

-  /etc/docker/daemon.json
```{
  "insecure-registries" : ["harbor.test.com"],
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
```
- Docker version `20.10.12` 
- Harbor version `2.5.1`

**Comment by Vad1mo** [comment]
What values did you set in Helm?

Make sure you set the externalURL with the "http://" schema.

**Comment by marco210** [comment]
> What values did you set in Helm?
> 
> Make sure you set the externalURL with the "http://" schema.

Hi, Below is my core configmap: 
```
data:
  app.conf: |+
    appname = Harbor
    runmode = prod
    enablegzip = true

    [prod]
    httpport = 8080
  PORT: "8080"
  DATABASE_TYPE: "postgresql"
  POSTGRESQL_HOST: "release-name-harbor-database"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_USERNAME: "postgres"
  POSTGRESQL_DATABASE: "registry"
  POSTGRESQL_SSLMODE: "disable"
  POSTGRESQL_MAX_IDLE_CONNS: "100"
  POSTGRESQL_MAX_OPEN_CONNS: "900"
  EXT_ENDPOINT: "http://harbor.test.com"
  CORE_URL: "http://release-name-harbor-core:80"
  JOBSERVICE_URL: "http://release-name-harbor-jobservice"
  REGISTRY_URL: "http://release-name-harbor-registry:5000"
  TOKEN_SERVICE_URL: "http://release-name-harbor-core:80/service/token"
  WITH_NOTARY: "true"
  NOTARY_URL: "http://release-name-harbor-notary-server:4443"
  CORE_LOCAL_URL: "http://127.0.0.1:8080"
  WITH_TRIVY: "true"
  TRIVY_ADAPTER_URL: "http://release-name-harbor-trivy:8080"
  REGISTRY_STORAGE_PROVIDER_NAME: "filesystem"
  WITH_CHARTMUSEUM: "true"
  CHART_REPOSITORY_URL: "http://release-name-harbor-chartmuseum"
  LOG_LEVEL: "info"
  CONFIG_PATH: "/etc/core/app.conf"
  CHART_CACHE_DRIVER: "redis"
  _REDIS_URL_CORE: "redis://release-name-harbor-redis:6379/0?idle_timeout_seconds=30"
  _REDIS_URL_REG: "redis://release-name-harbor-redis:6379/2?idle_timeout_seconds=30"
  PORTAL_URL: "http://release-name-harbor-portal"
  REGISTRY_CONTROLLER_URL: "http://release-name-harbor-registry:8080"
  REGISTRY_CREDENTIAL_USERNAME: "harbor_registry_user"
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: "release-name-harbor-core,release-name-harbor-jobservice,release-name-harbor-database,release-name-harbor-chartmuseum,release-name-harbor-notary-server,release-name-harbor-notary-signer,release-name-harbor-registry,release-name-harbor-portal,release-name-harbor-trivy,release-name-harbor-exporter,127.0.0.1,localhost,.local,.internal"
  PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry"
```
