### ISSUE TITLE
Harbor with External postgres database connectivity 

### ISSUE THREAD

**Issue by rakeshreddyrg09** [goharbor/harbor#17226]
Hello Team,
I am trying to install harbor with external postgres  as my database (https://access.crunchydata.com/documentation/postgres-operator/latest/quickstart/), but the external DB details are dynamic for me like username, password & host.  
so I tried below format, but it didn't work.
```
external:
    host: "harbor-primary.ns.svc"
    port: "5432"
    username: "harboruser"
    password: 
      valueFrom:
        secretKeyRef:
          name: harbor-harboruser
          key: password
    coreDatabase: "registry"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"
```
or can i pass the details as ENV of core or somewhere so that it can fetch from their?
can anyone help me out here.
Thank you.
