### ISSUE TITLE
Registry become 503 after some 200 health check in k8s

### ISSUE THREAD

**Issue by Ives66** [goharbor/harbor#17388]
Hi
I deploy my harbor through harbor-operator in k8s. When I want to upgrade it from v2.2.4 to v2.5.3, I meet some problem.
The registry pod may start healthily at first, but after some second it become 503. 

> time="2022-08-11T13:02:54.670894365Z" level=info msg="providing prometheus metrics on /metrics" 
> time="2022-08-11T13:02:54.670966604Z" level=info msg="listening on [::]:5000" go.version=go1.17.13 instance.id=bc00bdd8-805e-4c08-9ca4-10304319caf8 version=v2.8.0.m 
> 172.20.128.193 - - [11/Aug/2022:13:02:58 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.20"
> 172.20.128.250 - - [11/Aug/2022:13:02:59 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
> 172.20.128.100 - - [11/Aug/2022:13:03:00 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
> 172.20.128.193 - - [11/Aug/2022:13:03:04 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.20"
> 172.20.128.193 - - [11/Aug/2022:13:03:08 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.20"
> 172.20.128.250 - - [11/Aug/2022:13:03:09 +0000] "GET / HTTP/1.1" 503 125 "" "Go-http-client/1.1"
> 172.20.128.100 - - [11/Aug/2022:13:03:10 +0000] "GET / HTTP/1.1" 503 125 "" "Go-http-client/1.1"
> 172.20.128.193 - - [11/Aug/2022:13:03:14 +0000] "GET / HTTP/1.1" 503 125 "" "kube-probe/1.20"
> 172.20.128.193 - - [11/Aug/2022:13:03:18 +0000] "GET / HTTP/1.1" 503 125 "" "kube-probe/1.20"
> 172.20.128.250 - - [11/Aug/2022:13:03:19 +0000] "GET / HTTP/1.1" 503 125 "" "Go-http-client/1.1"

I tried docker push on it when it healthy, and it said

> time="2022-08-12T01:30:25.528696908Z" level=info msg="authorized request" go.version=go1.17.13 http.request.id=a2372779-fc0d-4065-9346-4d3e393ff1d6 http.request.method=POST http.request.remoteaddr=10.255.136.230 http.request.uri="/v2/test/ore/blobs/uploads/" http.request.useragent="docker/20.10.17 go/go1.17.11 git-commit/a89b842 kernel/5.10.104-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/20.10.17 \(darwin\))" vars.name="test/ore" 
> time="2022-08-12T01:30:25.530887991Z" level=info msg="authorized request" go.version=go1.17.13 http.request.id=49a5ec52-6139-48dd-848d-6d16f6d7c8b9 http.request.method=POST http.request.remoteaddr=10.255.136.230 http.request.uri="/v2/test/ore/blobs/uploads/" http.request.useragent="docker/20.10.17 go/go1.17.11 git-commit/a89b842 kernel/5.10.104-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/20.10.17 \(darwin\))" vars.name="test/ore" 
> time="2022-08-12T01:30:25.531777347Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="**s3aws: InvalidPathAccess: Forbidden path to access server.**
>  status code: 403, request id: 64f548f5ad317b1862f5ad31-ac16d9fb, host id: 64f548f5ad317b1862f5ad31-ac16d9fb" err.message="unknown error" go.version=go1.17.13 http.request.id=a2372779-fc0d-4065-9346-4d3e393ff1d6 http.request.method=POST http.request.remoteaddr=10.255.136.230 http.request.uri="/v2/test/ore/blobs/uploads/" http.request.useragent="docker/20.10.17 go/go1.17.11 git-commit/a89b842 kernel/5.10.104-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/20.10.17 \(darwin\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=258.242159ms http.response.status=500 http.response.written=123 vars.name="test/ore" 

I check the harbor.yml, it seems that nothing wrong in s3, and it does work in v2.2.4 after I change the image again.

````
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: "redis"
  maintenance:
    uploadPurging:
      enabled: true
      age: 168h0m0s
      interval: 24h0m0s
      dryRun: false
    readOnly:
      enabled: false
  redirect: 
    disable: true
  s3:
    region: "xxxx"
    bucket: "xxxxxxxxxxxxxxxxxxxxxxx"
    encrypt: false
    skipverify: true
    secure: true
    v4auth: true
    chunksize: 10485760
    storageclass: "STANDARD"
    accesskey: "xxxxxxxxxxxxx"
    secretkey: "xxxxxxxxxxxx"
    regionendpoint: "xxxxxxxxxxxxxxxxx"
````
