### ISSUE TITLE
Greater control over Image pull/push authorization

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#17490]
**Is your feature request related to a problem? Please describe.**
In harbor there are Private and Public repositories. Recently we wanted to have a private repository, but still allowing unauthenticated users to download images from this private repositories if they belong to the organization network. This requirement is not met by The private repository only and having the repository set to public is undesirable.

**Describe the solution you'd like**
We would like to have an option to allow one or more IP ranges to read from a private repository.

**Work around**
Currently, the work around we found for this was to restrict the access to the /v2/<project> by creating an additional Ingress object along side the harbor helm deployed one. Here an example of the manifest:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.harbor.expose.ingress.annotations }}
      {{- toYaml .Values.harbor.expose.ingress.annotations | nindent 4  }}
    {{- end }}
    nginx.ingress.kubernetes.io/whitelist-source-range: >-
      IP1,
      IP2,
      [etc]
  name: harbor-{{- $.Release.Namespace -}}-protected-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $tls.enabled }}
  tls:
  - secretName: {{ template "harbor.tlsCoreSecretForIngress" . }}
    {{- if $ingress.hosts.core }}
    hosts:
    - {{ $ingress.hosts.core }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ template "harbor.core" . }}
            port:
              number: 80
        path: /v2/<repo1>
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ template "harbor.core" . }}
            port:
              number: 80
        path: /v2/<repo2>
        pathType: ImplementationSpecific
```
