### ISSUE TITLE
How does Docker connect to a harbor deployed at Helm

### ISSUE THREAD

**Issue by meng-yu-github** [goharbor/harbor#17526]
I used Helm Deployment Harbor, and the UI page worked fine, but couldn't connect using Docker.
The tls.key and tls.crt I use are harbor-helm-core in Secret in K8S.
The ca. crt is the Registry Root Certificate downloaded from System Settings on the UI page.
The tls.cert is converted from TLs.crt.

**Expect the result**
Docker can connect successfully

**Error info**
```bash
docker login 82.xxx.xxx.195:30003 -u admin
Password:
Error response from daemon: Get https://82.xxx.xxx.195:30003/v2/: x509: cannot validate certificate for 82.xxx.xxx.195 because it doesn't contain any IP SANs
```

**Docker certificate directory structure**
```bash
/etc/docker
├── certs.d
    └── 82.xxx.xxx.195
        ├── 82.xxx.xxx.195.cert
        ├── 82.xxx.xxx.195.key
        └── ca.crt
```

**pod info**
```bash
kubectl get pod -n harbor-test
NAME                                         READY   STATUS    RESTARTS   AGE
harbor-helm-chartmuseum-66c9596b86-cwv8h     1/1     Running   0          7m19s
harbor-helm-core-5b5b98b76c-86tlg            1/1     Running   0          7m19s
harbor-helm-database-0                       1/1     Running   0          7m19s
harbor-helm-jobservice-566c698bd6-tzkfb      1/1     Running   0          7m19s
harbor-helm-nginx-75fc4667fd-mh6vj           1/1     Running   0          7m20s
harbor-helm-notary-server-6cf668f98b-2kdth   1/1     Running   0          7m20s
harbor-helm-notary-signer-66bdc45bc-9xnbj    1/1     Running   0          7m19s
harbor-helm-portal-75c4ddc5-cbvdc            1/1     Running   0          7m20s
harbor-helm-redis-0                          1/1     Running   0          7m19s
harbor-helm-registry-85cfc98b48-bd5wc        2/2     Running   0          7m19s
harbor-helm-trivy-0                          1/1     Running   0          7m19s
```
**value.yaml info**
```yaml
expose:
  type: nodePort
  tls:
    enabled: true
    certSource: auto
    auto:
      commonName: "harbor-cert"
    secret:
      secretName: ""
      notarySecretName: ""
nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002
      https:
        port: 443
        nodePort: 30003
      notary:
        port: 4443
        nodePort: 30004
externalURL: https://82.xxx.xxx.195
internalTLS:
  enabled: false
  certSource: "auto"
  trustCa: ""
  core:
    secretName: ""
    crt: ""
    key: ""
  jobservice:
    secretName: ""
    crt: ""
    key: ""
  registry:
    secretName: ""
    crt: ""
    key: ""

 ...

```

**Comment by meng-yu-github** [comment]
**helm version**
```bash
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
```

**harbor image**
```bash
docker images | grep harbor
goharbor/chartmuseum-photon                                                   v2.5.3                788b207156ad   2 months ago    225MB
goharbor/redis-photon                                                         v2.5.3                5dc5331f3de8   2 months ago    154MB
goharbor/trivy-adapter-photon                                                 v2.5.3                27798821348a   2 months ago    251MB
goharbor/notary-server-photon                                                 v2.5.3                c686413b72ce   2 months ago    112MB
goharbor/notary-signer-photon                                                 v2.5.3                a3bc1def3f94   2 months ago    109MB
goharbor/harbor-registryctl                                                   v2.5.3                942de6829d43   2 months ago    136MB
goharbor/registry-photon                                                      v2.5.3                fb1278854b91   2 months ago    77.9MB
goharbor/nginx-photon                                                         v2.5.3                91877cbc147a   2 months ago    44.3MB
goharbor/harbor-jobservice                                                    v2.5.3                75e6a7496590   2 months ago    227MB
goharbor/harbor-core                                                          v2.5.3                93a775677473   2 months ago    203MB
goharbor/harbor-portal                                                        v2.5.3                d78f9bbad9ee   2 months ago    52.6MB
goharbor/harbor-db                                                            v2.5.3                bd50ae1eccdf   2 months ago    224MB
```

**Comment by chlins** [comment]
You could try to change the `externalURL: https://82.xxx.xxx.195` to `https://82.xxx.xxx.195:30003`.

**Comment by meng-yu-github** [comment]
@chlins thank you.

By using the homebrew certificate and changing externalURL,  now can logged in.

**Changes of yaml**
```yaml
expose:
  type: nodePort
  tls:
    enabled: true
    certSource: secret
    auto:
      commonName: ""
    secret:
      secretName: "harbor-cert"
      notarySecretName: ""
nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002
      https:
        port: 443
        nodePort: 30003
      notary:
        port: 4443
        nodePort: 30004
externalURL: https://82.xxx.xxx.195:30003
 ...
```
