### ISSUE TITLE
GC log not found when GC fails

### ISSUE THREAD

**Issue by dkulchinsky** [goharbor/harbor#17536]
**Expected behavior and actual behavior:**

GC fails and when trying to get the log we get:

```json
{"errors":[{"code":"NOT_FOUND","message":"{\"code\":10010,\"message\":\"object is not found\",\"details\":\"log entity: 6e0aaeb546660763a8a745dc\"}"}]}
```

sweeper is set to 14 days and we check immediately after the job failed.

**Steps to reproduce the problem:**

Run GC, when it fails click on "logs" link

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.3
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

```
job_loggers:
  - name: "DB"
    level: INFO
    sweeper:
      duration: 14
```

**Comment by chlins** [comment]
Could you check the jobservice logs?

**Comment by dkulchinsky** [comment]
> Could you check the jobservice logs?

I did, and can't find anything of relevance.

unless you can tell me.what to look for? perhaps I'm missing something

**Comment by dkulchinsky** [comment]
@chlins combed through the jobservice logs again and found this:

```
2022-09-14T20:36:56Z [INFO] [/jobservice/worker/cworker/reaper.go:181]: Reaper: mark job 4746d1529505908316d7f391 failed as job is still not finished in 1 day
```

`4746d1529505908316d7f391` is indeed the GC job, as I was seeing this uuid return a 404 when trying to fetch the log:

```
2022-09-15T00:08:44Z [WARNING] [/pkg/joblog/dao/dao.go:51]: no job log founded. Query condition, uuid: 4746d1529505908316d7f391, err: no job log founded

2022-09-15T00:08:44Z [ERROR] [/jobservice/api/handler.go:289]: Serve http request 'GET /api/v1/jobs/4746d1529505908316d7f391/log' error: 404 {"code":10010,"message":"object is not found","details":"log entity: 4746d1529505908316d7f391"}
```

GC is very slow and looks like it's terminated after 24 hours, is this configurable? can we allow it to run longer?

also, if the job is terminated like this, shouldn't the log from the period that it was running still be stored?

**Comment by stonezdj** [comment]
It seems that the name of job_logger is invalid
```
job_loggers:
  - name: "STD_OUTPUT" # logger backend name, only support "FILE" and "STD_OUTPUT"
    level: "INFO" # INFO/DEBUG/WARNING/ERROR/FATAL
  - name: "FILE"
    level: "INFO"
    settings: # Customized settings of logger
      base_dir: "/var/log/jobs"
    sweeper:
      duration: 1 #days
      settings: # Customized settings of sweeper
        work_dir: "/var/log/jobs"
```
Could you please trigger another GC job manually and check if the current GC job writes the log?
