### ISSUE TITLE
Harbor behind nginx some uri 404 not found

### ISSUE THREAD

**Issue by he323219002** [goharbor/harbor#17969]
### harbor version

2.6.2

### description

harbor was deployed in vmware machin http://192.168.195.160:8092/，it's OK, I can get accessed with no issue. but when I  deploy nginx in order to use http://192.168.195.160:9002/harbor as reverse proxy, there has some error happend that some uri not found:

![issue_20221212_100710](https://user-images.githubusercontent.com/43230468/206946840-403f6e1e-cee4-42fc-9f4f-221cf3ab2c71.png)

`polyfills.af4f4bbe373e95ea.js:1          GET http://192.168.195.160:9002/setting.json?buildTimeStamp=1667985813147 404 (Not Found)`
`main.3a80e4618d3c965a.js:1 ERROR 
Ze {headers: Y, status: 404, statusText: 'Not Found', url: 'http://192.168.195.160:9002/setting.json?buildTimeStamp=1667985813147', ok: false, …}
error
: 
"<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.22.1</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
headers
: 
Y {normalizedNames: Map(7), lazyUpdate: null, lazyInit: null, headers: Map(7)}
message
: 
"Http failure response for http://192.168.195.160:9002/setting.json?buildTimeStamp=1667985813147: 404 Not Found"
name
: 
"HttpErrorResponse"
ok
: 
false
status
: 
404
statusText
: 
"Not Found"
url
: 
"http://192.168.195.160:9002/setting.json?buildTimeStamp=1667985813147"
[[Prototype]]
: 
Mt`
`polyfills.af4f4bbe373e95ea.js:1          GET http://192.168.195.160:9002/api/v2.0/systeminfo 404 (Not Found)`

### my harbor.yml

```yml
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 8092

# https related config
https:
  # https port for harbor, default is 443
  # port: 443
  # The path of cert and key files for nginx
  #certificate: /your/certificate/path
  #private_key: /your/private/key/path

external_url: http://192.168.195.160:9002/harbor


harbor_admin_password: *******

# Harbor DB configuration
database:
  # The password for the root user of Harbor DB. Change this before any production use.
  password: home
  # The maximum number of connections in the idle connection pool. If it <=0, no idle connections are retained.
  max_idle_conns: 100
  # The maximum number of open connections to the database. If it <= 0, then there is no limit on the number of open connections.
  # Note: the default number of connections is 1024 for postgres of harbor.
  max_open_conns: 900

# The default data volume
data_volume: /data


trivy:
  # ignoreUnfixed The flag to display only fixed vulnerabilities
  ignore_unfixed: false
  # skipUpdate The flag to enable or disable Trivy DB downloads from GitHub
  #
  # You might want to enable this flag in test or CI/CD environments to avoid GitHub rate limiting issues.
  # If the flag is enabled you have to download the `trivy-offline.tar.gz` archive manually, extract `trivy.db` and
  # `metadata.json` files and mount them in the `/home/scanner/.cache/trivy/db` path.
  skip_update: false

  offline_scan: false
  #
  # Comma-separated list of what security issues to detect. Possible values are `vuln`, `config` and `secret`. Defaults to `vuln`.
  security_check: vuln
  #
  # insecure The flag to skip verifying registry certificate
  insecure: false


jobservice:
  # Maximum number of job workers in job service
  max_job_workers: 10

notification:
  # Maximum retry count for webhook job
  webhook_job_max_retry: 10

chart:
  # Change the value of absolute_url to enabled can enable absolute url in chart
  absolute_url: disabled

# Log configurations
log:
  # options are debug, info, warning, error, fatal
  level: info
  # configs for logs in local storage
  local:
    # Log files are rotated log_rotate_count times before being removed. If count is 0, old versions are removed rather than rotated.
    rotate_count: 50
    # Log files are rotated only if they grow bigger than log_rotate_size bytes. If size is followed by k, the size is assumed to be in kilobytes.
    # If the M is used, the size is in megabytes, and if G is used, the size is in gigabytes. So size 100, size 100k, size 100M and size 100G
    # are all valid.
    rotate_size: 200M
    # The directory on your host that store log
    location: /var/log/harbor


_version: 2.6.0


proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy



# enable purge _upload directories
upload_purging:
  enabled: true
  # remove files in _upload directories which exist for a period of time, default is one week.
  age: 168h
  # the interval of the purge operations
  interval: 24h
  dryrun: false


cache:
  # not enabled by default
  enabled: false
  # keep cache for one day by default
  expire_hours: 24

```

### nginx.conf

```
http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;


    server {
        listen       9002;
        server_name  192.168.195.160;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        
        location /harbor {
          proxy_pass http://192.168.195.160:8092;
          proxy_set_header  Host              $http_host;
          proxy_set_header  X-Real-IP         $remote_addr;
          proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header  X-Forwarded-Proto $scheme;

          proxy_buffering off;
          proxy_request_buffering off;
        }

        #location / {
        #    root   html;
        #    index  index.html index.htm;
        #}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }

```

Has anyone encountered this problem and solved it?
thank you for your help
