### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[job-scandata-exports]

### ISSUE THREAD

**Issue by FeiYuJun** [goharbor/harbor#18290]
# version
Kubernetes-v1.20, helm3,  harbor2.7,  redis4.0

# create pv-pvc
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ops
  name: pv-harbor
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Gi
  hostPath:
    path: /data/harbor
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  claimRef:
    name: pvc-harbor
    namespace: ops
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodenv
              values:
                - ops-publish
              operator: In
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-harbor
  namespace: ops
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-harbor
  storageClassName: ""
```
# valumes.yaml
```yaml
# ...
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: "pvc-harbor"
      storageClass: "-"
      subPath: "registry"
      accessMode: ReadWriteMany
      size: 200Gi
      annotations: {}
    chartmuseum:
      existingClaim: "pvc-harbor"
      storageClass: "-"
      subPath: "chartmuseum"
      accessMode: ReadWriteMany
      size: 200Gi
      annotations: {}
    jobservice:
      jobLog:
        existingClaim: "pvc-harbor"
        storageClass: "-"
        subPath: "joblog"
        accessMode: ReadWriteMany
        size: 200Gi
        annotations: {}
      scanDataExports:
        existingClaim: "pvc-harbor"
        storageClass: "-"
        subPath: "scanexports"
        accessMode: ReadWriteMany
        size: 200Gi
        annotations: {}
    trivy:
      existingClaim: "pvc-harbor"
      storageClass: "-"
      subPath: "trivy"
      accessMode: ReadWriteMany
      size: 200Gi
      annotations: {}
  imageChartStorage:
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /data/harbor
# ...
```
# install
```bash
[root@k8s-master local]# helm  install harbor ./harbor -n ops
NAME: harbor
LAST DEPLOYED: Wed Mar  1 10:48:30 2023
NAMESPACE: ops
STATUS: deployed
REVISION: 1
TEST SUITE: None

[root@k8s-master local]# kubectl  get pod,deploy -n ops
NAME                                      READY   STATUS              RESTARTS   AGE
pod/harbor-chartmuseum-58c6bcfdc4-gfpt9   1/1     Running             0          3m49s
pod/harbor-core-8594d7cc4f-ch2nx          1/1     Running             0          3m49s
pod/harbor-database-0                     1/1     Running             0          3m49s
pod/harbor-jobservice-6d965b89cc-kc8w5    0/1     ContainerCreating   0          3m49s
pod/harbor-nginx-5c5785b46c-dkn6w         1/1     Running             0          3m49s
pod/harbor-portal-856f48fd86-h7fpz        1/1     Running             0          3m49s
pod/harbor-registry-7f6c9c589c-w9rvr      2/2     Running             0          3m49s
pod/harbor-trivy-0                        1/1     Running             0          3m49s

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/harbor-chartmuseum   1/1     1            1           3m50s
deployment.apps/harbor-core          1/1     1            1           3m50s
deployment.apps/harbor-jobservice    0/1     1            0           3m50s
deployment.apps/harbor-nginx         1/1     1            1           3m50s
deployment.apps/harbor-portal        1/1     1            1           3m50s
deployment.apps/harbor-registry      1/1     1            1           3m50s
```
# error log
```bash
[root@k8s-master local]# kubectl logs pod/harbor-jobservice-6d965b89cc-kc8w5 -n ops
Error from server (BadRequest): container "jobservice" in pod "harbor-jobservice-6d965b89cc-kc8w5" is waiting to start: ContainerCreating

[root@k8s-master local]# kubectl describe pod/harbor-jobservice-6d965b89cc-kc8w5
Events:
Type     Reason       Age   From               Message
----     ------       ----  ----               -------
Normal   Scheduled    4m4s  default-scheduler  Successfully assigned ops/harbor-jobservice-6d965b89cc-kc8w5 to k8s-node01
Warning  FailedMount  2m2s  kubelet            Unable to attach or mount volumes: unmounted volumes=[job-scandata-exports], unattached volumes=[jobservice-config job-logs job-scandata-exports]: timed out waiting for the condition
```

Why failed? Is there a problem with the configuration?
