### ISSUE TITLE
The docker-compose command has been replaced by docker compose

### ISSUE THREAD

**Issue by Aurorxa** [goharbor/harbor#18444]
**Expected behavior and actual behavior:**
the docker-compose command has been replaced by docker compose，Now the command for installing docker compose is `yum install -y -q yum-utils`,`yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo`,`yum install -y -q docker-ce docker-ce-cli containerd.io docker-scan-plugin docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin`

**Steps to reproduce the problem:**
![1](https://user-images.githubusercontent.com/25677587/228396197-1de94b30-e861-4b44-9929-161b7093222d.gif)

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.17]
- docker engine version: [23.0.1]
- docker compose version: [v2.17.2]

**Current installation steps improved :**
```shell
wget https://github.com/goharbor/harbor/releases/download/v1.10.17/harbor-offline-installer-v1.10.17.tgz
```
```shell
tar -zxvf harbor-offline-installer-v1.10.17.tgz
```
```shell
vim harbor/harbor.yml
```
```yaml
# Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: 192.168.68.17 # 主机的 IP 地址

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 80

# https related config
#https: # 关闭 https
  # https port for harbor, default is 443
 # port: 443
  # The path of cert and key files for nginx
  #certificate: /your/certificate/path
  #private_key: /your/private/key/path
```
```shell
sed -i 's/docker-compose --version/docker compose version/g' common.sh
sed -i 's/docker-compose/docker compose/g' install.sh
./install.sh
```
