### ISSUE TITLE
Trivy vulnerability scanning failing 

### ISSUE THREAD

**Issue by juliomarmin** [goharbor/harbor#18454]
Hi,

I'm trying to perform an image vulnerability scanning, but I get error. I suspect the issue could be newer Trivy version not backwards compatible. (?) (See logs below)
The versions I have are:

- Harbor v2.7.1
- Docker: 23.0.2
- Docker Compose version v2.16.0
- Trivy : "v0.37.2",

The logs are:
### Scan log
2023-03-30T13:49:37Z [INFO] [/pkg/scan/job.go:387]: {
  "uuid": "cf3837b7-ced8-11ed-a2bf-0242ac120009",
  "name": "Trivy",
  "description": "The Trivy scanner adapter",
  "url": "http://trivy-adapter:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.37.2",
  "create_time": "2023-03-30T08:56:50.349223Z",
  "update_time": "2023-03-30T08:56:50.349226Z"
}
2023-03-30T13:49:37Z [INFO] [/pkg/scan/job.go:387]: {
  "registry": {
    "url": "http://core:8080",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 2,
    "repository": "harbor/aquasec/trivy",
    "tag": "latest",
    "digest": "sha256:5a290a63ed8b927fee29ceed3480036c00ce5460a75d0ad3598d7c8636e067a9",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2023-03-30T13:49:37Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2023-03-30T13:49:37Z [INFO] [/pkg/scan/job.go:224]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2023-03-30T13:49:39Z [INFO] [/pkg/scan/job.go:245]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2023-03-30T13:49:46Z [ERROR] [/pkg/scan/job.go:294]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: signal: killed: 2023-03-30T13:49:41.867Z	[33mWARN[0m	'--security-checks' is deprecated. Use '--scanners' instead.
2023-03-30T13:49:41.875Z	[34mINFO[0m	Vulnerability scanning is enabled
: general response handler: unexpected status code: 500, expected: 200

### Trivy-adapter log
Mar 30 13:49:09 REDACTED.compute.internal trivy-adapter[614]: find: '/etc/harbor/ssl': No such file or directory
Mar 30 13:49:09 REDACTED.compute.internal trivy-adapter[614]: {"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2023-03-30T13:49:09Z","version":"dev"}
Mar 30 13:49:09 REDACTED.compute.internal trivy-adapter[614]: {"addr":":8080","level":"warning","msg":"Starting API server without TLS","time":"2023-03-30T13:49:09Z"}
Mar 30 13:49:45 REDACTED.compute.internal trivy-adapter[614]: {"**exit_code":-1**,"image_ref":"core:8080/harbor/aquasec/trivy@sha256:5a290a63ed8b927fee29ceed3480036c00ce5460a75d0ad3598d7c8636e067a9","level":"error","msg":"**Running trivy failed**","std_out":"2023-03-30T13:49:41.867Z\t\u001b[33mWARN\u001b[0m\t'**--security-checks' is deprecated. Use '--scanners' instead**.\n2023-03-30T13:49:41.875Z\t\u001b[34mINFO\u001b[0m\tVulnerability scanning is enabled\n","time":"2023-03-30T13:49:45Z"}
Mar 30 13:49:46 REDACTED.compute.internal trivy-adapter[614]: {"error":"running trivy wrapper: running trivy: signal: killed: 2023-03-30T13:49:41.867Z\t\u001b[33mWARN\u001b[0m\t'--security-checks' is deprecated. Use '--scanners' instead.\n2023-03-30T13:49:41.875Z\t\u001b[34mINFO\u001b[0m\tVulnerability scanning is enabled\n","level":"error","msg":"Scan failed","time":"2023-03-30T13:49:45Z"}
Mar 30 13:49:46 REDACTED.compute.internal trivy-adapter[614]: {"error":"running trivy wrapper: running trivy: signal: killed: 2023-03-30T13:49:41.867Z\t\u001b[33mWARN\u001b[0m\t'--security-checks' is deprecated. Use '--scanners' instead.\n2023-03-30T13:49:41.875Z\t\u001b[34mINFO\u001b[0m\tVulnerability scanning is enabled\n","level":"error","msg":"Scan job failed","scan_job_id":"5e203dc423854d8daf2ed0c5","time":"2023-03-30T13:49:46Z"}

**Comment by zyyw** [comment]
Hi @juliomarmin , are you using Trivy scan in an air-gapped environment? Please share the Trivy related config in your `harbor.yml` file. There is a known issue that Trivy fails to scan an artifact in air-gapped environment?
**Scan log**
```
2023-03-31T08:58:14Z [INFO] [/pkg/scan/job.go:387]: {
  "uuid": "162c39e3-cf92-11ed-994b-0242ac140009",
  "name": "Trivy",
  "description": "The Trivy scanner adapter",
  "url": "http://trivy-adapter:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.37.2",
  "create_time": "2023-03-31T07:03:06.274913Z",
  "update_time": "2023-03-31T07:03:06.274915Z"
}
2023-03-31T08:58:14Z [INFO] [/pkg/scan/job.go:387]: {
  "registry": {
    "url": "http://core:8080",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 1,
    "repository": "library/nginx",
    "tag": "1.23.3",
    "digest": "sha256:7f797701ded5055676d656f11071f84e2888548a2e7ed12a4977c28ef6114b17",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2023-03-31T08:58:14Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2023-03-31T08:58:14Z [INFO] [/pkg/scan/job.go:224]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2023-03-31T08:58:16Z [INFO] [/pkg/scan/job.go:245]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2023-03-31T08:58:21Z [ERROR] [/pkg/scan/job.go:294]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2023-03-31T08:58:16.738Z	[33mWARN[0m	'--skip-update' is deprecated. Use '--skip-db-update' instead.
2023-03-31T08:58:16.738Z	[33mWARN[0m	'--security-checks' is deprecated. Use '--scanners' instead.
2023-03-31T08:58:16.742Z	[31mERROR[0m	The local DB has an old schema version which is not supported by the current version of Trivy CLI. DB needs to be updated.
2023-03-31T08:58:16.743Z	[31mFATAL[0m	init error: DB error: database error: validate error: --skip-update cannot be specified with the old DB schema. Local DB: 1, Expected: 2
: general response handler: unexpected status code: 500, expected: 200
```
I also tried install trivy with default config in `harbor.yml`, and it works fine in this case.

**Comment by senthil13** [comment]
Yes we also have this issue. 

our logs
```
2023-04-10T14:47:59Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2023-04-10T14:47:59Z [INFO] [/pkg/scan/job.go:224]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2023-04-10T14:48:01Z [INFO] [/pkg/scan/job.go:245]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2023-04-10T14:48:06Z [ERROR] [/pkg/scan/job.go:294]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 1: 2023-04-10T14:48:03.954Z	[33mWARN[0m	'--security-checks' is deprecated. Use '--scanners' instead.
2023-04-10T14:48:03.970Z	[34mINFO[0m	Need to update DB
2023-04-10T14:48:03.970Z	[34mINFO[0m	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-04-10T14:48:03.970Z	[34mINFO[0m	Downloading DB...
2023-04-10T14:48:03.990Z	[31mFATAL[0m	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get "https://ghcr.io/v2/": Forbidden
: general response handler: unexpected status code: 500, expected: 200
```
This is from our harbor.yml
```
# Trivy configuration
#
# Trivy DB contains vulnerability information from NVD, Red Hat, and many other upstream vulnerability databases.
# It is downloaded by Trivy from the GitHub release page https://github.com/aquasecurity/trivy-db/releases and cached
# in the local file system. In addition, the database contains the update timestamp so Trivy can detect whether it
# should download a newer version from the Internet or use the cached one. Currently, the database is updated every
# 12 hours and published as a new release to GitHub.
trivy:
  # ignoreUnfixed The flag to display only fixed vulnerabilities
  ignore_unfixed: false
  # timeout The duration to wait for scan completion
  timeout: 5m0s
  # skipUpdate The flag to enable or disable Trivy DB downloads from GitHub
  #
  # You might want to enable this flag in test or CI/CD environments to avoid GitHub rate limiting issues.
  # If the flag is enabled you have to download the `trivy-offline.tar.gz` archive manually, extract `trivy.db` and
  # `metadata.json` files and mount them in the `/home/scanner/.cache/trivy/db` path.
  skip_update: false
  #
  offline_scan: false
  #
  # Comma-separated list of what security issues to detect. Possible values are `vuln`, `config` and `secret`. Defaults to `vuln`.
  security_check: vuln
  #
  # insecure The flag to skip verifying registry certificate
  insecure: false
  # github_token The GitHub access token to download Trivy DB
  #
  # Anonymous downloads from GitHub are subject to the limit of 60 requests per hour. Normally such rate limit is enough
  # for production operations. If, for any reason, it's not enough, you could increase the rate limit to 5000
  # requests per hour by specifying the GitHub access token. For more details on GitHub rate limiting please consult
  # https://developer.github.com/v3/#rate-limiting
  #
  # You can create a GitHub token by following the instructions in
  # https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
  #
  # github_token: xxx
```

Trivy version is 
```
# trivy -v
Version: 0.39.0
```
harbor version is  v2.7.1

any help will be much appreciated 

Thanks
Senthil
