### ISSUE TITLE
How to configure Harbord to be a mirror registry for Containerd?

### ISSUE THREAD

**Issue by m0sh1x2** [goharbor/harbor#18530]
Hello,

For several days I am trying to configure Harbor Proxy Cache to become a mirror registry for Containerd. Most likely I am missing some very simple core steps but here is what I am doing:

1. Configure containerd to pull docker.io images from harbor proxy cache

/etc/containerd/config.toml:
```toml
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
```

/etc/containerd/certs.d/docker.io:
```toml
server = "https://docker.io"

[host."https://[REDACTED_HARBOR_REGISTRY_URL]/v2/docker.io"]
  capabilities = ["pull", "resolve"]
```

Reload configs
```
systemctl daemon-reload && systemctl restart containerd
```

Try to pull image:

```
root@control-plane-01:/etc/containerd/certs.d/docker.io# crictl pull docker.io/library/node:latest
DEBU[0000] get image connection
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:docker.io/library/node:latest,Annotations:map[string]string{},},Auth:nil,SandboxConfig:nil,}
E0413 12:48:28.685862 1603695 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"docker.io/library/node:latest\": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:1a2ff2f511abbd3a7923669b27454b8572a120e94e2870a4bd2b8c6f8ad9eba8: not found" image="docker.io/library/node:latest"
FATA[0002] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/node:latest": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:1a2ff2f511abbd3a7923669b27454b8572a120e94e2870a4bd2b8c6f8ad9eba8: not found
```

I've tried several scenarios even I've forgotten some of them but most are deprecated. Any help or configuration sharing/guidance will be of a great help.

Thanks
