### ISSUE TITLE
Cannot push to registry same tag with vulnerabilities even with imutable exclusion

### ISSUE THREAD

**Issue by arnaudclerc** [goharbor/harbor#18792]
**Expected behavior and actual behavior:**
my registry is configured to be immutable except for tag `*-dev`,
yet, pushing an existing tag matching the exclusion regex fails, I get an http response `412 Precondition Failed`

I expect being able to push the image no matter the vulnerabilities status, when matching imutable exclusion pattern.

the intended process works as expected when image hasn't vulnerabilities.

**Steps to reproduce the problem:**
- Kaniko image builder within Gitlab CI job
- Private registry configured as immutable except for specific tag
![image](https://github.com/goharbor/harbor/assets/23419677/393e8db8-405a-4ec4-ad98-be0525a4930a)
- Private registry configured to prevent images with vulnerabilities to work
![image](https://github.com/goharbor/harbor/assets/23419677/1525c89b-2ff2-4169-86f9-9320dcbc9f33)
- push 1st image with vulnerabilities matching the imutable exclusion pattern
- push a second time the image with same tag (image content doesn't affect behavior)

**Versions:**
- harbor: Version v2.7.0-864aca34
- Kaniko builder: gcr.io/kaniko-project/executor:debug

```
INFO[0003] Pushing image to core-harbor.[MASKED]/container-registry/mon-frontend:0.2.0-dev 
error pushing image: failed to push to destination core-harbor.[MASKED]/container-registry/mon-frontend:0.2.0-dev: HEAD https://core-harbor.[masked]/v2/container-registry/mon-frontend/manifests/0.2.0-dev: unexpected status code 412 Precondition Failed (HEAD responses have no body, use GET for details)
```

**Comment by AllForNothing** [comment]
At present, you cannot set the `immutable policy` to make the specified image escape the constraints of the CVE inspection policy.  
The supported approach is to use the CVE allowlist(currently, tag strategy/filter for CVE allowlist is not supported, if needed, you can open a discussion for this topic ).

**Comment by arnaudclerc** [comment]
Thanks for your answer.
I actually want to block images with CVE via pulling (preventing them to be exposed), but i expected to be able to push on top of the tag to fix CVE.

As i understand it's not supported yet.

I will open discussion to add a feature to specify which way (push/pull) CVE constraints should block the image.

**Comment by AllForNothing** [comment]
Sorry, I may misunderstand your case.   

 `but i expected to be able to push on top of the tag to fix CVE.`: 
you should always be able to push an image that's not immutable.
the CVE inspection policy has no impact on push operation.

Can you check the tag status(whether it is immutable) for the images you want to push?
If the images you want to push are not immutable, there must be some other reasons for the push failure

**Comment by arnaudclerc** [comment]
I've made 4 push on the same tag.
<img width="1044" alt="image" src="https://github.com/goharbor/harbor/assets/23419677/58f5e092-63e6-416c-9956-82d58e91bf2f">
the tag is matching the imutable exclusion, the first two didn't have CVE, the third introduced a CVE and made impossible to push the 4th (supposed to fix the CVE, but at this point the image content is irrelevant)

Result of 4th image push:
<img width="777" alt="image" src="https://github.com/goharbor/harbor/assets/23419677/7f8e0587-0363-4f1c-8bc2-543ee080ef23">

**Comment by AllForNothing** [comment]
@arnaudclerc Will your fourth push succeed if you uncheck the `prevent images with vulnerabilities to work` option?

**Comment by arnaudclerc** [comment]
it did.

**Comment by AllForNothing** [comment]
@arnaudclerc 
What tool are you using for push?  not docker client, right?

**Comment by arnaudclerc** [comment]
Kaniko.

I've did the test with Docker CLI and the behaviour disappear, working as expected.

I deduct that kaniko is doing the action that is blocking, but i doubt that it tries to pull.

Are you familiar with kaniko ? Here is my command if it can help

````yaml
.container-build:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    before_script:        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"https://${HARBOR_URL}\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_CONTAINER_MANAGER_LOGIN}" "${HARBOR_CONTAINER_MANAGER_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    script:
        - /kaniko/executor
            --context "${CI_PROJECT_DIR}"
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${HARBOR_URL}/container-registry/${CI_PROJECT_NAME}:${NEW_TAG}"
````
