### ISSUE TITLE
Annotations and Custom OCI image configuration in Harbor v2.x

### ISSUE THREAD

**Issue by guigomcha** [goharbor/harbor#18886]
Hi, I am trying to get harbor to show a few things in the UI but I don't seem to get it to work. There are a couple of questions below, thanks in advance.

1. Annotations: right now I have added annotations to the manifest, the layers and the config to see if it would pick up any. The only thing that I got was that it is combining the config descriptor content with the config annotations in the "overview" UI of the image tag (which actually does not seem very ok to me to be honest).

example manifest (fetched from harbor using ORAS)
```yaml

{
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "config": {
        "mediaType": "application/REDACTED",
        "digest": "sha256:REDACTED",
        "size": 142,
        "annotations": {
            "org.opencontainers.image.description": "REDACTED",
            "org.opencontainers.image.vendor": "REDACTED",
            "org.opencontainers.image.version": "1.0.1"
        }
    },
    "layers": [
        {
            "mediaType": "application/tar+gz",
            "digest": "sha256:REDACTED",
            "size": 1359,
            "annotations": {
                "org.opencontainers.image.title": "REDACTED.tar.gz"
            }
        }
    ],
    "annotations": {
        "org.opencontainers.image.created": "2023-07-04T07:46:54Z",
        "some.example": "test"
    }
}
```
What do I have to do to see the annotations in the repository table ??
![image](https://github.com/goharbor/harbor/assets/39807810/c41eae9b-3f6b-4c35-b9ae-11682bc0b57b)

2. Custom MediaType configs: I don't see any documentation on how to add a different icon for a specific image mediaType (always shows the OCI icon). Is this even possible?
![image](https://github.com/goharbor/harbor/assets/39807810/f949c15a-bcfc-4c63-9c94-94276c5fe51c)
 what kind of pre-configuration is possible for custom mediaTypes? e.g. adding a pull comand example and some automatic labels for example...
