### ISSUE TITLE
external redis username ACL auth connect distribution registry failed

### ISSUE THREAD

**Issue by MinerYang** [goharbor/harbor#18892]
If you are reporting a problem, please make sure the following information are provided:
- introduced by: https://github.com/goharbor/harbor/pull/18364
- affect version: v2.8.0, v2.8.1, v2.8.2
- impact: disrtibution performance

**Expected behavior and actual behavior:**
upstream distribution do not support username-password auth mode
using `external_reids.username` would cause distribution redis connection failure , which would not affect image push/pull but only have an impact on distribution performance, could see error log in the registry container.
```
time="2023-07-05T06:29:53.894080917Z" level=error msg="redis: error connecting: WRONGPASS invalid username-password pair or user is disabled." go.version=go1.20.4 instance.id=ea5a081f-84d5-4d63-8618-70f2078871be redis.connect.duration=124.519µs service=registry version=v2.8.2.m
time="2023-07-05T06:29:53.894240222Z" level=error msg="redis: error connecting: WRONGPASS invalid username-password pair or user is disabled." go.version=go1.20.4 instance.id=ea5a081f-84d5-4d63-8618-70f2078871be redis.connect.duration=116.94µs service=registry version=v2.8.2.m
```

**Steps to reproduce the problem:**
- configure external redis with both username and password
```
external_redis:
  # support redis, redis+sentinel
  # host for redis: <host_redis>:<port_redis>
  # host for redis+sentinel:
  #  <host_sentinel1>:<port_sentinel1>,<host_sentinel2>:<port_sentinel2>,<host_sentinel3>:<port_sentinel3>
  host: myhost:6379
  password: mypassword
  # Redis AUTH command was extended in Redis 6, it is possible to use it in the two-arguments AUTH <username> <password> form.
  username: virginia
 ...
```
- install harbor
- push/pull image into harbor 

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.8.0/v2.8.1 / v2.8.2
- docker engine version: 23.0.3

**Additional context:**

Note: distribution (until v2.8.2) only support auth by password
- https://pkg.go.dev/github.com/distribution/distribution/v3/configuration
- https://github.com/distribution/distribution/blob/7c354a4b40feeea21d7eeae4de91c8ff7951e672/registry/handlers/app.go#L530
