### ISSUE TITLE
harbor-core  http: proxy error: context canceled

### ISSUE THREAD

**Issue by SmallGaoX** [goharbor/harbor#18919]
# who can save me
- docker-compose
- harbor: v2.8.2-d4c34dcc
```txt
nginx --> harbor
```
##  harbor.yml
```
hostname: harbor.internal.com
http:
  port: 80
  relativeurls: true
external_url: https://harbor.internal.com
harbor_admin_password: xxx
database:
  password: xxx
  max_idle_conns: 100
  max_open_conns: 900
  conn_max_lifetime: 5m
  conn_max_idle_time: 0
data_volume: /data
storage_service:
  s3:
    accesskey: xxx
    secretkey: xxx
    region: us-east-1
    regionendpoint: https://oss.internal.com
    bucket: harbor
    multipartcopythresholdsize: "5368709120"
trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  security_check: vuln
  insecure: false
jobservice:
  max_job_workers: 10
  logger_sweeper_duration: 1 
notification:
  webhook_job_max_retry: 3
  webhook_job_http_client_timeout: 3 
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor
_version: 2.8.0
external_redis:
  host: 10.10.101.17:6379
  password: xxx
  registry_db_index: 1
  jobservice_db_index: 2
  trivy_db_index: 5
  idle_timeout_seconds: 30
proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy
metric:
  enabled: false
  port: 9090
  path: /metrics
upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false
cache:
  enabled: false
  expire_hours: 24
```
```txt
helm push loki-5.8.9.tgz  oci://harbor.internal.com/library
Error: failed commit on ref "unknown-sha256:27f6b31d6e9884505825a54c2eea1428a2cd0edf834ce3e1d2d2fb5670638de7": unexpected status: 401 Unauthorized
```

```log
nginx              | 192.168.2.237 - "HEAD /v2/library/loki/blobs/sha256:8ef1d433ae2a02b609865fd016982d1c22c4efc2cccac424e13cd29730732341 HTTP/1.1" 401 0 "-" "Helm/3.10.0" 0.002 0.002 .
nginx              | 192.168.2.237 - "HEAD /v2/library/loki/blobs/sha256:27f6b31d6e9884505825a54c2eea1428a2cd0edf834ce3e1d2d2fb5670638de7 HTTP/1.1" 401 0 "-" "Helm/3.10.0" 0.001 0.001 .
nginx              | 192.168.2.237 - "POST /service/token HTTP/1.1" 405 19 "-" "Helm/3.10.0" 0.001 0.001 .
nginx              | 192.168.2.237 - "GET /service/token?scope=repository%3Alibrary%2Floki%3Apull&scope=repository%3Alibrary%2Floki%3Apull%2Cpush&service=harbor-registry HTTP/1.1" 200 1050 "-" "Helm/3.10.0" 0.025 0.025 .
nginx              | 192.168.2.237 - "HEAD /v2/library/loki/blobs/sha256:8ef1d433ae2a02b609865fd016982d1c22c4efc2cccac424e13cd29730732341 HTTP/1.1" 404 0 "-" "Helm/3.10.0" 0.005 0.005 .
nginx              | 192.168.2.237 - "HEAD /v2/library/loki/blobs/sha256:27f6b31d6e9884505825a54c2eea1428a2cd0edf834ce3e1d2d2fb5670638de7 HTTP/1.1" 404 0 "-" "Helm/3.10.0" 0.005 0.005 .
registry           | time="2023-07-12T01:24:26.203782556Z" level=info msg="authorized request" go.version=go1.20.4 http.request.host=harbor.internal.com http.request.id=29e485f6-5520-45ed-b158-2ca71a4c10ee http.request.method=POST http.request.remoteaddr=10.0.1.1 http.request.uri="/v2/library/loki/blobs/uploads/" http.request.useragent="Helm/3.10.0" vars.name="library/loki"
registry           | time="2023-07-12T01:24:26.205083779Z" level=info msg="authorized request" go.version=go1.20.4 http.request.host=harbor.internal.com http.request.id=9a4cc5bf-9d9f-42d7-81e5-084f32296824 http.request.method=POST http.request.remoteaddr=10.0.1.1 http.request.uri="/v2/library/loki/blobs/uploads/" http.request.useragent="Helm/3.10.0" vars.name="library/loki"
registry           | time="2023-07-12T01:24:26.964477415Z" level=info msg="response completed" go.version=go1.20.4 http.request.host=harbor.internal.com http.request.id=29e485f6-5520-45ed-b158-2ca71a4c10ee http.request.method=POST http.request.remoteaddr=10.0.1.1 http.request.uri="/v2/library/loki/blobs/uploads/" http.request.useragent="Helm/3.10.0" http.response.duration=765.284815ms http.response.status=202 http.response.written=0
registry           | 172.18.0.8 - - [12/Jul/2023:01:24:26 +0000] "POST /v2/library/loki/blobs/uploads/ HTTP/1.1" 202 0 "" "Helm/3.10.0"
nginx              | 192.168.2.237 - "POST /v2/library/loki/blobs/uploads/ HTTP/1.1" 202 0 "-" "Helm/3.10.0" 0.774 0.774 .
nginx              | 192.168.2.237 - "GET /v2/library/loki/blobs/uploads/19e4005e-c0db-491f-ad88-4b573a80d238?_state=AmRRRvjIat0rebllJMY6uf-dWsKHDdPsICQ_jzTXbFR7Ik5hbWUiOiJsaWJyYXJ5L2xva2kiLCJVVUlEIjoiMTllNDAwNWUtYzBkYi00OTFmLWFkODgtNGI1NzNhODBkMjM4IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIzLTA3LTEyVDAxOjI0OjI2LjIwMzg5Mzk3MloifQ%3D%3D&digest=sha256%3A8ef1d433ae2a02b609865fd016982d1c22c4efc2cccac424e13cd29730732341 HTTP/1.1" 401 152 "http://harbor.internal.com/v2/library/loki/blobs/uploads/19e4005e-c0db-491f-ad88-4b573a80d238?_state=AmRRRvjIat0rebllJMY6uf-dWsKHDdPsICQ_jzTXbFR7Ik5hbWUiOiJsaWJyYXJ5L2xva2kiLCJVVUlEIjoiMTllNDAwNWUtYzBkYi00OTFmLWFkODgtNGI1NzNhODBkMjM4IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIzLTA3LTEyVDAxOjI0OjI2LjIwMzg5Mzk3MloifQ%3D%3D&digest=sha256%3A8ef1d433ae2a02b609865fd016982d1c22c4efc2cccac424e13cd29730732341" "Helm/3.10.0" 0.002 0.002 .
nginx              | 192.168.2.237 - "POST /v2/library/loki/blobs/uploads/ HTTP/1.1" 499 0 "-" "Helm/3.10.0" 0.797 0.797 .
harbor-core        | 2023/07/12 01:24:26 http: proxy error: context canceled
registry           | time="2023-07-12T01:24:27.126936123Z" level=info msg="response completed" go.version=go1.20.4 http.request.host=harbor.internal.com http.request.id=9a4cc5bf-9d9f-42d7-81e5-084f32296824 http.request.method=POST http.request.remoteaddr=10.0.1.1 http.request.uri="/v2/library/loki/blobs/uploads/" http.request.useragent="Helm/3.10.0" http.response.duration=927.980067ms http.response.status=202 http.response.written=0
registry           | 172.18.0.8 - - [12/Jul/2023:01:24:26 +0000] "POST /v2/library/loki/blobs/uploads/ HTTP/1.1" 202 0 "" "Helm/3.10.0"
registry           | 172.18.0.8 - - [12/Jul/2023:01:24:29 +0000] "GET / HTTP/1.1" 200 0 "" "Go-http-client/1.1"
harbor-portal      | 172.18.0.8 - - [12/Jul/2023:01:24:29 +0000] "GET / HTTP/1.1" 200 785 "-" "Go-http-client/1.1"
registryctl        | 172.18.0.8 - - [12/Jul/2023:01:24:29 +0000] "GET /api/health HTTP/1.1" 200 9
```

I'm already logged in
```
 helm registry login harbor.internal.com --username admin
```
