### ISSUE TITLE
Does Harbor version 2.8 support token authentication

### ISSUE THREAD

**Issue by yuexian1234** [goharbor/harbor#19196]
Does Harbor version 2.8 support token authentication? It seems that the default is now basic password authentication
in file  common/config/registry/config.yml,the config as below
```
auth: 
   htpasswd: 
        realm: harbor-registry-basic-realm
        path: /etc/registry/passwd
```
i want to use
```
auth: 
  token:
    issuer: harbor-token-issuer
    realm: https://newhub.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
```

but,When I manually switch to token authentication, docker login returns an error
<img width="806" alt="image" src="https://github.com/goharbor/harbor/assets/14341344/1800c754-92a4-4d88-bc17-7f4fed429ded">

in the harbor1.x，i can use token authentication correctly。
