### ISSUE TITLE
Garbage collector not clean redis keys

### ISSUE THREAD

**Issue by nevlkv** [goharbor/harbor#19325]
**Expected behavior and actual behavior:**
Garbage collector not cleanup redis keys, and failed with message

```
2023-09-06T02:37:23Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:414]: 2937 blobs and 812 manifests are actually deleted 2023-09-06T02:37:23Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:415]: The GC job actual frees up 54343 MB space. 2023-09-06T02:37:23Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:445]: failed to clean registry cache error retrieving 'blobs::*' keys: WRONGPASS invalid username-password pair or user is disabled., pattern blobs::*
```

**Steps to reproduce the problem:**

Starts registry cleanup

**Versions:**

- harbor version: 2.8.4

**Additional context:**

external redis with default user

```
_REDIS_URL_REG: redis://:password@harbor-redis-master:6379/2?idle_timeout_seconds=30
```

**Comment by wy65701436** [comment]
the error points the auth info is incorrect, can you check that at your end?

**Comment by nevlkv** [comment]
password correct 
```
redis-cli -n 2 -a <password>
127.0.0.1:6379[2]> info keyspace
# Keyspace
db0:keys=133200,expires=133085,avg_ttl=2212096
db1:keys=2036,expires=1748,avg_ttl=83530815
db2:keys=5784,expires=156,avg_ttl=85886397
db5:keys=63,expires=54,avg_ttl=2360250

```

**Comment by nevlkv** [comment]
garbage service used `_REDIS_URL_REG:` ?

**Comment by MinerYang** [comment]
Hi @nevlkv 

- Is this a fresh install harbor? Have you changed the redis password after installation?
- Could you also check/provide other redis url, for example _REDIS_URL_CORE?

**Comment by nevlkv** [comment]
1. current instance was upgraded from 2.7.1, redis is external and not changed
2. we use default redis account and password always identical
```
kubectl get cm harbor-core -n=io  -o yaml
apiVersion: v1
data:
  _REDIS_URL_CORE: redis://:<password>@harbor-redis-master:6379/0?idle_timeout_seconds=30
  _REDIS_URL_REG: redis://:<password>@harbor-redis-master:6379/2?idle_timeout_seconds=30

```
i can auth with <password> via redis-cli and flushdb[

GC [use same connection string](https://github.com/goharbor/harbor/blob/v2.8.4/src/jobservice/job/impl/gc/garbage_collection.go#L114)

**Comment by viceice** [comment]
Seeing same error:
```
023-09-17T00:02:59Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:515]: failed to clean registry cache failed to scan keys: WRONGPASS invalid username-password pair or user is disabled., pattern blobs::*
```

I've no password for redis, i'm using network policies to limit redis access to harbor.
```yaml
_REDIS_URL_CORE: redis://keydb:6379/0?idle_timeout_seconds=30
_REDIS_URL_REG: redis://keydb:6379/2?idle_timeout_seconds=30
```

**Comment by viceice** [comment]
![image](https://github.com/goharbor/harbor/assets/1798109/8b9ccd23-ab86-4c53-ac46-4d94a7bb6098)
It seems the redis url is not passed to the job service via env.

I only see this inside `config.yml` if job service:
```yaml
worker_pool:
  workers: 10
  backend: "redis"
  redis_pool:
    redis_url: "redis://keydb:6379/1"
    namespace: "harbor_job_service_namespace"
    idle_timeout_second: 3600
```
