### ISSUE TITLE
Proxy cache serves the stale digests for the latest tags

### ISSUE THREAD

**Issue by hoptical** [goharbor/harbor#19429]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When a new image is pushed on the **same** tag (e.g., **latest**), the harbor proxy cache doesn't update to the latest digest and still serves the stale one. This behavior persists even when all artifacts are removed from the harbor panel **unless** the artifact record is deleted from **Redis**. 

It's expected that Harbor serves the most recent digest for the same tag.

**Steps to reproduce the problem:**
1. Create a project regarding the desired repository; `ghcr` here.
2. Pull the repository: `ghcr.io/snapp-incubator/snappcloud-hub-catalog:latest`
3. Push a new image with the latest tag
4. Pull the image, and you will see that the previous digest is pulled.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.7.0
- docker engine version: 20.10.17
- docker-compose version: 1.18.0

**Additional context:**

- **Harbor config files:** `harbor.yaml`:
   ```yaml
  hostname: xxx
  
  http:
    port: 80
  https:
      port: 443
      private_key: xxx
      certificate: xxx
  harbor_admin_password: xxx
  database:
    password: xxx
    max_idle_conns: 100
    max_open_conns: 1000
  data_volume: /data
  jobservice:
    max_job_workers: 10
  notification:
    webhook_job_max_retry: 10
  chart:
    absolute_url: disabled
  log:
    level: info
    local:
      rotate_count: 50
      rotate_size: 200M
      location: /var/log/harbor
  _version: 2.7.0
  proxy:
    http_proxy: xxx
    https_proxy: xxx
    no_proxy: xxx
    components:
      - core
      - registry
  
  metric:
    enabled: true
    port: 9090
    path: /metrics
  
  cache:
    # not enabled by default
    enabled: true
    # keep cache for one day by default
    expire_hours: 24
  ```
- **Log files:** Attached; the desired digest is `sha256:6920278b1beca46c117c655cdf7edd0932243f95620de35d0ea1e41d27c00335`
![Screenshot from 2023-10-10 13-17-55](https://github.com/goharbor/harbor/assets/30399989/3fcc4461-7186-4742-9def-164ca7af2ba1)
