### ISSUE TITLE
Trivy Adapter Not Working

### ISSUE THREAD

**Issue by uttkumert** [goharbor/harbor#19479]
I install harbor with docker compose and add trivy-adapter on docker-compose.yml. My current configuration and docker-compose.yml like these

```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS                    PORTS                                   NAMES
74f6d39199f2   goharbor/nginx-photon:v2.9.0           "nginx -g 'daemon of…"   22 minutes ago   Up 22 minutes (healthy)   0.0.0.0:80->8080/tcp, :::80->8080/tcp   nginx
b6808c9c845c   goharbor/harbor-jobservice:v2.9.0      "/harbor/entrypoint.…"   22 minutes ago   Up 22 minutes (healthy)                                           harbor-jobservice
a9d4bfd0ba46   goharbor/harbor-core:v2.9.0            "/harbor/entrypoint.…"   22 minutes ago   Up 22 minutes (healthy)                                           harbor-core
37c3d8a1fd75   goharbor/trivy-adapter-photon:v2.5.0   "/home/scanner/entry…"   22 minutes ago   Up 22 minutes (healthy)                                           trivy-adapter
3a8cfd80c1eb   goharbor/harbor-registryctl:v2.9.0     "/home/harbor/start.…"   22 minutes ago   Up 22 minutes (healthy)                                           registryctl
015280b339bb   goharbor/harbor-db:v2.9.0              "/docker-entrypoint.…"   22 minutes ago   Up 22 minutes (healthy)                                           harbor-db
c2ce84e3f466   goharbor/registry-photon:v2.9.0        "/home/harbor/entryp…"   22 minutes ago   Up 22 minutes (healthy)                                           registry
036e8b510161   goharbor/harbor-portal:v2.9.0          "nginx -g 'daemon of…"   22 minutes ago   Up 22 minutes (healthy)                                           harbor-portal
02b5db894289   goharbor/redis-photon:v2.9.0           "redis-server /etc/r…"   22 minutes ago   Up 22 minutes (healthy)                                           redis
12809c87810f   goharbor/harbor-log:v2.9.0             "/bin/sh -c /usr/loc…"   22 minutes ago   Up 22 minutes (healthy)   127.0.0.1:1514->10514/tcp               harbor-log
``` 

```
  trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:v2.5.0
    restart: always
    cap_drop:
      - ALL
    depends_on:
      - log
      - redis
    networks:
      - harbor
    volumes:
      - type: bind
        source: /data/trivy-adapter/trivy
        target: /home/scanner/.cache/trivy
      - type: bind
        source: /data/trivy-adapter/reports
        target: /home/scanner/.cache/reports
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "trivy-adapter"
    env_file:
      ./common/config/trivy-adapter/env
``` 

ENV File:
```
SCANNER_LOG_LEVEL=info
SCANNER_REDIS_URL=redis://redis:6379/5?idle_timeout_seconds=30
SCANNER_STORE_REDIS_URL=redis://redis:6379/5?idle_timeout_seconds=30
SCANNER_STORE_REDIS_NAMESPACE=harbor.scanner.trivy:store
SCANNER_JOB_QUEUE_REDIS_URL=redis://redis:6379/5?idle_timeout_seconds=30
SCANNER_JOB_QUEUE_REDIS_NAMESPACE=harbor.scanner.trivy:job-queue
SCANNER_TRIVY_CACHE_DIR=/home/scanner/.cache/trivy
SCANNER_TRIVY_REPORTS_DIR=/home/scanner/.cache/reports
SCANNER_TRIVY_VULN_TYPE=os,library
SCANNER_TRIVY_SEVERITY=UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
SCANNER_TRIVY_IGNORE_UNFIXED=False
SCANNER_TRIVY_SKIP_UPDATE=False
SCANNER_TRIVY_OFFLINE_SCAN=False
SCANNER_TRIVY_GITHUB_TOKEN=
SCANNER_TRIVY_INSECURE=False
SCANNER_TRIVY_TIMEOUT=5m0s
HTTP_PROXY=
HTTPS_PROXY=
NO_PROXY=core,portal,localhost,log,chartmuseum,notary-server,notary-signer,127.0.0.1,nginx,registry,registryctl,redis,exporter,.local,jobservice,db,.internal,trivy-adapter,postgresql
``` 

Bu I can't see any scan report and trivy adapter gives me these error
```
2023-10-24T09:03:42Z [INFO] [/pkg/scan/job.go:387]: {
  "uuid": "53e8e759-6742-11ee-9f9a-0242ac140009",
  "name": "Trivy adapter",
  "description": "",
  "url": "http://trivy-adapter:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "Basic",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": true,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.24.2",
  "create_time": "2023-10-10T07:55:06.834135Z",
  "update_time": "2023-10-24T08:45:55.214925Z"
}
2023-10-24T09:03:42Z [INFO] [/pkg/scan/job.go:387]: {
  "registry": {
    "url": "http://core:8080",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 1,
    "repository": "library/minio",
    "tag": "RELEASE.2021-04-22T15-44-28Z",
    "digest": "sha256:4f39c3fa2ecf208c0df013e36883d25c3eb8a88ec10d6b1718c2f2b62a34c665",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2023-10-24T09:03:42Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2023-10-24T09:03:42Z [INFO] [/pkg/scan/job.go:224]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2023-10-24T09:03:44Z [INFO] [/pkg/scan/job.go:245]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2023-10-24T09:03:49Z [ERROR] [/pkg/scan/job.go:294]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: open /home/scanner/.cache/reports/scan_report_1395566209.json: permission denied: general response handler: unexpected status code: 500, expected: 200

``` 

How can I fix this issue.

Note: I create /home/scanner and give full permission of all users
