### ISSUE TITLE
Images not pullable due to wrong cache info in redis

### ISSUE THREAD

**Issue by chrifey** [goharbor/harbor#19695]
Hi,

we are facing an issue that occurs from time to time and we are stuck with it.

**Environment:**
Harbor 2.8.4
RHEL 8.8
3 Node HA Setup 
external redis (5.0.3) with redis sentinel
external postgres 13 with pgpool

<details>
  <summary>harbor.yml (redacted ansible template)</summary>
  
  ### Heading
  ```yaml
external_database:
  harbor:
    host: {{ postgresPcpVIP }}
    port: 9999
    db_name: {{ postgresHarborDbName }}
    username: {{ postgresHarborUser }}
    password: {{ harborDbPassword }}
    ssl_mode: disable
    max_idle_conns: 2
    max_open_conns: 0
  notary_signer:
    host: {{ postgresPcpVIP }}
    port: 9999
    db_name: {{ postgresNotarySignerDbName }}
    username: {{ postgresHarborUser }}
    password: {{ harborDbPassword }}
    ssl_mode: disable
    max_idle_conns: 2
    max_open_conns: 0
  notary_server:
    host: {{ postgresPcpVIP }}
    port: 9999
    db_name: {{ postgresNotaryServerDbName }}
    username: {{ postgresHarborUser }}
    password: {{ harborDbPassword }}
    ssl_mode: disable
    max_idle_conns: 2
    max_open_conns: 0

{% with redisHosts = namespace(entities=[]) %}
{% for redisHost in ansible_play_hosts_all %}
{% set redisHosts.entities = redisHosts.entities + [redisHost] %}
{% endfor %}

external_redis:
  host: {{ redisHosts.entities | join(':26379,') }}:26379
{% endwith %}
  sentinel_master_set: redis-cluster 
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  trivy_db_index: 5
  idle_timeout_seconds: 30

data_volume: /data

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

{% if harborTrivyEnable %}
trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false
{% endif %}

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

metric:
  enabled: true
  port: 9090
  path: /metrics

{% if harborS3StorageServiceEnabled %}
storage_service:
  s3:
    accesskey: {{ harborS3StorageService.accesskey }}
    secretkey: {{ harborS3StorageService.secretkey }}
    region: {{ harborS3StorageService.region }}
    regionendpoint: {{ harborS3StorageService.regionendpoint }}
    bucket: {{ harborS3StorageService.bucket }}
    encrypt: {{ harborS3StorageService.encrypt }}
    secure: {{ harborS3StorageService.secure }}
    v4auth: {{ harborS3StorageService.v4auth }}
    chunksize: {{ harborS3StorageService.chunksize }}
    multipartcopychunksize: {{ harborS3StorageService.multipartcopychunksize }}
    multipartcopymaxconcurrency: {{ harborS3StorageService.multipartcopymaxconcurrency }}
    multipartcopythresholdsize: {{ harborS3StorageService.multipartcopythresholdsize }}
    rootdirectory: {{ harborS3StorageService.rootdirectory }}
{% endif %}
  ```
</details>

The issue looks like the following:
- Image is uploaded to registry
- Client pulls image
  - From time to time gets `filesystem layer verification failed for digest sha256:******cb5e` error

The problematic blob is existing in the Postgres DB and also in the S3 storage (**with the correct checksum**)

```
harbor_int=> select * from artifact_blob where digest_blob = 'sha256:******cb5e';
   id    |                                digest_af                                |                               digest_blob                               |       creation_time
---------+-------------------------------------------------------------------------+-------------------------------------------------------------------------+----------------------------
 2331089 | sha256:******cb5e | sha256:******cb5e | 2023-11-06 11:50:35.855172
(1 row)
```

While debugging the logs we found, that the proxy in the problematic case is answering the HEAD and GET queries with "200 0", which means 0 bytes for the requested blob.

We then search in Redis and are now pretty sure that all constellations of non-pullable images are due to incorrect cache information in Redis. In every case we investigated, the Redis query for blob hashes of a "defective" image returned the value "0" for the key "size". After deleting the Redis entry, the image is immediately pullable. 

The issue we now have is, that we do not know under which circumstances this happens or how we can further debug this issue.

We are happy about any further suggestions.
