### ISSUE TITLE
Facing docker retry push when harbor is backed by s3, some multipartupload in progress and no logs 

### ISSUE THREAD

**Issue by syldej** [goharbor/harbor#19755]
Hi everyone!

Does anyone faced a docker push <harbor>/group/repo:tag issue when harbor is backed by an external S3 as storage solution ?
- Here my working configuration on Azure, but not working in a air-gapped environment
```
storage_service:
 s3:
   accesskey: <masked>
   secretkey: <masked>
   region: luxembourg
   regionendpoint: s3-<masked>.com
   bucket: registry-onazure
   encrypt: false
   secure: true
   v4auth: true
   chunksize: 5242880
   multipartcopychunksize: 33554432
   multipartcopymaxconcurrency: 100
   multipartcopythresholdsize: 5368709120
   rootdirectory: /s3/object/name/prefix
 redirect:
   disabled: false

```
- the S3 IAM Policy is allowing everything
- The docker push <> pushed some content, but always retry, at the bucket level, the directory is well created /s3/object/name/prefix
and see current multipartuploads in progress, and finally the docker push command end with an EOF

Any help is welcome !
Thanks & Regards
