### ISSUE TITLE
failed to verify certificate when pod is pulling image

### ISSUE THREAD

**Issue by vodanet** [goharbor/harbor#19832]
Hi,
i have: 

- habor version: v2.10.0-6abb4eab
- kubernetes: v1.26.11+k3s2
- container runtime: containerd://1.7.7-k3s1.26

I have a K3S cluster with 3 nodes.
I use Traefik as ingress controller.

The installation of Harbor was successful (all pods running).
Harbor is used internally as an insecure registry - so I'm not using any certificates at the moment.

On each node I entered the following in /etc/docker/daemon.json:
```
{
"insecure-registries" : ["registry.<hostname>", "192.168.3.205", "<hostname>"]
}
```

On each node I can log in to the harbor registry with docker login and pull images.

E.g.:
```
docker pull <hostname>/testprojekt/hello-world
Using default tag: latest
latest: Pulling from testprojekt/hello-world
c1ec31eb5944: Already exists
Digest: sha256:d37asd45d47ad12441c205a938129df7a3e52345828b4fa27b03a98825d1e2e7
Status: Downloaded newer image for registry.<hostname>/testprojekt/hello-world:latest
registry.<hostname>/testprojekt/hello-world:latest
```

I created the image-pull-secret for Kubernetes as follows:
`kubectl create secret docker-registry regcred --docker-server=<registry.hostname> --docker-username=<name> --docker-password=<pword> --docker-email=<email>`

(same LOGIN data as I used on the nodes for Docker login)

But if I create a POD that is supposed to pull this image then it doesn't work:
```
apiVersion: apps/v1
child: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: hello

        image: registry.<hostname>/testprojekt/hello-world:latest
        command:
          - "sleep"
          - "604800"
        imagePullPolicy: Always
```

I get the message:
`Failed to pull image "registry.<hostname>/testprojekt/hello-world:latest": rpc error: code = Unknown desc = failed to pull and unpack image "registry.<hostname>/testprojekt/hello-world:latest": failed to resolve reference "registry.<hostname>/testprojekt/hello-world:latest": failed to do request: Head "https://registry.<hostname>/v2/testprojekt/hello-world/manifests/latest": tls: x509: certificate signed by unknown authority
`
Thank you very much for the help!!
Daniel

[harbor.zip](https://github.com/goharbor/harbor/files/13903491/harbor.zip)
