### ISSUE TITLE
The internal_tls.strong_ssl_ciphers options doesn't work in harbor.yml

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#19912]
In PR: https://github.com/goharbor/harbor/pull/16990/files, it introduced an option to enable strong cipher suites in nginx.conf of portal and nginx
```
internal_tls:
  enabled: true
  dir: /etc/harbor/tls/internal
  strong_ssl_ciphers: true
```

But after enable this option, the cipher suite doesn't change after prepare command
