### ISSUE TITLE
provide official harbor dashboard via grafana website

### ISSUE THREAD

**Issue by volker-raschek** [goharbor/harbor#19948]
**Is your feature request related to a problem? Please describe.**

Yes, I've deployed grafana via the prometheus operator stack. The deployment of grafana has a feature to download dashboards from custom resources - for example via url, grafana net id or as raw json. For example: 

```
dashboards:
    default:
      # some-dashboard:
      #   json: |
      #     $RAW_JSON
      # custom-dashboard:
      #   file: dashboards/custom-dashboard.json
      # local-dashboard:
      #   url: https://example.com/repository/test.json
      #   token: ''
      # local-dashboard-base64:
      #   url: https://example.com/repository/test-b64.json
      #   token: ''
      #   b64content: true
      # local-dashboard-gitlab:
      #   url: https://example.com/repository/test-gitlab.json
      #   gitlabToken: ''
      # local-dashboard-bitbucket:
      #   url: https://example.com/repository/test-bitbucket.json
      #   bearerToken: ''
      # local-dashboard-azure:
      #   url: https://example.com/repository/test-azure.json
      #   basic: ''
      #   acceptHeader: '*/*'
      argocd:
        gnetId: 14584
        revision: 1
        datasource: Prometheus
```
 
The current problem is, that the dashboard located in [contrib](https://raw.githubusercontent.com/goharbor/harbor/main/contrib/grafana-dashboard/metrics-example.json) leads to an EOF error: 

```text
logger=provisioning.dashboard type=file name=default t=2024-02-04T17:05:31.128692475Z level=error msg="failed to load dashboard from " file=/var/lib/grafana/dashboards/default/harbor.json error="unexpected EOF"
```   

**Describe the solution you'd like**

For me it is not clear why to "official" grafana dashboard is hidden as part of this project inside the `contrib` directory. Furthermore, DevOps teams search initially after official grafana dashboards via the grafana dashboard website. There are some unofficial dashboards, where the DevOps team take the risk, that the dashboard could be unmaintained, when a newer version of harbor breaks the dashboard.

Reagarding the import mechanism, which leads to the EOF error - if the dashboard is located via the grafana dashboard website, the dashboard receives a dashboard id like `gnetId` and a `revision`. Via this information, a reproducible deployment can be guaranteed, because currently by using the rawURL directly can be leads to incompatibility between dashbord and harbor version. 

So, please provide the dashboard via the grafana dashboard website and make it possible for devops engineers to setup a reproducible deployment of a grafana dashboard. Maybe it is possible to upload the dashboard from GitHub to the grafana website via the CI.

  Volker
