### ISSUE TITLE
Can not create config maps when install Harbor on Kubernetes ( v1.3.3 ), error message show " the ConfigMap  is invalid "

### ISSUE THREAD

**Issue by willstudy** [goharbor/harbor#2009]
At first, modify some basic configs, included `make/harbor.cfg`,`make/kubernetes/**/*.rc.yaml` and so on.

Then I run this command
```
python make/kubernetes/prepare
```
and some files generated. But some errors happens when I exec
```
kubectl apply -f make/kubernetes/jobservice/jobservice.cm.yaml
```
Output is 
```
[root@XXX ]# kubectl apply -f make/kubernetes/jobservice/jobservice.cm.yaml
The ConfigMap "harbor-jobservice-config" is invalid.

* data[MYSQL_PORT]: Invalid value: "MYSQL_PORT": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[REGISTRY_URL]: Invalid value: "REGISTRY_URL": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[SECRET_KEY]: Invalid value: "SECRET_KEY": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[EXT_ENDPOINT]: Invalid value: "EXT_ENDPOINT": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[GODEBUG]: Invalid value: "GODEBUG": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
* data[LOG_LEVEL]: Invalid value: "LOG_LEVEL": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```
```make/kubernetes/jobservice/jobservice.cm.yaml``` file output:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "rponline"
  UI_SECRET: "xGmyDfwYbwUPLcVX"
  SECRET_KEY: "0GFvILdJ5Wj7oJkQ"
  CONFIG_PATH: /etc/jobservice/app.conf
  REGISTRY_URL: http://registry:5000
  VERIFY_REMOTE_CERT: "on"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  LOG_DIR: /var/log/jobs
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: "http:/XXX.com"
  TOKEN_URL: http://ui
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
```

Could anyone help me? Thanks very much.

**Comment by reasonerjt** [comment]
@ScorpioCPH could you help?

**Comment by ScorpioCPH** [comment]
@kdada

**Comment by kdada** [comment]
Please give the kubectl version:
```
$ kubectl version
```

**Comment by willstudy** [comment]
Output 
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:29:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:22:25Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
@kdada

**Comment by kdada** [comment]
We have tested in kubernetes 1.4 and 1.5, The ConfigMap can be created successfully. May be it's a limitation of kubernetes 1.3 ( We have no cluster versioned 1.3 to test).

You can modify those keys in data to satisfy the requirements as a workaround.

**Comment by willstudy** [comment]
Thanks for your reply. I will have a try on other k8s version.

**Comment by willstudy** [comment]
Can create config maps in kubernetes 1.5.6, but errors occurred when created rc using these config maps.
```
# kc get configmaps
NAME                       DATA      AGE
harbor-jobservice-config   16        3m
harbor-mysql-config        1         3m
harbor-nginx-config        3         3m
harbor-registry-config     2         3m
harbor-ui-config           30        3m
```
Errors
```
# kubectl apply -f make/kubernetes/mysql/mysql.rc.yaml
The ReplicationController "mysql-rc" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```
The `harbor-mysql-config` output is
```
# kc describe configmaps harbor-mysql-config 
Name:		harbor-mysql-config
Namespace:	default
Labels:		<none>
Annotations:	<none>

Data
====
MYSQL_ROOT_PASSWORD:	8 bytes
```
The `mysql.cm.yaml` output is 
```
# cat make/kubernetes/mysql/mysql.cm.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-mysql-config
data:
  MYSQL_ROOT_PASSWORD: rponline
```
Kubernetes version 
```
#  kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:54:20Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
@kdada  Could you help me what's wrong with the problem ？ Thanks very much
