### ISSUE TITLE
Harbor registry / Jobservice Pod doesn't restart after change

### ISSUE THREAD

**Issue by didlawowo** [goharbor/harbor#20149]
If you are reporting a problem, please make sure the following information are provided:

i have installed harbor on my k3S cluster with longhorn
it's seems the harbor try to update the pod for something, but the old pod doesn't release the pvc, then the new pod don't get it and don't start. i don't have another problem with pvc in the cluster when config change, only with harbor

<img width="1629" alt="image" src="https://github.com/goharbor/harbor/assets/12622760/5613a559-6d9d-4680-b028-9ccc0005a766">

<img width="1629" alt="image" src="https://github.com/goharbor/harbor/assets/12622760/7d406fd0-fdb1-4624-972e-8ec0b36661c9">

**Steps to reproduce the problem:**
install harbor with bitnami helm chart and wait for update

**Versions:**
latest harbor

k3S 1.28
longhorn 1.6

**Additional context:**

no log with error cause pod is container starting

my config 

```
   repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.1.2
    chart: harbor
    helm:
      values: |
        exposureType: ingress
        jobservice:
          nodeSelector:
            kubernetes.io/arch: amd64

        trivy:
          enabled: false
        externalURL: https://harbor-registry.home.oursain.net
        logLevel: warn
        adminPassword: "admin"
        service:
          type: ClusterIP
        redis:
          master:
            nodeSelector:
              kubernetes.io/arch: amd64
        core:
          nodeSelector:
            kubernetes.io/arch: amd64
        persistence:
          persistentVolumeClaim:
            registry:
              size: 50Gi
          imageChartStorage:
            type: filesystem
            gcs:
              bucket: dc-consulting-home-harbor
              existingSecret: "harbor-gcp-secret"

        ingress:
          core:
            hostname: harbor-registry.home.oursain.net
            tls: true
            ingressClassName: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
```
