### ISSUE TITLE
CentOS7 docker installed error: Network harbor_harbor  Error

### ISSUE THREAD

**Issue by yezihack** [goharbor/harbor#20260]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
![image](https://github.com/goharbor/harbor/assets/11530866/4a12c6d0-96d0-4f0c-a1a5-a81722b7b1e9)

**Steps to reproduce the problem:**
1. CentOS7 
Linux kube31 3.10.0-1160.71.1.el7.x86_64 1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

2. install redis 
```sh
docker pull redis:7.0.11

mkdir -p /data/redis/data/

cat <<EOF |tee /data/redis/redis.conf
bind 0.0.0.0
port 6379
requirepass eo5HLdBByQEx4L4b
appendonly yes
daemonize no
dir /data
dbfilename dump.rdb
appendfilename "appendonly.aof"
EOF

docker run  -d  -p 6379:6379 --restart=always --name redis \
    -v /data/redis/data/:/data \
    -v /data/redis/redis.conf:/etc/redis.conf redis:7.0.11 \
    redis-server /etc/redis.conf 
```
4. generate domain ssl 

```sh
mkdir -p /data/harbor/{data,logs}
mkdir -p /data/certs
openssl req -newkey rsa:2048 -nodes -keyout harbor.k8s.io.key -x509 -days 5 \
        -out harbor.k8s.io.crt -subj "/C=CN/ST=Beijing/L=Beijing/O=Kubernetes/OU=K8S/CN=harbor.k8s.io"
```

5.  use external redis

```sh
  host: 192.168.1.100:6379
  password: eo5HLdBByQEx4L4b
```

6. harbor.yml

```yml
hostname: harbor.k8s.io
http:
  port: 80
https:
  port: 443
  certificate: /data/certs/harbor.k8s.io.crt
  private_key: /data/certs/harbor.k8s.io.key
harbor_admin_password: eo5HLdBByQEx4L4b

database:
  password: eo5HLdBByQEx4L4b
  max_idle_conns: 100
    
  max_open_conns: 900
  conn_max_lifetime: 5m
  conn_max_idle_time: 0

data_volume: /data/harbor/data

trivy:
  ignore_unfixed: false
  skip_update: false
  skip_java_db_update: false
  offline_scan: false
  security_check: vuln
  insecure: false

jobservice:
  max_job_workers: 10
  job_loggers:
    - STD_OUTPUT
    - FILE
  logger_sweeper_duration: 1 
notification:
  webhook_job_max_retry: 3
  webhook_job_http_client_timeout: 3 
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /data/harbor/logs

_version: 2.10.0
external_redis:
  host: 192.168.1.100:6379
  password: eo5HLdBByQEx4L4b
  registry_db_index: 1
  jobservice_db_index: 2
  trivy_db_index: 5
  idle_timeout_seconds: 30

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

metric:
  enabled: true
  port: 9090
  path: /metrics

upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false
cache:
  enabled: false
  expire_hours: 24

```

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.10.1]
- docker engine version: [20.10.18]
- docker-compose version: [2.3.4]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
