### ISSUE TITLE
harbor pulls all version numbers to docker every time a copy task is executed. Even though these version numbers have been synchronized

### ISSUE THREAD

**Issue by OMS-ZH** [goharbor/harbor#20392]
![image](https://github.com/goharbor/harbor/assets/43334788/c8752ebd-574f-43fc-a555-1b15da5008af)

harbor pulls all version numbers to docker every time a copy task is executed. Even though these version numbers have been synchronized, it still goes back to synchronization, adding m images, n versions, and each copy requires m*n pull requests to the target repository. This is very inefficient, and there are a lot of unnecessary requests

**Comment by MinerYang** [comment]
Hi @OMS-ZH ,
Could you try to enable `cache layer configurations`
```
# Cache layer configurations
# If this feature enabled, harbor will cache the resource
# `project/project_metadata/repository/artifact/manifest` in the redis
# which can especially help to improve the performance of high concurrent
# manifest pulling.
# NOTICE
# If you are deploying Harbor in HA mode, make sure that all the harbor
# instances have the same behaviour, all with caching enabled or disabled,
# otherwise it can lead to potential data inconsistency.
cache:
  # not enabled by default
  enabled: false
  # keep cache for one day by default
  expire_hours: 24
```
