### ISSUE TITLE
Image pull issue from Harbor registry which is deployed on the same cluster.

### ISSUE THREAD

**Issue by Leela-SR** [goharbor/harbor#20524]
Hi Harbor Team,

We plan to have a local container registry in the same cluster where our applications are running. We need this local container registry to support the network disconnections.

I have deployed Harbor in our cluster as local container registry and was able to successfully pull and push images from outside the cluster through nodePort and ingress service types.
However, this is not our use case. We need to pull the images within the cluster for which I am making use of "harbor core" service to access the repositories. Note: I have tried it with image pull secret where un: admin, pw: Harbor12345 url: http://test-harbor-core.harbor.svc:80
example:
![image](https://github.com/goharbor/harbor/assets/112939073/6d334571-1218-4cb9-a113-02248cb6a738)

When I try to deploy the pod, I get following error:
![image](https://github.com/goharbor/harbor/assets/112939073/590b089b-2ae9-4a44-b8a4-aa11871b3761)

Could you please let us if we are missing anything? Is any configuration is missing? i am able to ping harbor.core service pod from other pods successfully.

NOTE: When exposed through NodePort or Ingress from cluster, I am successfully pulling the images from Harbor container registry.
![image](https://github.com/goharbor/harbor/assets/112939073/97dcdda7-99f5-4c19-ae7f-1c1b4b66fcb1)

Our Configuration:
Kubernetes version: v1.28.9+rke2r1

**Comment by Kajot-dev** [comment]
That would seem like some DNS issue in your k8s cluster since it fails to lookup the hostname. Connection to the harbor registry is not even made

Also, you're trying to access port 80 over https. I would strongly recommend using harbor's internal tls for this one

**Comment by stonezdj** [comment]
Please don't use service name to serve Harbor service, because you should always pull image through externalURL

**Comment by Leela-SR** [comment]
@stonezdj  Why we can't access harbor service through service Type Cluster IP (internal to cluster). Generally, if it is ClusterIP, we generally access it through service name right? We don't want to expose registry outside cluster due to security issues.

**Comment by stonezdj** [comment]
When pulling image from Harbor, it always request the bearer token via `<externalURL>/service/token`, if you are using the service name, the pull request fail to get the bearer token.

**Comment by Leela-SR** [comment]
@stonezdj
 I have set the EXT_ENDPOINT and deployed harbor with serviceType = clusterIP
 https://harbor:443 ( tried with http://harbor:80 as well)
 When I try to deploy a pod where the image is pulled from harbor registry, i am getting this error.
![image](https://github.com/goharbor/harbor/assets/112939073/166866c8-0613-45e4-b984-b98b3e749000)

It starts referencing the image from docker.io. Could you please let us know why it is pointing to "docker.io/harbor/ix/test/redis:latest

Am I missing any configuration here?

my pod deployment file is:
![image](https://github.com/goharbor/harbor/assets/112939073/50781da3-3b8d-4aab-ac6d-974467c4d477)

Created Kubernetes image secret object using following:
registry server: https://harbor:433
un: admin
pw: Harbor12345

**Comment by JasonGoldhill** [comment]
@Leela-SR did you ever figure this out? I am trying to do something similar (use harbor as a local image cache on my cluster), but getting the same "no such host" error when trying to pull an image through the local service address (harbor.harbor.svc.cluster.local/{project-name}/{repository}:{tag})

**Comment by eXist-FraGGer** [comment]
Guys, the same issue and no any information:

harbor-secret.yaml:
```yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: apps
  name: harbor-secret
stringData:
  .dockerconfigjson: |
    {"auths":{"harbor-core.harbor.svc.cluster.local":{"username":"admin","password":"adminpswd"}}}
type: kubernetes.io/dockerconfigjson
```

deployment.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: api
          image: harbor-core.harbor.svc.cluster.local/apps/api:latest
          imagePullPolicy: Always
```

The result:
```shell
Failed to pull image "harbor-core.harbor.svc.cluster.local/apps/api:latest": Error response from daemon: Get "https://harbor-core.harbor.svc.cluster.local/v2/": dial tcp: lookup harbor-core.harbor.svc.cluster.local: Temporary failure in name resolution
```

**But it works with Istio if I create Virtual Service and open a tunnel**.
This is not good as I always have to open tunnel to start my infrastructure...
