### ISSUE TITLE
panic: bad _REDIS_URL_CORE

### ISSUE THREAD

**Issue by linonetwo** [goharbor/harbor#20638]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I get this after install from helm

```
panic: bad _REDIS_URL_CORE
goroutine 1 [running]:
main.main()
 /harbor/src/core/main.go:135 +0x1278
```

**Steps to reproduce the problem:**

In a fresh install with external redis, with value

```yaml
redis:
  type: external
  external:
    addr: "10.100.1.60:6379"
    username: ""
    password: ""
    # If using existingSecret, the key must be REDIS_PASSWORD
    existingSecret: "redis-default-password"
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.10.2  / 1.14.2

**Additional context:**
