### ISSUE TITLE
can't use group members with OIDC Google

### ISSUE THREAD

**Issue by fatsolko** [goharbor/harbor#20719]
I create OIDC authentication with Google and add user in Google to group `devops`
![image](https://github.com/goharbor/harbor/assets/76652885/cddb8a33-0204-4d0d-aa0c-46a5103ddee8)
After adding group member to project I expected user to have access to project docker.
![image](https://github.com/goharbor/harbor/assets/76652885/237afda8-b0a1-4a07-bdb4-eaa574c51097)
![image](https://github.com/goharbor/harbor/assets/76652885/cf61b131-ed09-4927-8cbf-902f6e6bc489)
but it doesn't work, I only see the public project
![image](https://github.com/goharbor/harbor/assets/76652885/ea324296-35d6-4625-8706-bab3d67c3a49)

What am I doing wrong?

**Comment by fatsolko** [comment]
I think the main problem is not being able to get groups from Google account.
I don't know which scope should work.

**Comment by stonezdj** [comment]
You should set the `Group Claim Name`

`Group Claim Name: The name of a custom group claim that you have configured in your OIDC provider, that includes the groups to add to Harbor.`

see: https://goharbor.io/docs/edge/administration/configure-authentication/oidc-auth/#configure-an-oidc-provider-in-harbor

**Comment by fatsolko** [comment]
> You should set the `Group Claim Name`
> 
> `Group Claim Name: The name of a custom group claim that you have configured in your OIDC provider, that includes the groups to add to Harbor.`
> 
> see: https://goharbor.io/docs/edge/administration/configure-authentication/oidc-auth/#configure-an-oidc-provider-in-harbor

yes, but google does not provide group scope
for example: there is log when I set Group Claim Name groups
`2024-07-10T07:10:23Z [WARNING] [/pkg/oidc/helper.go:394]: Unable to get groups from claims, claims: map[email:some@py.com email_verified:true family_name:some given_name:some hd:py.com name:some picture:https://lh3.googleusercontent.com/a/ACg8ocKi_Ub65nJIOAbVEu3AUSNWpEC7pHeI=s96-c sub:11286363274952], groups claims key: groups`

**Comment by mmonaco** [comment]
I think you have three problems:

 1. You'd want the full group name: `devops@????`.
 2. The scope should have `https://www.googleapis.com/auth/cloud-identity.groups.readonly`
 3. Discussed in https://github.com/goharbor/harbor/issues/13609, support for google groups seems to be broken in Harbor, possibly because scopes that are a full URL (instead of a simple string) are broken.

**Comment by webertrlz** [comment]
This is a real, old issue, is there any expectation to fix it?

**Comment by mmonaco** [comment]
Still relevant

**Comment by paretl** [comment]
Hello, this is still an issue and it could be useful for a lot of people 
Any news about that? @wy65701436 @reasonerjt 
Thanks :pray:

**Comment by rchekhina** [comment]
Still relevant

**Comment by franzudev** [comment]
I'm interested too

**Comment by fatsolko** [comment]
Still relevant

**Comment by rchekhina** [comment]
HI,

Still relevant.

Best regards.

**Comment by discostur** [comment]
Hi, 
would be really nice +1

Thanks

**Comment by Macbet** [comment]
as a workaround we use dex as OIDC provider ( it support a google groups )

**Comment by rchekhina** [comment]
HI @Macbet 

Can you explain how you did it please ?

Best regards.

**Comment by Macbet** [comment]
@rchekhina 
Sure. 
this oidc config from harbor

<img width="598" height="717" alt="Image" src="https://github.com/user-attachments/assets/a81fe7f7-796a-4845-89c8-f84011ce1b02" />


i deploy in k8s dex with /dex path for main domain of harbor
and this config from dex
```yaml
config:
    issuer: https://yourdomain.org/dex
    storage:
      type: postgres
      config:
        host: localhost
        port: 5432
        database: dex_db
        user: dex
        password: $DEX_DB_PASSWORD
        ssl:
          mode: require
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*'] 
    oauth2:
      skipApprovalScreen: true
      alwaysShowLoginScreen: false

    staticClients:
    - id: harbor # This is the client ID Harbor will use to connect to Dex
      redirectURIs:
        - https://yourdomain.org/c/oidc/callback # Replace with your Harbor's OIDC callback URL
      name: "Harbor"
      secretEnv: CLIENT_SECRET # A shared secret between Dex and Harbor
    connectors:
    - type: google
      id: google # Unique ID for this connector
      name: google
      config:
        clientID: $GOOGLE_CLIENT_ID # Your OAuth 2.0 Client ID from Google Cloud
        clientSecret: $GOOGLE_CLIENT_SECRET # Your OAuth 2.0 Client Secret from Google Cloud
        redirectURI: https://yourdomain.org/dex/callback # Dex's callback URL for Google
        serviceAccountFilePath: /etc/gcp/secret/gcp-credentials # Path to your service account JSON key file
        domainToAdminEmail:
            "*": devops@yourdomain.org
        hostedDomains: ["yourdomain.org"] # Replace with your domain and a super admin email
```
and now harbor login not direct throw google but throw dex and dex can fetch groups from google
