### ISSUE TITLE
Unable to docker login 

### ISSUE THREAD

**Issue by parliament718** [goharbor/harbor#20773]
Have been trying to login to Harbor via docker cli, to no avail. 

I'm able to login throught the Web interface via https://harbor.mysite.com using the admin account. 

Likewise I'm able to list projects via 

```curl -u 'admin:my-admin-pass' https://harbor.mysite.io/api/v2.0/projects```

However, I'm not able to login via CLI and robot account:
 `docker -D login https://harbor.mysite.io -u 'robot$test' -p 'robot-password'`, fails with: 

> Error response from daemon: Get "https://harbor.mysite.io/v2/": received unexpected HTTP status: 521

I'm not sure why 521, but if i print Harbor's nginx logs it prints on every login attempt:

> 192.168.100.11 - "GET /v2/ HTTP/1.0" 401 76 "-" "docker/25.0.2 go/go1.21.6 git-commit/fce6e0c kernel/6.6.12-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/25.0.2 \x5C(darwin\x5C))" 0.003 0.003 .

So that's a 401 error.

To fully understand my setup: I have my own Nginx running with SSL termination and trusted certificates. My Nginx gets requests via HTTPS and proxies them to Harbor's internal IP address via HTTP:

```
location / {
   if ($host = harbor.mysite.io) {
       proxy_pass http://192.168.100.23;
    }
}
```

This works insofar as I can access Harbor's WebUI via HTTPS just fine.

Here's my `harbor.yml`:

```
hostname: harbor.mysite.io
http:
  port: 80
external_url: https://harbor.mysite.io                    <== tried this
harbor_admin_password: my-admin-pass
registry:  
  relativeurls: true                                                   <== tried this
database:
  password: my-admin-pass
  max_idle_conns: 100
  max_open_conns: 900
  conn_max_lifetime: 5m
  conn_max_idle_time: 0

data_volume: /data

trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  security_check: vuln
  insecure: false

jobservice:
  max_job_workers: 10
  logger_sweeper_duration: 1 #days

notification:
  webhook_job_max_retry: 3
  webhook_job_http_client_timeout: 3 #seconds

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 2.8.0 #Do not modify

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false

cache:
  enabled: false
  expire_hours: 24
```

Why can't I connect via docker cli?
