### ISSUE TITLE
No S3 registry storage support for eu-central-2

### ISSUE THREAD

**Issue by tschlaepfer** [goharbor/harbor#20789]
**Expected behavior and actual behavior:**
When configuring S3 as the storage backend for the Harbor registry, the registry pod returns the following error message, indicating that the eu-central-2 region is not supported. 
```
panic: invalid region provided: eu-central-2
```

The code should be updated to support the latest AWS regions, https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints 

**Steps to reproduce the problem:**
Configure the image chart storage to use s3 in the eu-central-2 region. 
```
persistence:
  imageChartStorage:
    type: s3
    s3:
      region: eu-central-2
```

**Versions:**
Please specify the versions of the following systems.

- harbor version: v2.11.0

**Comment by tschlaepfer** [comment]
When specifying the regional endpoint, the eu-central-2 region can be used. 
```
persistence:
  imageChartStorage:
    type: s3
    s3:
      [...]
      region: eu-central-2
      regionendpoint: https://s3.eu-central-2.amazonaws.com
```
