### ISSUE TITLE
Unable to see job logs while they are running

### ISSUE THREAD

**Issue by atchadwick** [goharbor/harbor#20821]
I'm using 2.11 and latest helm chart

I have the job service log to database, while a job is running if I try to view a log it says object not found however on completion I can then see the log however this isn't great for me for troubleshooting issues or checking progress. 

As this is potentially as per design is there a better/recommended solution to be able to see logs as they are being streamed or at least on point of viewing the object. 

Also is there a location I can see the actual progress of say a garbage collection log I have looked around the pod logs and inside the pods and can't see anything although I am probably missing something here any help would be appreciated, I don't have a hard requirement on database if that's the solution but I would prefer to keep it as most of the pods are ephemeral.

**Comment by stonezdj** [comment]
Please go to the Job Service Dashboard and select the workers and you can find the job in the worker, and there is a log link, you can check when it is running

**Comment by atchadwick** [comment]
Yea the issue is when I do that I get no object 

```
{
    "errors": [
        {
            "code": "NOT_FOUND",
            "message": "{\"code\":10010,\"message\":\"object is not found\",\"details\":\"log entity: 90dbfded4000f104a0a5af05\"}"
        }
    ]
}

```
Once the job completes I can then see the log 

 Error from the job pod:

```
2024-08-08T08:00:28Z [WARNING] [/pkg/joblog/dao/dao.go:66]: no job log founded. Query condition, uuid: 90dbfded4000f104a0a5af05, err: no job log founded
2024-08-08T08:00:28Z [ERROR] [/jobservice/api/handler.go:291]: Serve http request 'GET /api/v1/jobs/90dbfded4000f104a0a5af05/log' error: 404 {"code":10010,"message":"object is not found","details":"log entity: 90dbfded4000f104a0a5af05"}
```

Snipped of the yaml for the jobservice

```
jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.11.0
  replicas: 3
  revisionHistoryLimit: 10
  # set the service account to be used, default if left empty
  serviceAccountName: ""
  # mount the service account token
  automountServiceAccountToken: false
  maxJobWorkers: 20
  # The logger for jobs: "file", "database" or "stdout"
  jobLoggers:
    - database
  # The jobLogger sweeper duration (ignored if `jobLogger` is `stdout`)
  loggerSweeperDuration: 14 #days
  notification:
    webhook_job_max_retry: 3
    webhook_job_http_client_timeout: 3 # in seconds
  reaper:
    # the max time to wait for a task to finish, if unfinished after max_update_hours, the task will be mark as error, but the task will continue to run, default value is 24
    max_update_hours: 24
    # the max time for execution in running state without new task created
    max_dangling_hours: 168
```

Do I need to enable file to see streaming and database for the end result?

**Comment by stonezdj** [comment]
Was this job executed 24 hours ago, the job service reaper all the execution and task exceed 24 hour and result in the not found error.

Please update the configuration and restart Harbor. use the file logger for job service and change the max_update_hours to 168.

```
jobLoggers:
    - file
 ...

reaper:
   max_update_hours: 168
   max_dangling_hours: 168
```
