### ISSUE TITLE
Configure the harbor network at install time

### ISSUE THREAD

**Issue by yilas** [goharbor/harbor#20866]
Hello 👋🏻 

I have a VM located in a DMZ with an address in the 172.20.0.0/24 subnet. I need to access a Harbor instance hosted on a different VM with a completely different address. The issue I'm facing is that the network created by Docker Compose uses a range within `172.20.0.0/16`, which is causing conflicts.

Is there a way to designate a specific network for the Harbor deployment, rather than having to adjust the Docker daemon settings initially ?

We could imagine a specific configuration in the `harbor.yml` for the network. For instance : 

```yaml
networks:
  harbor:
    subnet: 172.22.0.0/16
    gateway: 172.22.0.1
```

which might render the following docker-compose file : 

```yaml
networks:
  harbor:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
```

Thank you for your help !
