### ISSUE TITLE
helm install harbor by default,error The username or password is incorrect.,

### ISSUE THREAD

**Issue by wangchao732** [goharbor/harbor#21052]
harbor registry all v2.11.1

setup:

1、helm upgrade --install harbor harbor/harbor --namespace harbor --create-namespace
2、all server running is health
3、look all server logs not error info
![1729056538159](https://github.com/user-attachments/assets/97471af4-4f19-4900-8f06-f5355f202cc4)

![1729056513764](https://github.com/user-attachments/assets/ec98cc90-1cf5-433a-8c11-0c22dc66ecfb)

![image](https://github.com/user-attachments/assets/2adb104a-569b-4220-a304-0ef2175a0470)

![1729056247284](https://github.com/user-attachments/assets/fa2cd3bb-8e66-4443-b95c-5139ce4b9ef2)

need help ! thanks ！

**Comment by wangchao732** [comment]
![image](https://github.com/user-attachments/assets/0d7d519f-bb6a-4b44-bb15-198786e8fedc)

**Comment by another-novelty** [comment]
For me, it was an issue with the ingress.

Check if `/api`, `/service`, `/v2`, `/chartrepo` and `/c` all point to the `harbor-core` service, instead of the `harbor-portal` service.

```
  - match: Host(`YOUR_HARBOR_URL_HERE`)
    kind: Rule
    services:
    - name: harbor-portal
      namespace: harbor
      port: 80
  - match: Host(`YOUR_HARBOR_URL_HERE`) && PathRegexp(`^/(api|service|v2|chartrepo|c)/`)
    kind: Rule
    services:
    - name: harbor-core
      namespace: harbor
      port: 80
```
