### ISSUE TITLE
Using a proxy for the portal.

### ISSUE THREAD

**Issue by p1r4t3-s4il0r** [goharbor/harbor#21256]
First of all, I would like to apologize as the answer of my question might be very easy...

I would like to access the portal page on my browser without having to enter a port (eg:`https://local.lan/registery`). But I can't get it working, I'm always hitting 502.

I can access harbor on `http//local.lan:9012` and it redirects me on `https://local.lan:9013` (as intended). I can also directly access it from `https://local.lan:9013`. However, when trying `http://local.lan/registery` it redirects me on `https://local.lan/registery` (as intented) but right on this page I keep getting error 502. The same happens on `https://local.lan/registery`.

Could you have a look and tell me what I'm doing wrong ? Especially with `hostname` and `external_url`.

harbor.yml

```yml
# Configuration file of Harbor

# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: local.lan

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 9012

# https related config
https:
  # https port for harbor, default is 443
  port: 9013
  # The path of cert and key files for nginx
  certificate: /home/[...]/harbor/cert/harbor.crt
  private_key: /home/[...]/harbor/cert/harbor.key
  # enable strong ssl ciphers (default: false)
  # strong_ssl_ciphers: false

# Uncomment external_url if you want to enable external proxy
# And when it enabled the hostname will no longer used
# external_url: http://local.lan

```

nginx.conf

```conf
location /registery/ {
        rewrite ^/registery(.*)$ $1 break;
        proxy_pass http://127.0.0.1:9012/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
    }
```

Thank you very much for your time.

**Comment by SterhLight** [comment]
hello my friend. I see your installation method, but I would like to make sure, are you installing harbor via compose? If so, then by doing docker -ps, you will see that you already have a container with nginx. are you making a proxy behind the proxy?

**Comment by stonezdj** [comment]
If you want to access Harbor through 80/443 port, you can configure it in the harbor.yaml like that, no extra proxy required.
```
# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 80

# https related config
https:
  # https port for harbor, default is 443
  port: 443
```
