### ISSUE TITLE
harbor 使用 S3，默认就使用了path-style，无法使用virtual-hosted–style

### ISSUE THREAD

**Issue by bxd602** [goharbor/harbor#21270]
harbor 使用 S3，默认就使用了path-style，无法使用virtual-hosted–style

我通过代理请求发现 请求s3的 aws-sdk-go 还是很旧的 1.15.11版本
```
[02/Dec/2024:18:55:23 +0800] "PUT /{bucket}/docker/registry/v2/repositories/aigc/rembg/_uploads/ef0d14b7-9227-4bf5-861e-f28c9b639dfd/startedat HTTP/1.1" 403 1374 "-" "aws-sdk-go/1.15.11 (go1.23.2; linux; amd64)" "127.0.0.1" "xx.xx.com" "keep-alive" "-" "-" "-" "gzip" "-" "-"
```

我是用的是 2.12.0的harbor，s3的配置如下
```
storage_service:
  s3:
    accesskey:  123123123123
    secretkey: 123123123123123
    region: ap-guangzhou
    regionendpoint: https://cos.ap-guangzhou.myqcloud.com
    forcepathstyle: false
    # accelerate: false
    bucket: 1231231231
    # encrypt: true
    # secure: true
    # skipverify: true
    # v4auth: false
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 1000
    multipartcopythresholdsize: 5368709120
    rootdirectory: /
    loglevel: debug
```

这个该如何升级呢？需要重编源码吗
