### ISSUE TITLE
Create a configuration item max_job_duration_hours for job service 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#21280]
There are two environment variable need to configured in the jobservice config.yml and env file to configure the longest time a task can be scheduled.

https://github.com/goharbor/harbor/wiki/Harbor-FAQs#job-service

MAX_JOB_DURATION_SECONDS 
and 
```
reaper:
  max_update_hours: 168
```

Need to consolidate these two option into one option in the harbor.yml under jobservice section.

**Comment by Vivekgaddigi** [comment]
hey @stonezdj can i work on this?

**Comment by stonezdj** [comment]
Thanks @Vivekgaddigi  
you could create a PR to update the harbor.yml.tmpl 

```
jobservice:
  # Maximum number of job workers in job service
  max_job_workers: 10
  # Maximum number of task duration in job service, default 24 hours
  max_job_duration_hours: 24
```

Then render it into the common/config/jobservice/env and common/config/jobservice/config.yml
