### ISSUE TITLE
Error 401 while pulling/pushing images

### ISSUE THREAD

**Issue by maurochss** [goharbor/harbor#21288]
Hi all,

I'm facing an error on harbor Version v2.11.1-6b7ecba1

My setup:

I have an HTTPs NGINX at DMZ that forwards the traffic to a **non** https harbor running on my internal network on port 82.

![image](https://github.com/user-attachments/assets/b836a495-1b14-4cf4-844d-7a812ac004f7)

I'm struggling to identify the possible issue, assistance on this would be very nice.

PS: I can access the web interface without any issues.

--
Regards,
Mauro Chan Son Suleimane

**Comment by Vad1mo** [comment]
Very difficult to tell, but I guess its you LB, make sure you configure it similar to the recommendations for running harbor on nginx ingress.

```yaml
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/proxy-buffering: "off"
                  nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
```
