### ISSUE TITLE
Harbor is not fetching the latest digest of particular tag when using harbor proxy with kyverno for image verification.

### ISSUE THREAD

**Issue by Thrinadh-Kumpatla** [goharbor/harbor#21451]
How can we help you?

Hi, 
We have a workflow where we are using harbor proxy proxied with dockerhub. harbor mutating webhook rewrite the image tag in such a way it pulls from harbor instead of docker.
we do image signing via github actions workflow using cosign. 
We run kyverno clusterPolicy in order to verify if image has signature or not. 

Let's say I have a particular tag with 4 different digests with latest digest in docker and their associated signatures. When harbor and kyverno is present, kyverno is always pulling the old digest instead of new digest even with pullPolicy set to Always and that's not the case when I removed harbor and instead fetch the image directly from dockerhub. Did anyone faced this issue?

Attached kyverno policy for reference

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-keyless-thrinadh
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-image-keyless-thrinadh
      match:
        any:
        - resources:
            kinds:
              - Pod
              - Deployment
      verifyImages:
      - imageReferences:
        - "hub.company.com/dockerhub-proxy/thrinadh8898/sigstore-keyless-max-testing*"  
        mutateDigest: true 
        required: true
        useCache: false
        verifyDigest: true 
        attestors:
        - entries:
          - keyless:
              subjectRegExp: https://github\.com/.+
              issuerRegExp: https://token\.actions\.githubusercontent.+
              rekor:
                url: https://rekor.sigstore.dev
```

When I set 
```
  mutateDigest: false 
  required: true
  useCache: false
  verifyDigest: false 
```

It's pulling the latest which is fine, But what I noticed is that kyverno is allowing the same tag with a digest without signature which shouldn't happen.
