### ISSUE TITLE
Cannot Use Minio S3 Buckets

### ISSUE THREAD

**Issue by chrysillis** [goharbor/harbor#21618]
I have MinIO bucket setup. I've confirmed I can connect to and upload data to this bucket from other apps. However, Harbor will not connect. It keeps giving this error:

`time="2025-02-11T00:57:12.727243101Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

I have checked many times and confirmed all of the configs are correct as far as MinIO's side is concerned.

```
storage_service:
 s3:
   accesskey: <my-access-key>
   secretkey: <my-secret-key>
   region: us-east-1
   regionendpoiont: https://minio.local
   forcepathstyle: true
   bucket: harbor
   v4auth: true
```
