### ISSUE TITLE
Failed on load rest config

### ISSUE THREAD

**Issue by JanBenisek** [goharbor/harbor#21738]
How can we help you?

### Error message
The service `harbor-jobservice` does not start, error:
```
[ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:Get "http://harbor-core:80/api/v2.0/internalconfig": dial tcp: lookup harbor-core on 192.168.178.1:53: no such host, url:http://harbor-core:80/api/v2.0/internalconfig
panic: failed to load configuration, error: failed to load rest config

goroutine 1 [running]:
main.main()
	/harbor/src/jobservice/main.go:46 +0x3ae
```

### The relevant part of `values.yaml`:
```yaml
externalURL: "https://harbor.${DOMAIN_NAME}"
    harborAdminPassword: admin 
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: "secret"
        secret:
          secretName: "letsencrypt-wildcard-cert-FOOBAR.com-production"
      ingress:
        hosts:
          core: harbor.${DOMAIN_NAME}
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: "100000m"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "300"
```

### Context
- ✅ The application works and I can access it.
- I somehow suspect that the `http://harbor-core` should be on my domain. I tried to change it but without luck.
- `k get svc` shows all of them running
- ingress exists 

### Environment
- I am deploying `harbor` on k8s (1.30.1, Talos OS 1.8.3)
- I am using Metallb as a loadbalancer on my bare metal cluster.
- helm chart 1.16.2.
