### ISSUE TITLE
Can't do a docker cli login for an OIDC user

### ISSUE THREAD

**Issue by stevenwhayes** [goharbor/harbor#21758]
I can't get docker cli login to work with Harbor except with robot accounts.  My main user setup is OIDC to Dex using Github Oauth as a backend to Dex.  I've reviewed the issues and and the only relevant one I've seen is to make sure you are using the username as it appears in Harbor, not as it does in the identity provider (https://github.com/goharbor/harbor/issues/18772).  I'm doing that.  I've tried many combinations of OIDC scope, Username Claim, automatic onboarding and nothing makes a difference.  I can log into the webUI fine but the docker CLI login doesn't work and errors on "failed to verify id token signature".  Here is a full log example:

```
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/server/middleware/log/log.go:31]: attach request id 1ca08966-f1f0-4a9b-9542-fa53aaa13a3e to the logger for the request GET /v2/
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:55]: In artifact info middleware, url: /v2/
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="1ca08966-f1f0-4a9b-9542-fa53aaa13a3e"]: an unauthorized security context generated for request GET /v2/
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/lib/http/error.go:62]: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/server/middleware/log/log.go:31]: attach request id 24dec6a0-6817-4d55-94cc-beb19ed6a98f to the logger for the request GET /service/token
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:55]: In artifact info middleware, url: /service/token?account=Steve_Hayes&client_id=docker&offline_token=true&service=harbor-registry
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/pkg/oidc/secret.go:87]: Verifying the secret for user: Steve_Hayes
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/pkg/config/manager.go:142]: failed to get key oidc_groups_claim, error: the configure value is not set, maybe default value not defined before get
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/pkg/config/manager.go:142]: failed to get key oidc_groups_claim, error: the configure value is not set, maybe default value not defined before get
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/pkg/oidc/helper.go:201]: Raw ID token for verification: <redacted>
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/pkg/config/manager.go:142]: failed to get key oidc_groups_claim, error: the configure value is not set, maybe default value not defined before get
harbor-core  | 2025-03-20T00:47:20Z [ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="24dec6a0-6817-4d55-94cc-beb19ed6a98f"]: failed to verify secret, username: Steve_Hayes, error: failed to verify the secret: failed to verify signature: failed to verify id token signature
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/core/auth/authenticator.go:145]: Current AUTH_MODE is oidc_auth
harbor-core  | 2025-03-20T00:47:20Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="<redacted>" requestID="24dec6a0-6817-4d55-94cc-beb19ed6a98f" user agent="docker/27.2.1 go/go1.22.7 git-commit/8b539b8 kernel/5.15.167.4-microsoft-standard-WSL2 os/linux arch/amd64 UpstreamClient(Docker-Client/27.2.1 \(linux\))"]: failed to authenticate user:Steve_Hayes, error:not supported
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="24dec6a0-6817-4d55-94cc-beb19ed6a98f"]: an unauthorized security context generated for request GET /service/token
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/core/service/token/token.go:37]: URL for token request: /service/token?account=Steve_Hayes&client_id=docker&offline_token=true&service=harbor-registry
harbor-core  | 2025-03-20T00:47:20Z [DEBUG] [/core/service/token/creator.go:201]: scopes: []
```

versions:
Harbor 2.12.2
Dex 2.40.0

Dex config:

```
issuer: https://<redacted>:8443/dex
storage:
  type: memory
web:
  https: 0.0.0.0:8443
  tlsCert: /certs/fullchain.pem
  tlsKey: /certs/privkey.pem
oauth2:
  skipApprovalScreen: true
staticClients:
- id: harbor
  redirectURIs:
  - https://<redacted>/c/oidc/callback
  name: Harbor
  secret: <redacted>
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: <redacted>
    clientSecret: <redacted>
    redirectURI: https://<redacted>:8443/dex/callback
    orgs:
    - name: <redacted>  # optional: restrict to a specific GitHub organization
    preferredEmailDomain: <redacted>
    useLoginAsID: true
```

Attaching screenshot from my OIDC setup.  

![Image](https://github.com/user-attachments/assets/25e9996e-4537-456c-bab9-56233a726c5d)

It is a very straightforward setup.  The strangest thing is I believe this did work at one time, and has stopped, despite me not changing versions or configurations of anything, because I had an entry in my docker config.json for it.  I really need this to work as managing robot accounts for all the users greatly reduces the appeal of using Harbor.  Appreciate any help.  Feel like I'm missing something simple.
