### ISSUE TITLE
docker-proxy which harbor's nginx is registered gets zombified after pulling large amount of images at once

### ISSUE THREAD

**Issue by KellyPerro** [goharbor/harbor#21753]
Hi.

Just as the title says, I am trying to download large amount of images to my systems (32 clusters).
The image is about 3GB and 32 clusters are downloading them simultaneously.
For some reason, when I try to download all at once, the docker-proxy which harbor's nginx has registered its ports gets killed and zombify.
I'm talking about the one that gets registered when running "docker-compose up".
Now, when I try with small amount, say batches of 5 clusters, I see way less times of zombification, but still the docker-proxy is getting killed.
I'm struggling to find the culprit behind this for more than a month. Any ideas?

FYI, I'm using harbor 2.7.0 with docker version 20.10.13

Thanks.

**Comment by Vad1mo** [comment]
I don't remember the settings for 2.7 anymore.

Here is how we recommend configuring the nginx ingress. 
Make sure that your Nginx proxy has a similar setting. disable caching, buffering etc...


```yaml
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/proxy-buffering: "off"
                  nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
```

On a side note: if 32 clusters are pulling the same image at the same time, the image will be pulled upstream 32x times too. (if the image is not already in the cache)
