### ISSUE TITLE
Proxy project with quay.io does not work in kubernetes

### ISSUE THREAD

**Issue by sias32** [goharbor/harbor#21795]
**Expected behavior and actual behavior:**
The cluster receives images without problems

**Steps to reproduce the problem:**
1. Create an endpoint in the harbor with options:
- name: redhat
- provider: quay
- address: http://quay.io
- tls: true

2. Create a private proxy project with the name: redhat

3. Create a robot account with the name: `agent$k8s-cluster` and give it full rights

4. Create a deployment with an image and a secret from the harbor
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: harbor.com/redhat/soketi/soketi:1.6-16-distroless
        imagePullPolicy: Always
      imagePullSecrets:
      - name: harbor.com
```

4. run the app and get an error
```bash
k describe pods/soketi-59d686f86d-wdpxh 
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  16m                 default-scheduler  Successfully assigned app-test/soketi-59d686f86d-wdpxh to cluster-node-64wc5
  Warning  Failed     16m (x2 over 16m)   kubelet            Error: ErrImagePull
  Warning  Failed     16m (x2 over 16m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    16m (x2 over 16m)   kubelet            Back-off pulling image "harbor.com/redhat/soketi/soketi:1.6-16-distroless"
  Warning  Failed     16m (x2 over 16m)   kubelet            Error: ImagePullBackOff
  Normal   Pulling    16m (x3 over 16m)   kubelet            Pulling image "harbor.com/redhat/soketi/network-watcher:6.3"
  Warning  Failed     16m (x3 over 16m)   kubelet            Failed to pull image "harbor.com/redhat/soketi/network-watcher:6.3": failed to pull and unpack image "harbor.com/redhat/soketi/network-watcher:6.3": failed to resolve reference "harbor.com/redhat/soketi/network-watcher:6.3": unexpected status from HEAD request to https://harbor.com/v2/redhat/soketi/network-watcher/manifests/6.3: 401 Unauthorized
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [v2.11.0 or v2.12.2]
- harbor chart: [1.15.0 or 1.16.2]
- cluster version: [1.29.4]

**Additional context:**

- **Harbor config files:**
```yaml
logLevel: info
externalURL: https://harbor.com
existingSecretAdminPassword: harbor-secrets
imagePullPolicy: Always

expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-ingress
  ingress:
    hosts:
      core: harbor.com
    className: "nginx"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    labels: {}

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    trivy:
      storageClass: basic
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: false
    type: s3
    s3:
      region: ru-1
      regionendpoint: https://bucket.com
      forcepathstyle: true
      accelerate: false
      bucket: harbor_registry
      encrypt: true
      existingSecret: harbor-secrets
      secure: true
      v4auth: true
      chunksize: "5242880"
      multipartcopychunksize: "33554432"
      multipartcopymaxconcurrency: "100"
      multipartcopythresholdsize: "33554432"
      rootdirectory: /
      usedualstack: false
      loglevel: debug

internalTLS:
  enabled: true
  strong_ssl_ciphers: true
  certSource: "auto"

ipFamily:
  ipv6:
    enabled: false
  ipv4:
    enabled: true

updateStrategy:
  type: RollingUpdate

metrics:
  enabled: false

trace:
  enabled: false

cache:
  enabled: true
  expireHours: 24

portal:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

core:
  replicas: 1
  resources: {}
  quotaUpdateProvider: db
  gdpr:
    deleteUser: true
    auditLogsCompliant: false

jobservice:
  replicas: 1
  maxJobWorkers: 10
  jobLoggers:
  - database
  loggerSweeperDuration: 14
  resources: {}
  existingSecret: harbor-secrets
  notification:
    webhook_job_max_retry: 3
    webhook_job_http_client_timeout: 3
  reaper:
    max_update_hours: 12
    max_dangling_hours: 24

registry:
  replicas: 1
  registry:
    resources: {}
  controller:
    resources: {}
  credentials:
    username: registry_user
    existingSecret: harbor-secrets
  upload_purging:
    enabled: true
    age: 168h
    interval: 24h
    dryrun: false

trivy:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  securityCheck: "vuln,config,secret"
  timeout: 5m0s
  tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "statefulset"
    effect: "NoExecute"

database:
  type: external
  external:
    host: "postgres"
    port: 6100
    username: "harbor"
    coreDatabase: "harbordb"
    existingSecret: "harbor-secrets"
    sslmode: "disable"
  maxIdleConns: 100
  maxOpenConns: 900

redis:
  type: external
  external:
    existingSecret: harbor-secrets
    username: harbor
    addr: 10.133.200.4:30000,10.137.200.4:30000,10.139.200.4:30000
    sentinelMasterSet: harbor
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    trivyAdapterIndex: "5"
    harborDatabaseIndex: "6"
    cacheLayerDatabaseIndex: "7"
```

- **Log files:** none
