### ISSUE TITLE
Endpoint with auth registry get unhealthy without any reason after 5-24h

### ISSUE THREAD

**Issue by Syntax3rror404** [goharbor/harbor#21985]
**Expected behavior and actual behavior:**
After adding a registry for replication to another registry via endpoint url, registry gets unhealthy over time like every 5 hours. This issue is reproducible and only affects registries with auth. 

**Steps to reproduce the problem:**
- Install harbor
- Create remote registry like a acr for mirroring or use a docker.io account for image pulling
- Registry gets healthy
- Wait 24h
- Registry gets unhealthy 
- Fix it by entering the same creds again
- Registry gets healthy again
- Wait 24h
- Registry gets unhealthy 
- .........

**Versions:**

- harbor version: 2.12.2
- kubernetes version: 1.23.3

**Additional context:**

- **Harbor config files:**  helm values.yaml
```yaml
---
{{- if .Values.spec.harbor.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: {{ .Values.spec.argocdNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: harbor
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: harbor
    path: '.'
    repoURL: {{ .Values.spec.bitnami.repoURL }}
    targetRevision: {{ .Values.spec.harbor.targetRevision }}
    helm:
      values: |
        adminPassword: "{{ .Values.spec.harbor.initpw }}"
        global:
          storageClass: "{{ .Values.spec.harbor.storageClass }}"
        externalURL: "https://{{ .Values.spec.harbor.host }}"
        exposureType: ingress
        expose:
          tls:
            certSource: none
        proxy:
          httpProxy: {{ .Values.spec.proxy.proxy }}
          httpsProxy: {{ .Values.spec.proxy.proxy }}
          noProxy: {{ .Values.spec.proxy.noproxy }}
        logLevel: debug
        service:
          type: ClusterIP
        ipFamily:
          ipv6:
            enabled: false
          ipv4:
            enabled: true
        redis:
          master:
             resourcesPreset: "small"
        ingress:
          core:
            ingressClassName: cilium
            hostname: "{{ .Values.spec.harbor.host }}"
            tls: false
            pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
              ingress.cilium.io/loadbalancer-mode: shared
              ingress.cilium.io/websocket: enabled
            extraTls:
              - hosts:
                  - "{{ .Values.spec.harbor.host }}"
        notary:
          enabled: false
        persistence:
          enabled: true
          resourcePolicy: ''
          persistentVolumeClaim:
            registry:
              size: 64Gi
            trivy:
              size: 5Gi
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
```
- **Log files:** You can get them by package the `/var/log/harbor/` .
