### ISSUE TITLE
Harbor Registry fails with Huawei OBS due to unsupported PATCH method

### ISSUE THREAD

**Issue by erlkoenig91** [goharbor/harbor#22126]
Hi Harbor Team, 

**Describe the bug**
When using Harbor (v2.13.1) with Huawei OBS as the backend for registry storage (storage_provider_name: s3), image uploads fail with a 405 Method Not Allowed error. The issue arises during the blob upload phase, where the registry performs an HTTP PATCH request to stream upload chunks to the S3 backend.

Huawei OBS, while claiming S3 compatibility, does not support the HTTP PATCH method, which leads to the following error returned by the registry:

```
s3aws: MethodNotAllowed: The specified method is not allowed against this resource.
status code: 405
```

**Expected behavior**
Image uploads should complete successfully using Huawei OBS, assuming all required S3 features are supported. If PATCH is a hard requirement, the documentation should clearly state that compatibility is limited to S3 providers that support HTTP PATCH.

Steps to reproduce the issue:
	1.	Set up Harbor 2.13.1 with Huawei OBS as storage backend.
	2.	Use the following harbor.yml configuration (excerpt):

```
              storage_service:
                storage_provider_name: s3
                s3:
                  region: reg1
                  bucket: k8s01-harbor
                  accesskey: ...
                  secretkey: ...
                  regionendpoint: https://<bucket>.obs.<region>.myhuaweicloud.com
                  v4auth: true
                  forcepathstyle: false
                  chunksize: 5242880
                  rootdirectory: ""
```
	3.	Push any container image using Docker or Podman.
	4.	Observe Harbor logs or registry container output.
**Log output (relevant excerpt):**

error resolving upload: s3aws: MethodNotAllowed: The specified method is not allowed against this resource.
status code: 405

Environment details:
	•	Harbor version: v2.13.1
	•	Docker registry: distribution v2 backend
	•	Storage: Huawei OBS (S3-compatible)
	•	Client: Docker 28.1.1
	•	System: Linux, Kernel 6.8

**Additional context:**
This issue may affect other non-AWS S3 backends as well, particularly those that lack support for HTTP PATCH. There is currently no documented way to disable PATCH uploads or enforce multipart-only PUT behavior.
