### ISSUE TITLE
does Harbor support webhooks that when docker images were updated ?

### ISSUE THREAD

**Issue by hongtao12310** [goharbor/harbor#2448]
I am developing a K8S deployment tool to deploy the project to K8S cluster.

my code is on the gitlab. and gitlab support webhook when there is coding change so that we can use jenkis to auto build docker images based the code and then push the images to Harbor.

but at that point K8S doesn't know the image changes when Jenkis push it to Harbor . so i am wondering if the Harbor can support webhooks so that I can register an API or something other to pull the docker image and deploy the image to K8S when there is an image change on Harbor .

**Comment by reasonerjt** [comment]
No it currently doesn't you can try to leverage "notification" of the docker registry within Harbor.

For details see: https://docs.docker.com/registry/notifications/

**Comment by hongtao12310** [comment]
Thanks reasonerjt !

since Harbor is based on docker registry. I assumed "notifications" section was supported in harbor.cfg ?

**Comment by reasonerjt** [comment]
No, you can't set it in harbor.cfg, you need to update the config.yml of registry.

**Comment by hongtao12310** [comment]
ok. do you mean we should update the common/templates/registry/config.yml to enable docker registry notifications ?

**Comment by swathichittajallu** [comment]
@clouderati Hi, I have tried and it worked by updating the config.yml in Harbor

**Comment by shinebayar-g** [comment]
@swathichittajallu Hi, can you share your method?
Currently in `common/templates/registry/config.yml` file there is 
```YAML
notifications:
  endpoints:
  - name: harbor
    disabled: false
    url: $ui_url/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s
```
How do you add more urls? I mean my CI/CD endpoint to this config?

**Comment by swathichittajallu** [comment]
@shinebayar-g endpoints takes an array of elements. You can give your endpoint the same way as how harbor endpoint is given. 
notifications:
  endpoints:
  - name: harbor
    disabled: false
    url: $ui_url/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s
  - name: Your endpoint-name
    disabled: false
    url: your custom url
    timeout: 3000ms
    threshold: 5
    backoff: 1s

**Comment by swathichittajallu** [comment]
endpoints takes an array of elements. You can give your endpoint the same way as how harbor endpoint is given.

```
notifications:
    endpoints:
    - name: harbor
      disabled: false
      url: $ui_url/service/notifications
      timeout: 3000ms
      threshold: 5
      backoff: 1s
    - name: Your endpoint-name
      disabled: false
      url: your custom url
      timeout: 3000ms
      threshold: 5
      backoff: 1s

```
