### ISSUE TITLE
Harbor应该增加一个mirror registry的配置选项用作镜像

### ISSUE THREAD

**Issue by xingx-xx** [goharbor/harbor#2734]
在使用私有registry的过程中，有很多场景需要在内网做一个Hub的缓存，以便快速拉取官方镜像，提高开发和部署效率。
Harbor(1.1.2)可以通过配置registry的config.yml支持mirror，但是这就意味着client不能push到私有仓库，鱼和熊掌不可兼得。
建议Harbor默认增加一个配置选项，供用户配置额外启动一个registry作为mirror，这个功能很容易实现，比如说在docker-compose中增加以下内容：
```
  mirror:
    image: vmware/registry:2.6.1-photon
    container_name: mirror
    restart: always
    volumes:
      - /data/mirror:/storage:z
      - ./common/config/mirror/:/etc/registry/:z
    networks:
      - harbor
    ports:
      - 5000:5000
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mirror"
```
并稍加修改prepare脚本，添加一个mirror registry的模板就好
一个可以参考的mirror registry配置如下：
```
version: 0.1
log:
  level: warn
  fields:
    service: mirror
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: true
            age: 168h
            interval: 24h
            dryrun: false
    delete:
        enabled: true
proxy:
    remoteurl: https://registry-1.docker.io
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
```
