### ISSUE TITLE
Helm /v2 redirect issue and 200 OK when pushing image

### ISSUE THREAD

**Issue by triqster** [goharbor/harbor#5324]
Deploying the helm chart results in a redirect issue when pushing an image to repository (/v2/)

Ingress Yaml after deployment:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/rewrite-target: /registryproxy/v2
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /registryproxy/v2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: null
  generation: 1
  labels:
    app: harbor
    chart: harbor-0.2.0
    heritage: Tiller
    release: harbor
  name: harbor-harbor-ingress-registry
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/harbor-harbor-ingress-registry
spec:
  rules:
  - host: harbor.aa.FAKE.com
    http:
      paths:
      - backend:
          serviceName: harbor-harbor-ui
          servicePort: 80
        path: /v2
  tls:
  - hosts:
    - harbor.aa.FAKE.com
    secretName: harbor-harbor-ingress
status:
  loadBalancer: {}
```

The issue seems to be:
```
    ingress.kubernetes.io/rewrite-target: /registryproxy/v2
    nginx.ingress.kubernetes.io/rewrite-target: /registryproxy/v2
```
When pushing to a repository it end up in a redirect loop (docker push output):
```
Get /v2/: stopped after 10 redirects
```
Adding a tailing / to the end of the /v2 path seems to do the trick:
```
   ingress.kubernetes.io/rewrite-target: /registryproxy/v2/
   nginx.ingress.kubernetes.io/rewrite-target: /registryproxy/v2/
```
However this ends up with another issue (status 200 OK) from the registry pod:

After adding a tailing / to the ingress:
```
001242e380a1: Retrying in 1 second 
f395a9a6c3ea: Retrying in 1 second 
bf84f7356ba9: Retrying in 1 second 
ae3b3ab0f967: Layer already exists 
0706f78fa8ac: Layer already exists 
445960985331: Layer already exists 
602c24687a98: Layer already exists 
3358360aedad: Layer already exists 
received unexpected HTTP status: 200 OK
```

kubectl logs -f harbor-harbor-registry-0
```
time="2018-07-17T07:50:34.946179768Z" level=info msg="response completed" go.version=go1.7.3 http.request.host="harbor.aa.FAKE.com:443" http.request.id=be9c033d-9daf-5b6f-b8da-59972fef19fa http.request.method=POST http.request.remoteaddr=<FAKEIP> http.request.uri="/v2/" http.request.useragent="docker/18.05.0-ce go/go1.10.2 git-commit/f150324782 kernel/4.14.54-1-MANJARO os/linux arch/amd64 UpstreamClient(Docker-Client/18.05.0-ce \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.041957ms http.response.status=200 http.response.written=2 instance.id=eb147fdd-e531-470a-8f5c-d0be6692aa1b service=registry version=v2.6.2 
10.233.105.153 - - [17/Jul/2018:07:50:34 +0000] "POST /v2/ HTTP/1.1" 200 2 "" "docker/18.05.0-ce go/go1.10.2 git-commit/f150324782 kernel/4.14.54-1-MANJARO os/linux arch/amd64 UpstreamClient(Docker-Client/18.05.0-ce \\(linux\\))"
```
harbor-adminserver-0 logs:
```
10.233.83.51 - - [17/Jul/2018:08:01:05 +0000] "GET /api/configurations HTTP/1.1" 200 1716
10.233.83.51 - - [17/Jul/2018:08:01:17 +0000] "GET /api/configurations HTTP/1.1" 200 1716
```
harbor-ui logs:
```
2018-07-17T08:12:19Z [DEBUG] [interceptors.go:120]: in url handler, path: /registryproxy/v2/
2018-07-17T08:12:19Z [DEBUG] [security.go:233]: can not get user information from session
2018-07-17T08:12:19Z [DEBUG] [security.go:290]: user information is nil
2018-07-17T08:12:19Z [DEBUG] [security.go:304]: using local database project manager
2018-07-17T08:12:19Z [DEBUG] [security.go:306]: creating local database security context...
```
