### ISSUE TITLE
Harbor core showing session errors

### ISSUE THREAD

**Issue by jchanam** [goharbor/harbor#6532]
**Expected behavior and actual behavior:**
No errors shown on UI and core logs

**Steps to reproduce the problem:**
- Deploy an external postgres db
- Install harbor with the chart

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.7.0-rc2
- harbor chart version: master - https://github.com/goharbor/harbor-helm/commit/32f927fdfac0f563961fce6702aab46649ace637

**Additional context:**
* **Harbor config files:** (helm values)
```
expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.mydomain.com
      notary: harbor-notary.mydomain.com
    annotations:
      kubernetes.io/ingress.class: core
      kubernetes.io/tls-aws-certificate-manager: "true"
  tls:
    enabled: false

externalURL: https://harbor.mydomain.com

persistence:
  enabled: true
  resourcePolicy: ""
  persistentVolumeClaim:
    registry:
      storageClass: "aws-efs"
      accessMode: ReadWriteMany
    chartmuseum:
      storageClass: "aws-efs"
      accessMode: ReadWriteMany
    jobservice:
      storageClass: "aws-efs"
      accessMode: ReadWriteMany
    database:
      storageClass: "aws-efs"
      accessMode: ReadWriteMany

nginx:
  image:
    repository: myregistry.com/harbor/nginx-photon
    tag: v1.7.0-rc2

portal:
  image:
    repository: myregistry.com/harbor/harbor-portal
    tag: v1.7.0-rc2

core:
  image:
    repository: myregistry.com/harbor/harbor-core
    tag: v1.7.0-rc2

adminserver:
  image:
    repository: myregistry.com/harbor/harbor-adminserver
    tag: v1.7.0-rc2

jobservice:
  image:
    repository: myregistry.com/harbor/harbor-jobservice
    tag: v1.7.0-rc2

registry:
  registry:
    image:
      repository: myregistry.com/harbor/registry-photon
      tag: v1.7.0-rc2
  controller:
    image:
      repository: myregistry.com/harbor/harbor-registryctl
      tag: v1.7.0-rc2

chartmuseum:
  image:
    repository: myregistry.com/harbor/chartmuseum-photon
    tag: v1.7.0-rc2

clair:
  image:
    repository: myregistry.com/harbor/clair-photon
    tag: v1.7.0-rc2

notary:
  server:
    image:
      repository: myregistry.com/harbor/notary-server-photon
      tag: v1.7.0-rc2
  signer:
    image:
      repository: myregistry.com/harbor/notary-signer-photon
      tag: v1.7.0-rc2

database:
  type: external
  external:
    host: "pg-harbor"
    username: "harbor"
    password: "password"
    sslmode: "require"
```
* **Log files:** logs from harbor-core pod
```
2018-12-13T16:00:52Z [DEBUG] [security.go:233]: can not get user information from session
2018-12-13T16:00:52Z [DEBUG] [security.go:290]: user information is nil
2018-12-13T16:00:52Z [DEBUG] [security.go:304]: using local database project manager
2018-12-13T16:00:52Z [DEBUG] [security.go:306]: creating local database security context...
2018-12-13T16:01:01Z [DEBUG] [security.go:237]: got user information from session
2018-12-13T16:01:01Z [DEBUG] [security.go:243]: Getting user %+v{1 admin admin@example.com  system admin admin user false  0 true  zgpziteqgpbmnkbam7e9407w55v5oigb 2018-12-13 15:55:36.378492 +0000 UTC 2018-12-13 15:55:51.974262 +0000 UTC []}
2018-12-13T16:01:01Z [DEBUG] [security.go:244]: using local database project manager
2018-12-13T16:01:01Z [DEBUG] [security.go:246]: creating local database security context...
2018-12-13T16:01:02Z [DEBUG] [security.go:233]: can not get user information from session
2018-12-13T16:01:02Z [DEBUG] [security.go:290]: user information is nil
2018-12-13T16:01:02Z [DEBUG] [security.go:304]: using local database project manager
2018-12-13T16:01:02Z [DEBUG] [security.go:306]: creating local database security context...
2018-12-13T16:01:02Z [DEBUG] [security.go:233]: can not get user information from session
2018-12-13T16:01:02Z [DEBUG] [security.go:290]: user information is nil
2018-12-13T16:01:02Z [DEBUG] [security.go:304]: using local database project manager
2018-12-13T16:01:02Z [DEBUG] [security.go:306]: creating local database security context...

```
In the UI I'm getting this error messages when navigating:
```
Unknown errors have occurred. Please try again later.
```
And this when clicking on users:
```
Unexpected token < in JSON at position 0
```

I don't know how to fix this. I'll provide you every log you need.

**Comment by ywk253100** [comment]
Could you open the debug console of your browser and check what happens, is there any API call failed?

**Comment by jchanam** [comment]
On login page:
```
https://harbor.mydomain.com/api/users/current 401
```
```
Failed to load bootstrap options with error:  SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.n.json (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invoke (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvoke (main.3c73c10d2cb36b65f91c.js:1)
    at n.invoke (main.3c73c10d2cb36b65f91c.js:1)
    at e.run (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvokeTask (main.3c73c10d2cb36b65f91c.js:1)
```

Then, I put the correct credentials and click login. Nothing happens. No console logs. I reload and go into the panel.

When navigating and showing the error `Unknown errors have occurred. Please try again later.` there's no errors logged in the console. All 200 OK in network.

When showing the `Unknown errors have occurred. Please try again later.` error, I get this in console:
```
main.3c73c10d2cb36b65f91c.js:1 ERROR SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.n.json (main.3c73c10d2cb36b65f91c.js:1)
    at e.project (main.3c73c10d2cb36b65f91c.js:1)
    at e._next (main.3c73c10d2cb36b65f91c.js:1)
    at e.next (main.3c73c10d2cb36b65f91c.js:1)
    at e._next (main.3c73c10d2cb36b65f91c.js:1)
    at e.next (main.3c73c10d2cb36b65f91c.js:1)
    at XMLHttpRequest.i (main.3c73c10d2cb36b65f91c.js:1)
    at n.invokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvokeTask (main.3c73c10d2cb36b65f91c.js:1)
```

I hope this helps, thanks!

**Comment by jchanam** [comment]
Hi,

I'm still facing this issue in 1.7.0.

For example, when navigating to `https://harbor.mydomain.com/harbor/projects`. I get:
```
main.3c73c10d2cb36b65f91c.js:1 ERROR Error: Uncaught (in promise): SyntaxError: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.n.json (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invoke (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvoke (main.3c73c10d2cb36b65f91c.js:1)
    at n.invoke (main.3c73c10d2cb36b65f91c.js:1)
    at e.run (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at JSON.parse (<anonymous>)
    at e.n.json (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invoke (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvoke (main.3c73c10d2cb36b65f91c.js:1)
    at n.invoke (main.3c73c10d2cb36b65f91c.js:1)
    at e.run (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at D (main.3c73c10d2cb36b65f91c.js:1)
    at main.3c73c10d2cb36b65f91c.js:1
    at n.invokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at Object.onInvokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at n.invokeTask (main.3c73c10d2cb36b65f91c.js:1)
    at e.runTask (main.3c73c10d2cb36b65f91c.js:1)
    at g (main.3c73c10d2cb36b65f91c.js:1)
    at e.invokeTask [as invoke] (main.3c73c10d2cb36b65f91c.js:1)
    at b (main.3c73c10d2cb36b65f91c.js:1)
    at XMLHttpRequest.C (main.3c73c10d2cb36b65f91c.js:1)
```

**Comment by jchanam** [comment]
Also, Projects are not being shown correctly. Sometimes I get that there's no projects, other times just "library".

When creating a new project, I get:
```
<html>
 <head><title>405 Not Allowed</title></head>
 <body bgcolor="white">
 <center><h1>405 Not Allowed</h1></center>
 <hr><center>nginx/1.13.8</center>
 </body>
 </html>
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
```

But when trying to create it again, it says that the project already exists, even though it's never shown in the list.

I hope this helps.

**Comment by zhoumeina** [comment]
@jchanam , so you use the GA version of harbor. Right?

**Comment by jchanam** [comment]
@zhoumeina Yes, I'm using the default values set on the helm chart. I've changed to the tag 1.0.0, which uses harbor 1.7.0.

Still facing this issue.

**Comment by jchanam** [comment]
Hi @ywk253100, @zhoumeina,

I've tried with the recent release of harbor v1.7.1 and the issue is still happening.

I'm using the helm chart tagged with version 1.0.0, and with this values:
```
expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.myurl.com
      notary: harbor-notary.myurl.com
    annotations:
      kubernetes.io/ingress.class: core
      kubernetes.io/tls-aws-certificate-manager: "true"
  tls:
    enabled: false

externalURL: https://harbor.myurl.com
```

I've tried with and without tls, with external and internal database, with and without persistence. In all cases, the failures persist.

Can I provide more information? What could you need to fix this issue? Is there any progress fixing this issue?
