### ISSUE TITLE
Can't log in with default admin credentials after installing newer version

### ISSUE THREAD

**Issue by cwelde** [goharbor/harbor#6879]
Running Harbor v1.5.0 on Ubuntu, decided to take a look at upgrading to v1.7.1. Took down the v1.5.0 instance, downloaded the offline installer for v1.7.1, followed all the instructions and only edited some settings in the harbor.cfg (the hostname, ui url protocol, and the cert/key paths) to be the same as the v1.5.0 settings. I then ran ./install.sh and everything set up correctly, no errors. I go to the web UI and try to login as admin with the password Harbor12345 but it says invalid username or password. Tried changing the admin password and still no luck. also tried configuring LDAP settings but still no luck. 

Docker engine version 18.09

Docker-compose version 1.23.2

edit: To add clarity, I don't care about the data in the v1.5.0 instance because we're going to rebuild/push our images to the v1.7.1 instance. I figured this was the appropriate way of doing that: Taking down the v1.5.0 instance, downloading the v1.7.1 installer, configuring the harbor.cfg for 1.7.1 to use the hostname and certs that the v1.5.0 did. It deploys correctly with no errors. However, I cannot log into the 1.7.1 Instance at all via the web UI.

**Comment by sn0wcat** [comment]
I did a clean install of online installer with v1.7.1  (running on ssh) and i have exactly the same thing.

**Comment by sn0wcat** [comment]
@cwelde 

There seems to be a bug in how harbor handles the /data/secretkey location

You can replace all occurences of **/data/secretkey** with **/data/secretkey/secretkey** in the docker-compose.yml (there are 2 places to patch)

in core:

`yml
/data/secretkey/secretkey:/etc/core/key:z
`

in admin server:

`yml
 /data/secretkey/secretkey:/etc/adminserver/key:z
`

after that it should start



``

**Comment by cwelde** [comment]
> @cwelde
> 
> There seems to be a bug in how harbor handles the /data/secretkey location
> 
> You can replace all occurences of **/data/secretkey** with **/data/secretkey/secretkey** in the docker-compose.yml (there are 2 places to patch)
> 
> in core:
> 
> `/data/secretkey/secretkey:/etc/core/key:z`
> 
> in admin server:
> 
> `/data/secretkey/secretkey:/etc/adminserver/key:z`
> 
> after that docker-compose up -d should work

Hi sn0w, I changed the two lines in the docker-compose.yml to the above, after running docker-compose up -d, I got the following error:

![aa](https://user-images.githubusercontent.com/28943926/52141190-c305a900-2609-11e9-845c-22d76390a24a.PNG)

**Comment by jacky1104** [comment]
The same issue to me too.

**Comment by cwelde** [comment]
> The same issue to me too.

Never figured it out. Decided to just deploy a fresh 1.7 instance on a new machine.  It was too much of a headache to figure things out.

**Comment by jacky1104** [comment]
@cwelde yes, reinstall, everything works.

**Comment by byliuyang** [comment]
In case you are not able to login into harbor when exposing the service through ClusterIP, please make sure you are exposing both the portal & the api correctly:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`harbor.example.com`)
      services:
        - kind: Service
          name: harbor-harbor-portal
          namespace: harbor
          port: 80
          scheme: http
    - kind: Rule
      match: Host(`harbor.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/service`) || PathPrefix(`/v2`) || PathPrefix(`/chartrepo`) || PathPrefix(`/c`))
      services:
        - kind: Service
          name: harbor-harbor-core
          namespace: harbor
          port: 80
          scheme: http
  tls:
    secretName: example-cert
```

This should solve all your problems!
