### ISSUE TITLE
Enable harbor registry storage provider disable redirect = true

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#7595]
https://github.com/vmware/harbor-boshrelease/issues/15

harbor.yaml should add an option registry_storage_provider.disable.redirect
default value is true
common/templates/registry/config.yml file as shown below and restarting the harbor job allows pushing images to the registry.
if registry_storage_provider.redirect.disable = true
```
storage:
  cache:
    layerinfo: inmemory
  s3:
    region:  *****
    bucket: **********
    encrypt: true
    secure: true
    chunksize: 5242880
    rootdirectory: /harbor-container-registry
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disable: true
```
if false
Remove the option
```
   redirect:
      disable: true
```
