### ISSUE TITLE
add replication target /api/registries 400 bad request

### ISSUE THREAD

**Issue by Ethan-2017** [goharbor/harbor#7784]
registry http://172.168.188.113 is unhealthy: unhealthy

Request URL: http://172.168.188.13/api/registries
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 172.168.188.13:80
Referrer Policy: no-referrer-when-downgrade

**Comment by Ethan-2017** [comment]
![aa47be52b4d3a4e6705426514e82e0a](https://user-images.githubusercontent.com/31506919/57616942-15177c80-75b2-11e9-9ed2-77e891c77240.png)

**Comment by Ethan-2017** [comment]
![bdd4d5f9815b0b35316807ab17d9e80](https://user-images.githubusercontent.com/31506919/57617043-5c9e0880-75b2-11e9-88cb-72c30128b53e.png)

**Comment by Ethan-2017** [comment]
{
  "status": "healthy",
  "components": [
    {
      "name": "registryctl",
      "status": "healthy"
    },
    {
      "name": "portal",
      "status": "healthy"
    },
    {
      "name": "jobservice",
      "status": "healthy"
    },
    {
      "name": "registry",
      "status": "healthy"
    },
    {
      "name": "database",
      "status": "healthy"
    },
    {
      "name": "core",
      "status": "healthy"
    },
    {
      "name": "redis",
      "status": "healthy"
    },
    {
      "name": "chartmuseum",
      "status": "healthy"
    },
    {
      "name": "clair",
      "status": "healthy"
    }
  ]
}

**Comment by Ethan-2017** [comment]
@ywk253100 
No documentation to instructe to how to add a registry ?what is access id and access secret ?it's  the harbor username and password?

**Comment by ywk253100** [comment]
Did you get any error when you clicking the `测试连接`? You should make sure the target registry can be ping with the credential provided when you adding it.

**Comment by Ethan-2017** [comment]
![cf5409edc380cfed56360074fcbcf65](https://user-images.githubusercontent.com/31506919/57693030-d0a3e380-767a-11e9-8d7b-2621a4de69e2.png)

**Comment by Ethan-2017** [comment]
@ywk253100  core.log
 May 14 19:16:22 172.18.0.1 core[1086]: 2019-05-14T11:16:22Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry http://172.168.188.113: Head http://172.168.188.113/v2/: Get http://replication.huihuigo.com/service/token?service=harbor-registry: dial tcp: lookup replication.huihuigo.com on 127.0.0.11:53: no such host

**Comment by Ethan-2017** [comment]
May 14 19:16:22 172.18.0.1 core[1086]: 2019-05-14T11:16:22Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry http://172.168.188.113: Head http://172.168.188.113/v2/: Get http://replication.huihuigo.com/service/token?service=harbor-registry: dial tcp: lookup replication.huihuigo.com on 127.0.0.11:53: no such host
May 14 19:16:22 172.18.0.1 core[1086]: 2019-05-14T11:16:22Z [ERROR] [/common/api/base.go:69]: POST /api/registries failed with error: {"code":400,"message":"registry http://172.168.188.113 is unhealthy: unhealthy"}

**Comment by Ethan-2017** [comment]
@ywk253100 when I add the host to the container  goharbor/harbor-core  AND  harbor-jobservice, I solve the error

**Comment by jahentao** [comment]
@Ethan-2017  I have the same error, I don't think add the IP host to container is a good solution, because my hostname is a domain. Is there other solution, or is it a bug? @ywk253100

**Comment by DesistDaydream** [comment]
I have the same error。Is there a better solution, such as modifying harbor.yml or something else?

**Comment by YakirShriker** [comment]
@Ethan-2017 can you please explain your solution?

**Comment by Docteur-RS** [comment]
I had the same error...  
I followed @Ethan-2017 fix to update the `/etc/hosts` of the pods *harbor-core* and *job-service* with the hostname of the artifactory and **it worked**...  

As the two pods don't allow updating the `/etc/hosts` directly I used the kubernetes way to update the hosts with the following:  

```
hostAliases:
- ip: "ip_of_machine_where_artifactory_is_exposed"
  hostnames:
  - "docker-local.artifactory"
```
Then, in the UI you can use the url `http://docker-local.artifactory`.

**Comment by sober-wang** [comment]
> 
> 
> @ywk253100 core.log
> May 14 19:16:22 172.18.0.1 core[1086]: 2019-05-14T11:16:22Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry http://172.168.188.113: Head http://172.168.188.113/v2/: Get http://replication.huihuigo.com/service/token?service=harbor-registry: dial tcp: lookup replication.huihuigo.com on 127.0.0.11:53: no such host

How to fix the problem. I met it  and feel headache

**Comment by sober-wang** [comment]
this issue have a solution. we should configuration the docker-compose.yml file.
```yaml
  core:
    image: goharbor/harbor-core:v1.8.3
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /data/harbor-1.8.3-data/ca_download/:/etc/core/ca/:z
      - /data/harbor-1.8.3-data/psc/:/etc/core/token/:z
      - /data/harbor-1.8.3-data/:/data/:z
      - ./common/config/core/certificates/:/etc/core/certificates/:z
      # mount the hosts file into your harbor-core container 
      - /etc/hosts:/etc/hosts
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /data/harbor-1.8.3-data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /data/harbor-1.8.3-data/secret/keys/secretkey
        target: /etc/core/key
    networks:
      harbor:
    dns_search: .
    depends_on:
      - log
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "core"
  jobservice:
    image: goharbor/harbor-jobservice:v1.8.3
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/harbor-1.8.3-data/job_logs:/var/log/jobs:z
      # mount the hosts file into your harbor-core container
      - /etc/hosts:/etc/hosts
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
    networks:
      - harbor
    dns_search: .
    depends_on:
      - redis
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"

```
