### ISSUE TITLE
docker login error

### ISSUE THREAD

**Issue by sage-z** [goharbor/harbor#7837]
我遇到的问题和他差不多，但是又有点区别，最后的结果对我没效 https://github.com/goharbor/harbor/issues/5292#issue-340282358

问题：可以访问UI界面，但是docker login 登录不上
错误信息： Error response from daemon: Get https://harbor.xxx.com/v2/: Get http://harbor.xxx.com:4000/service/token?account=sage&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/12904995/58006726-501e3080-7b1b-11e9-810c-aa6dfa803649.png">

我也有个上层Nginx做端口代理，但是由于docker客户端对HTTPS传输的限制，外界对于上层Nginx之间的传输是HTTPS，上层Nginx 跟 harbor 之间走的是http，上层Nginx做443端口到内网端口4000的转发，并且我不想4000端口暴露给外部链接

上层Nginx配置
```nginx
server {
        listen 443 ssl;
        server_name harbor.xxx.com;
        ssl on;

        ssl_certificate /etc/nginx/harbor/harbor.xxx.com.pem;
        ssl_certificate_key /etc/nginx/harbor/harbor.xxx.com.key;

        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA156:HIGH:!aNULL:!MD5:!RC4:!DHE;

        ssl_prefer_server_ciphers on;

        location / {
		proxy_pass http://127.0.0.1:4000;
		proxy_redirect off;
      		proxy_set_header Host $host;
      		proxy_set_header X-Forwarded-For $remote_addr;
        }
}
```

harbor.cfg 部分配置
```cfg
_version = 1.5.0
hostname = harbor.xxx.com
ui_url_protocol = http
max_job_workers = 50
customize_crt = on
ssl_cert = /data/cert/server.crt
ssl_cert_key = /data/cert/server.key
secretkey_path = /data
admiral_url = NA
http_proxy =
https_proxy =
no_proxy = 127.0.0.1,localhost,ui
```

docker-compose.yml 部分配置
```yml
  proxy:
    image: vmware/nginx-photon:v1.5.0
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 4000:80
      - 4001:443
      - 4443:4443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false

```
我该怎么办？ @ywk253100
