### ISSUE TITLE
cant add registry endpoint v1.8.0

### ISSUE THREAD

**Issue by torubylist** [goharbor/harbor#7909]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
can not  add registry enpoint. can work in 1.8.0-rc.1. but not v1.8.0

**Steps to reproduce the problem:**
update harbor.yml, mainly in harbor address and pg and redis configuration
install v1.8.0,two harbor, share outer pg and redis through haproxy
then add registry endpoint
in harbor1, add harbor2(ip) as the registry enpoint. 
but it return failed to ping endpoint.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.8.0]
- docker engine version: [18.09]
- docker-compose version: [1.18.0]

**Additional context:**
* **Harbor config files:** 
```
hostname: 0.0.0.0

http:
  port: 8800

harbor_admin_password: Harbor12345

database:
  password: Changeme_123

data_volume: /data


external_databases:
  harbor:
    host: 10.255.169.198
    port: 5432
    db_name: harbor
    username: postgres
    password: Changeme_123
    ssl_mode: disable
  clair:
    host: 10.255.169.198
    port: 5432
    db_name: clair
    username: postgres
    password: Changeme_123
    ssl_mode: disable
  notary_signer:
    host: 10.255.169.198
    port: 5432
    db_name: notary_signer
    username: postgres
    password: Changeme_123
    ssl_mode: disable
  notary_server:
    host: 10.255.169.198
    port: 5432
    db_name: notary
    username: postgres
    password: Changeme_123
    ssl_mode: disable

# Uncomment external_redis if using external Redis server
external_redis:
  host: 10.255.169.198
  port: 6379
  password: xxxxx
  registry_db_index: 1
  jobservice_db_index: 2
```

* **Log files:** You can get them by package the `/var/log/harbor/` .
POST /api/registries failed with error: {"code":400,"message":"registry http://172.16.71.154:8800 is unhealthy: unhealthy"}
```
      Name                     Command               State             Ports
--------------------------------------------------------------------------------------
harbor-core         /harbor/start.sh                 Up
harbor-db           /entrypoint.sh postgres          Up      5432/tcp
harbor-jobservice   /harbor/start.sh                 Up
harbor-log          /bin/sh -c /usr/local/bin/ ...   Up      127.0.0.1:1514->10514/tcp
harbor-portal       nginx -g daemon off;             Up      80/tcp
nginx               nginx -g daemon off;             Up      0.0.0.0:8800->80/tcp
redis               docker-entrypoint.sh redis ...   Up      6379/tcp
registry            /entrypoint.sh /etc/regist ...   Up      5000/tcp
registryctl         /harbor/start.sh                 Up

[root@haihe03 ~]# curl -X GET "http://172.16.71.154:8800/api/health"
{
  "status": "healthy",
  "components": [
    {
      "name": "jobservice",
      "status": "healthy"
    },
    {
      "name": "redis",
      "status": "healthy"
    },
    {
      "name": "core",
      "status": "healthy"
    },
    {
      "name": "database",
      "status": "healthy"
    },
    {
      "name": "portal",
      "status": "healthy"
    },
    {
      "name": "registry",
      "status": "healthy"
    },
    {
      "name": "registryctl",
      "status": "healthy"
    }
  ]
}

```
