### ISSUE TITLE
Registry Push Succeeds, yet it retries. 

### ISSUE THREAD

**Issue by sfxworks** [goharbor/harbor#7950]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I want to push a test image to the harbor registry I have. 

The push refers to repository [harbor.sfxworks.net/quantomworks/nginx]
332fa54c5886: Retrying in 3 seconds
6ba094226eea: Retrying in 4 seconds
6270adb5794c: Retrying in 5 seconds

I am using nginx as a test. All three layers appear in OpenStack inside my project's harbor container in the path of `docker/registry/v2/repositories/quantomworks/nginx/_layers/sha256`. However, the docker cli continues to retry pushing these images. Our OpenStack uses radosgw, an s3 service by Ceph, for our object storage behind the scenes. 

**Steps to reproduce the problem:**
1. Configure harbor for s3
2. pull nginx
3. tag nginx for your harbor service
4. push nginx 

This issue is not replicable when I remove s3 as the storage service type. 

```
root@workbench:~/github/hook-to-k8s# docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
e7c96db7181b: Pull complete
Digest: sha256:769fddc7cc2f0a1c35abb2f91432e8beecf83916c421420e6a6da9f8975464b6
Status: Downloaded newer image for alpine:latest
root@workbench:~/github/hook-to-k8s# docker tag alpine:latest harbor.sfxworks.net/quantomworks/alpine:latest
root@workbench:~/github/hook-to-k8s# docker push harbor.sfxworks.net/quantomworks/alpine:latest
The push refers to repository [harbor.sfxworks.net/quantomworks/alpine]
f1b5933fe4b5: Pushed
latest: digest: sha256:bf1684a6e3676389ec861c602e97f27b03f14178e5bc3f70dce198f9f160cce9 size: 528
```

**Versions:**
```
Harbor v1.8.0
```
```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional context:**
```
# Configuration file of Harbor
hostname: harbor.sfxworks.net

http:
  port: 80

https:
  port: 443
  certificate: /etc/letsencrypt/live/harbor.sfxworks.net/fullchain.pem
  private_key: /etc/letsencrypt/live/harbor.sfxworks.net/privkey.pem


harbor_admin_password: [REDACTED]
database:
  password: [REDACTED]
data_volume: /data
#storage_service:
#  s3:
#    accesskey: [REDACTED]
#    secretkey: [REDACTED]
#    regionendpoint: https://swift.iad1.imhadmin.net
#    bucket: harbor
#    region: iad1

clair:
  updaters_interval: 12
  http_proxy:
  https_proxy:
  no_proxy: 127.0.0.1,localhost,core,registry

jobservice:
  max_job_workers: 5

chart:
  absolute_url: disabled

log:
  level: info
  rotate_count: 50
  rotate_size: 200M
  location: /var/log/harbor

_version: 1.8.0
```

* **Log files:** 
https://swift.iad1.imhadmin.net/swift/v1/61af61cc80b04e14a185f5a08e763d3c/ZAWARUDO/harbor-logs.tar.gz
