### ISSUE TITLE
how to disable 80 port

### ISSUE THREAD

**Issue by hyahm** [goharbor/harbor#8287]
in other app, useing 80
I want disable it
harbor 

```
# port for http, default is 80. If https enabled, this port will redirect to https port
```

**Comment by reasonerjt** [comment]
You can update the configuration file of nginx and restart harbor.
If you are using `docker-compose` to manage harbor the path is something like: `harbor/common/config/nginx/nginx.conf`

**Comment by reasonerjt** [comment]
Closing this issue.  As the question has been answered.

**Comment by achimnol** [comment]
I want to keep running my own webserver listening to port 80, while running Harbor on port 443 using HTTPS.
I commented out the http part of `harbor.yml` but the installer (`./install.sh`) keeps regenerating `common/config/nginx/nginx.conf`, causing the Harbor nginx to conflict with my webserver.
If I manually start the Harbor daemons using docker-compose, it works, but this is suboptimal solution because it is the recommended way to upgrade/restart the Harbor services using `install.sh` if I understand correctly.

So I believe that this issue should not be closed yet.
Please make it possible to "completely" disable the port 80 in the Harbor side using the official installer.

**Comment by achimnol** [comment]
A proper workaround is that configure the HTTP port in `harbor.yml` to something different.

**Comment by lazywhite** [comment]
I  encountered this problem too, can we just add enable switch for http and https like this ?
```
http:
  port: 80
  enable: false
https:
  port: 443
  enable: true
```

**Comment by BrianInAz** [comment]
I needed port 80 for something else while I was adding TLS. Ended up just configuring https and setting http to something other than 80 (8080 in my case).

`# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 8080

# https related config
https:
  # https port for harbor, default is 443
  port: 443
  # The path of cert and key files for nginx
  certificate: /etc/letsencrypt/live/harbor/fullchain.pem
  private_key: /etc/letsencrypt/live/harbor/privkey.pem`

Then I just re-run ./prepare, docker compose down, docker compose up.

**Comment by mirql** [comment]
if someone came here with the same problem, here it is:

```yaml
# ...
http:
  # this is default bind on all interfaces 
  # port: :80
  # But actually we can specify address
  # because this thing is just replacing docker-compose field for nginx binding
  port: 127.0.0.1:5080
# ...
```

after that again prepare-down-up and our compose file updated and now we dont use our public ips
