### ISSUE TITLE
Error response from daemon: unknown: The image is not signed in Notary.

### ISSUE THREAD

**Issue by duyanghao** [goharbor/harbor#8461]
**Expected behavior and actual behavior:**
Expected behavior:
`pull image` successfully from harbor when there are many docker
Actual behavior:
`pull image` successfully from harbor when there are only 100 docker, but failed when the number of docker increase to 300. And the error log of docker lists as below:
```
Error response from daemon: unknown: The image is not signed in Notary.
Error response from daemon: Get https://registry.xxx.com/v2/test_5/tomcat/manifests/v139: received unexpected HTTP status: 500 Internal Server Error
```

**Steps to reproduce the problem:**
run `docker pull` a image simultaneously on 300 docker machines.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.7.0(helm chart installed)
- docker engine version: 18.09.6

**Comment by reasonerjt** [comment]
@duyanghao 
Please provide the logs.

**Comment by Grounz** [comment]
i have the same probleme on Harbor 1.9.3, i have update harbor from 1.8.0 to 1.9.3 and sometimes when we pull many images we get this error:

`
Get https://URLHABOR/v2/PROJECT/IMAGES/manifests/TAGS: received unexpected HTTP status: 500 Internal Server Error
unknown: The image is not signed in Notary.
The image is not signed in Notary.
`
On this project the checkbox "content Trust" is not enabled, so Notary is not enabled for this project.

So i don't understand for why, we get this error beacause notary is not enabled.
Below, the logs from notary:

`Nov 25 18:18:20 172.28.0.1 notary-server[4071]: {"go.version":"go1.11.2","http.request.host":"notary-server:4443","http.request.id":"78cca97b-d078-4206-b390-23a085b25b4f","http.request.method":"GET","http.request.remoteaddr":"172.31.0.3:57346","http.request.uri":"/v2/harborURL/project/images/_trust/tuf/root.json","http.request.useragent":"Go-http-client/1.1","level":"info","msg":"metadata not found: You have requested metadata that does not exist.: No record found","time":"2019-11-25T17:18:20Z"}
`

For your information, i have just deployed notary but is not enabled on all project

**Comment by saravanakumar-periyasamy** [comment]
I too got the same error `Error response from daemon: unknown: The image is not signed in Notary.`

**Comment by duyanghao** [comment]
@saravanakumar-periyasamy @Grounz I guess the problem is `notary`, maybe you can try again without `notary` deployed.

**Comment by saravanakumar-periyasamy** [comment]
@duyanghao yes, it worked after disabling the content security check in my repo configuration.

**Comment by Grounz** [comment]
@duyanghao thanks for you answer. I have just do it docker-compose stop notary ? is there a some parameter to put to  off in Harbor configuration ?

**Comment by Grounz** [comment]
@duyanghao  i have do that:

`docker-compose stop notary-server notary-signer`

But after this change, i want test pull/push that is OK but i have tested to deleted tag and harbor and i get 500 internal Server Error. Si i have restarted notary-server notary-signer, i attempt to delete tag and project and is successful.

I think there is a configuration on notary to disabled but i dont knwo what.

**Comment by duyanghao** [comment]
@Grounz Could you provide the `docker-compose.yml` and harbor version?

**Comment by Grounz** [comment]
@duyanghao Please accept my apologies for the late response.

below there is my `docker-compose.yml` file:

```yaml
version: '2.3'
services:
  log:
    image: goharbor/harbor-log:v1.9.3
    container_name: harbor-log
    restart: always
    dns_search: .
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
      - ./common/config/log/logrotate.conf:/etc/logrotate.d/logrotate.conf:z
      - ./common/config/log/rsyslog_docker.conf:/etc/rsyslog.d/rsyslog_docker.conf:z
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor
  registry:
    image: goharbor/registry-photon:v2.7.1-patch-2819-v1.9.0
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /registre-data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: /registre-data/secret/registry/root.crt
        target: /etc/registry/root.crt
    networks:
      - harbor
      - harbor-clair
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  registryctl:
    image: goharbor/harbor-registryctl:v1.9.3
    container_name: registryctl
    env_file:
      - ./common/config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /registre-data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: ./common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
    networks:
      - harbor
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registryctl"
  postgresql:
    image: goharbor/harbor-db:v1.9.3
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /registre-data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
      harbor-notary:
        aliases:
          - harbor-db
      harbor-clair:
        aliases:
          - harbor-db
    dns_search: .
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "postgresql"
  core:
    image: goharbor/harbor-core:v1.9.3
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /registre-data/ca_download/:/etc/core/ca/:z
      - /registre-data/psc/:/etc/core/token/:z
      - /registre-data/:/data/:z
      - ./common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /registre-data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /registre-data/secret/keys/secretkey
        target: /etc/core/key
    networks:
      harbor:
      harbor-notary:
      harbor-clair:
        aliases:
          - harbor-core
    dns_search: .
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "core"
  portal:
    image: goharbor/harbor-portal:v1.9.3
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    networks:
      - harbor
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "portal"

  jobservice:
    image: goharbor/harbor-jobservice:v1.9.3
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /registre-data/job_logs:/var/log/jobs:z
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
    networks:
      - harbor
      - harbor-clair
    dns_search: .
    depends_on:
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  redis:
    image: goharbor/redis-photon:v1.9.3
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /registre-data/redis:/var/lib/redis
    networks:
      harbor:
    dns_search: .
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "redis"
  proxy:
    image: goharbor/nginx-photon:v1.9.3
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./common/config/nginx:/etc/nginx:z
      - /registre-data/secret/cert:/etc/cert:z
    networks:
      - harbor
      - harbor-notary
    dns_search: .
    ports:
      - 127.0.0.1:80:8080
      - 127.0.0.1:443:8443
      - 127.0.0.1:4443:4443
    depends_on:
      - registry
      - core
      - portal
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
  notary-server:
    image: goharbor/notary-server-photon:v0.6.1-v1.9.3
    container_name: notary-server
    restart: always
    networks:
      - notary-sig
      - harbor-notary
    dns_search: .
    volumes:
      - ./common/config/notary:/etc/notary:z
      - type: bind
        source: /registre-data/secret/notary/notary-signer-ca.crt
        target: /etc/notary/notary-signer-ca.crt
      - type: bind
        source: /registre-data/secret/registry/root.crt
        target: /etc/notary/root.crt
    env_file:
      - ./common/config/notary/server_env
    depends_on:
      - postgresql
      - notary-signer
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "notary-server"
  notary-signer:
    image: goharbor/notary-signer-photon:v0.6.1-v1.9.3
    container_name: notary-signer
    restart: always
    networks:
      harbor-notary:
      notary-sig:
        aliases:
          - notarysigner
    dns_search: .
    volumes:
      - ./common/config/notary:/etc/notary:z
      - type: bind
        source: /registre-data/secret/notary/notary-signer.crt
        target: /etc/notary/notary-signer.crt
      - type: bind
        source: /registre-data/secret/notary/notary-signer.key
        target: /etc/notary/notary-signer.key
    env_file:
      - ./common/config/notary/signer_env
    depends_on:
      - log
      - postgresql
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "notary-signer"
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: goharbor/clair-photon:v2.0.9-v1.9.2
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cpu_quota: 50000
    dns_search: .
    depends_on:
      - log
      - postgresql
    volumes:
      - type: bind
        source: ./common/config/clair/config.yaml
        target: /etc/clair/config.yaml
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
    env_file:
      ./common/config/clair/clair_env
networks:
  harbor:
    external: false
  harbor-notary:
    external: false
  notary-sig:
    external: false
  harbor-clair:
    external: false
```

So we have notary docker container which are running on the server but for the moment we don't use the signing image feature.

The harbor version is `v1.9.3-c80751b8`
