### ISSUE TITLE
Why create a redis container when I'm using external redis？？

### ISSUE THREAD

**Issue by pog2g** [goharbor/harbor#8671]
harbor.yml 
```
# Uncomment external_redis if using external Redis server
external_redis:
   host: redis
   port: 6379
   password:
#   # db_index 0 is for core, it's unchangeable
   registry_db_index: 1
   jobservice_db_index: 2
   chartmuseum_db_index: 3
```
![image](https://user-images.githubusercontent.com/48884933/63066617-967a0480-bf3d-11e9-91dd-d01abbc10a38.png)
