### ISSUE TITLE
[chartmuseum-photon] The absoluteUrl is not working

### ISSUE THREAD

**Issue by bcarriou** [goharbor/harbor#8865]
Hi,

I want to deployed some helm charts in Harbor and I need to have the absoluteUrl (ex: https://myregistry.com/chartrepo) in index.yaml.

I have configured `absoluteUrl: true` and in the configmap, I can see `CHART_URL: https://myregistry.com/chartrepo`.

But, when I push a helm chart in harbor, the `index.yaml` don't use the absoluteUrl:

```yaml
apiVersion: v1
entries:
  library/fhir-validator:
  - apiVersion: v1
    appVersion: 3.0.1
    created: "2019-08-28T09:36:18Z"
    description: A Helm chart for fhir-validator app
    digest: 7dfad51bb44cd6311c353cc0d9bc4a1f498ee62aed2687e836cfc27583fc2212
    keywords:
    - fhir-validator
    - ihe
    name: library/fhir-validator
    urls:
    - library/charts/fhir-validator-3.0.1.tgz
    version: 3.0.1
generated: "2019-08-28T09:46:16Z"
```

If I understand, it's should be:
```yaml
    urls:
    -https://myregistry.com/chartrepo/library/charts/fhir-validator-3.0.1.tgz`
```
Any idea ?

Version:

```yaml
goharbor/chartmuseum-photon:v0.9.0-v1.8.2
goharbor/clair-photon:v2.0.8-v1.8.2
goharbor/harbor-core:v1.8.2
goharbor/harbor-jobservice:v1.8.2
goharbor/nginx-photon:v1.8.2
goharbor/notary-server-photon:v0.6.1-v1.8.2
goharbor/notary-signer-photon:v0.6.1-v1.8.2
goharbor/harbor-portal:v1.8.2
goharbor/redis-photon:v1.8.2
goharbor/registry-photon:v2.7.1-patch-2819-v1.8.2
```

**Comment by bcarriou** [comment]
When I launched the `redis-cli FLUSHALL` command in my redis container, the absoluteUrl is set in `index.yaml`.

It's normal ?

**Comment by bcarriou** [comment]
Can you tell me why when I pushed a helm chart in harbor, this name change ?

In my Charts.yaml, I have:

```yaml
apiVersion: v1
appVersion: "3.0.1"
description: A Helm chart for fhir-validator app
name: fhir-validator
[...]
```
The name is `fhir-validator`.

When I pushed in `ihe` project for example, the name is changed to `ihe/fhir-validator` in `index.yaml`:

```yaml
apiVersion: v1
entries:
  ihe/fhir-validator:
  - apiVersion: v1
    appVersion: 3.0.1
    [...]
    name: ihe/fhir-validator
generated: "2019-08-28T10:27:26Z"
```
This changement of the name have a impact for example `rancher` tool who he spawed an error due to the slash:

```yaml
2019/08/28 10:25:14 [ERROR] CatalogController kereval-chart [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template kereval-chart-ihe/fhir-validator: CatalogTemplate.management.cattle.io "kereval-chart-ihe/fhir-validator" is invalid: metadata.name: Invalid value: "kereval-chart-ihe/fhir-validator": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') failed to create template kereval-chart-ihe/apache-nexus: CatalogTemplate.management.cattle.io "kereval-chart-ihe/apache-nexus" is invalid: metadata.name: Invalid value: "kereval-chart-ihe/apache-nexus": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

Any idea ?

Thx
