### ISSUE TITLE
specifiy the harbor network at install time

### ISSUE THREAD

**Issue by haai** [goharbor/harbor#9062]
Consider the following situation:

You have a VM with a default network in the subnet 172.20.0.0/16.
Using the installer creates the containers and networks used for the deployment and it creates a network (harbor_harbor) interfering with you default network and you could not reach your instance anymore.

Would it be possible to specify the network where the harbor configuration will be deployed into instead of touching the docker daemon in the first place?

something like in the `harbor.yml`
```yaml
networks:
  harbor: 172.16.0.0/16
  harbor_clair: 172.18.0.0/16
```
which renders the docker compose yaml file as
```yaml
networks:
  harbor:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/16
  harbor-clair:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16
```

or with external network which will be created upfront

```yaml
networks:
  harbor:
    external: yes
```
