### ISSUE TITLE
Wrong push and pull commands when http.port: 127.0.0.1:xyz

### ISSUE THREAD

**Issue by Strum355** [goharbor/harbor#9336]
UI shows:
```
Tag an image for this project:
docker tag SOURCE_IMAGE[:TAG] docker.domain.co:127.0.0.1:8081/netsoc/IMAGE[:TAG]
```

with the following config:
```yml
hostname: docker.domain.co

# http related config
http:
  port: 127.0.0.1:8081
````

As the harbor nginx is sitting behind an additional proxy, we dont want it listening on 0.0.0.0:8081 hence it was set to 127.0.0.1

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.9.0]
- docker engine version: [19.03.2]
- docker-compose version: [1.24.1]
