### ISSUE TITLE
Harbor1.5.4, registry storage OSS, SignatureDoesNotMatch 403

### ISSUE THREAD

**Issue by Leiyy1234** [goharbor/harbor#9702]
I want to use aliyun OSS storage, after modify common/registry/config.yml, as follows:
oss:
accesskeyid: ...
accesskeysecret: ...
region: ...
bucket: ...
endpoint: http://...

#docker-compose up

log:
"/var/log/harbor/registry.log" 20111L, 2630376C                                                                                                                          1,1           Top
Nov  1 12:20:58 172.29.0.1 registry[25684]: 2019/11/01 04:20:58 GET http://oss-ap-southeast-1.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix= ...
Nov  1 12:20:58 172.29.0.1 registry[25684]: **panic: Aliyun API Error: RequestId: 5DBBB2AA43AE613331823835 Status Code: 403 Code: SignatureDoesNotMatch Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.**
Nov  1 12:20:58 172.29.0.1 registry[25684]:
Nov  1 12:20:58 172.29.0.1 registry[25684]: goroutine 1 [running]:
Nov  1 12:20:58 172.29.0.1 registry[25684]: panic(0xb80460, 0xc420232c60)
Nov  1 12:20:58 172.29.0.1 registry[25684]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov  1 12:20:58 172.29.0.1 registry[25684]: github.com/docker/distribution/registry/handlers.NewApp(0x1067820, 0xc420394e40, 0xc420364a80, 0x1067820)

Is there anything else I should config to use OSS?

**Comment by datavisorwenjiehuang** [comment]
I have the same issue, hoping someone or the group can have  solution for this .

**Comment by lushang** [comment]
Note that your `endpoint` should follows below rule,
> An endpoint which defaults to [bucket].[region].aliyuncs.com or [bucket].[region]-internal.aliyuncs.com (when internal=true). You can change the default endpoint by changing this value.

These works for me:
```yaml
oss:
    accesskeyid: xxxxxxxxxxxx
    accesskeysecret: xxxxxxx
    region: oss-cn-shanghai
    endpoint: my-bucket.oss-cn-shanghai.aliyuncs.com
    bucket: my-bucket
```
or

```yaml
oss:
    accesskeyid: xxxxxxxxxxxx
    accesskeysecret: xxxxxxx
    region: oss-cn-shanghai
    endpoint: my-bucket.oss-cn-shanghai-internal.aliyuncs.com
    internal: true
    bucket: my-bucket
```

You can checkout more informaton on the official site of docker [here][1]

[1]: https://docs.docker.com/registry/storage-drivers/oss/
