### ISSUE TITLE
x509: certificate is not valid for any names, but wanted to match ecf-harbor.com

### ISSUE THREAD

**Issue by damozhiying** [goharbor/harbor#9821]
**Versions:**

```
- harbor version: v1.9.2
- docker engine version: 18.06.1-ce
- docker-compose version: 1.24.1
- system : CentOS Linux release 7.5.1804 (Core) 
```
**Additional context:**

```
harbor.yml
# The IP address or hostname to access admin UI and registry service.
# DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname: ecf-harbor.com 

# http related config
http:
  # port for http, default is 80. If https enabled, this port will redirect to https port
  port: 7080

# https related config
https:
#   # https port for harbor, default is 443
  port: 7443
#   # The path of cert and key files for nginx
  certificate: /data/harbor/cert/server.crt
  private_key: /data/harbor/cert/server.key
```
**login succes by browse**
![image](https://user-images.githubusercontent.com/10277950/68568853-a8653800-0497-11ea-9828-d311ccdcb6b9.png)

**docker login error**
```

openssl req -newkey rsa:4096 -nodes  -sha256 -keyout '/data/harbor/cert/server.key' -subj '/O=Harbor Server/OU=Self signed/CN=ecf-harbor.com' -new  -x509 -days 10000 -out '/data/harbor/cert/server.crt'
cat ca.crt >>/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
update-ca-trust 
cp ca.crt /etc/docker/certs.d//etc/docker/certs.d/ecf-harbor.com:7443/

 docker login https://ecf-harbor.com:7443
Username: admin
Password: 
Error response from daemon: Get https://ecf-harbor.com:7443/v2/: x509: certificate is not valid for any names, but wanted to match ecf-harbor.com
